// The sections of PLAN §4. Colours are the Original Fluoro inks for core sections and pastel
// inks for guest sections. The core sections are listed in print order; a design's colourway may override them.

export const sections = [
  // Core sections, in the order they print every day (PLAN §4, §6)
  {
    slug: "tech",
    name: "Tech",
    tagline: "Gadgets, AI and clever things people made",
    kind: "core",
    colour: "#2f5bff",
    voice: "witty",
  },
  {
    slug: "startups",
    name: "Startups",
    tagline: "Launches, founders and the odd brilliant idea",
    kind: "core",
    colour: "#00c2c7",
    voice: "witty",
  },
  {
    slug: "screen",
    name: "Screen",
    tagline: "Films, shows, anime and the trailers worth a look",
    kind: "core",
    colour: "#ff3d9a",
    voice: "witty",
  },
  {
    slug: "play",
    name: "Play",
    tagline: "Games, comics and the joy of pressing start",
    kind: "core",
    colour: "#36f28a",
    voice: "witty",
  },
  {
    slug: "music",
    name: "Music",
    tagline: "Albums, gigs, festivals and the artists behind them",
    kind: "core",
    colour: "#ff2e4d",
    voice: "witty",
  },
  {
    slug: "money",
    name: "Money",
    tagline: "Only the fun kind",
    kind: "core",
    colour: "#ffd21f",
    voice: "witty",
  },
  {
    slug: "sports",
    name: "Sports",
    tagline: "The moments worth talking about",
    kind: "core",
    colour: "#ff6a1f",
    voice: "witty",
  },
  {
    slug: "internet",
    name: "Internet",
    tagline: "The best of the internet and the delightfully odd, so you don't have to scroll",
    kind: "core",
    colour: "#b14bff",
    voice: "quirky",
  },
  {
    slug: "discoveries",
    name: "Discoveries",
    tagline: "Space, animals, plants and science finds",
    kind: "core",
    colour: "#e9ff1f",
    voice: "warm",
  },
  // Weekend sections: Saturday's "The Big Weekend" and Sunday's "The Scrapbook" print these in
  // place of the daily sections (PLAN §6). `kind` stays "core" (the database knows only core and
  // guest); `weekend` says which day prints them, and never reaches the database.
  {
    slug: "week-in-10",
    name: "The Week in 10",
    tagline: "The ten best stories from Monday to Friday, told again in short",
    kind: "core",
    colour: "#ff3d9a",
    voice: "witty",
    weekend: "saturday",
  },
  {
    slug: "weekend-guide",
    name: "Weekend Guide",
    tagline: "What to watch, stream and hear, and the gigs and festivals this weekend",
    kind: "core",
    colour: "#36f28a",
    voice: "witty",
    weekend: "saturday",
  },
  {
    slug: "sports-weekend",
    name: "Sports Weekend",
    tagline: "This weekend's big matches, fights and races, previewed",
    kind: "core",
    colour: "#ff6a1f",
    voice: "witty",
    weekend: "saturday",
  },
  {
    slug: "deep-dive",
    name: "Deep Dive",
    tagline: "One fascinating story, told properly",
    kind: "core",
    colour: "#2f5bff",
    voice: "warm",
    weekend: "saturday",
  },
  {
    slug: "photo-album",
    name: "Photo Album",
    tagline: "The week's best pictures",
    kind: "core",
    colour: "#ffd21f",
    voice: "warm",
    weekend: "sunday",
  },
  {
    slug: "hall-of-fame",
    name: "Hall of Fame",
    tagline: "The week's best animal, hero, record and internet moment",
    kind: "core",
    colour: "#b14bff",
    voice: "quirky",
    weekend: "sunday",
  },
  {
    slug: "slow-read",
    name: "Slow Read",
    tagline: "A relaxed long read for a Sunday",
    kind: "core",
    colour: "#e9ff1f",
    voice: "warm",
    weekend: "sunday",
  },
  {
    slug: "make-and-do",
    name: "Make & Do",
    tagline: "A recipe, a make, a playlist and a doodle",
    kind: "core",
    colour: "#00c2c7",
    voice: "quirky",
    weekend: "sunday",
  },
  {
    slug: "next-week",
    name: "Next Week",
    tagline: "The releases, launches and events coming up",
    kind: "core",
    colour: "#ff2e4d",
    voice: "witty",
    weekend: "sunday",
  },
  // Rotating guest sections: two a day between Discoveries and the back page, each once every
  // fourteen days (PLAN §4)
  {
    slug: "brain-snacks",
    name: "Brain Snacks",
    tagline: "Fun facts, general knowledge and how things work",
    kind: "guest",
    colour: "#e2d4f7",
    voice: "quirky",
  },
  {
    slug: "time-machine",
    name: "Time Machine",
    tagline: "On this day, 100 years ago, and history's weirder moments",
    kind: "guest",
    colour: "#f6e3b0",
    voice: "quirky",
  },
  {
    slug: "dig-site",
    name: "Dig Site",
    tagline: "Archaeology, ancient mysteries and lost things found",
    kind: "guest",
    colour: "#ead2b8",
    voice: "warm",
  },
  {
    slug: "tiny-science",
    name: "Tiny Science",
    tagline: "Small studies with delightfully big results",
    kind: "guest",
    colour: "#cdeefd",
    voice: "quirky",
  },
  {
    slug: "word-nerd",
    name: "Word Nerd",
    tagline: "A word of the day, an etymology, some slang and other languages",
    kind: "guest",
    colour: "#ffd9c2",
    voice: "quirky",
  },
  {
    slug: "food-and-drink",
    name: "Food & Drink",
    tagline: "Food news, new flavours and the recipes everyone is making",
    kind: "guest",
    colour: "#ffc6cc",
    voice: "quirky",
  },
  {
    slug: "art-and-design",
    name: "Art & Design",
    tagline: "Galleries, design, street art and buildings worth a look",
    kind: "guest",
    colour: "#c8d8f5",
    voice: "warm",
  },
  {
    slug: "shelf",
    name: "Books & Comics Shelf",
    tagline: "New releases, bestsellers and the adaptations on the way",
    kind: "guest",
    colour: "#dfe8c4",
    voice: "warm",
  },
  {
    slug: "drops",
    name: "Fashion & Sneakers",
    tagline: "Drops, collabs and the odder moments on the runway",
    kind: "guest",
    colour: "#f9d0ee",
    voice: "witty",
  },
  {
    slug: "postcards",
    name: "Postcards",
    tagline: "Travel, strange places and festivals around the world",
    kind: "guest",
    colour: "#c4ecdf",
    voice: "warm",
  },
  {
    slug: "good-humans",
    name: "Good Humans",
    tagline: "Kindness, everyday heroes and community wins",
    kind: "guest",
    colour: "#ffe3a8",
    voice: "warm",
  },
  {
    slug: "india-desk",
    name: "India Desk",
    tagline: "Happy news from around India",
    kind: "guest",
    colour: "#ffd6a8",
    voice: "warm",
  },
  {
    slug: "planet-wins",
    name: "Planet Wins",
    tagline: "Nature bouncing back, rewilding and clean energy",
    kind: "guest",
    colour: "#cfeec0",
    voice: "warm",
  },
  {
    slug: "animal-kingdom",
    name: "Animal Kingdom",
    tagline: "Zoo births, pets and animal antics",
    kind: "guest",
    colour: "#f3e0c6",
    voice: "warm",
  },
  {
    slug: "world-records",
    name: "World Records",
    tagline: "The biggest, smallest, fastest and most gloriously pointless",
    kind: "guest",
    colour: "#fff0a0",
    voice: "quirky",
  },
  {
    slug: "nostalgia",
    name: "Nostalgia Corner",
    tagline: "The 2000s and 2010s: old games, old tech, old favourites",
    kind: "guest",
    colour: "#e8d0ff",
    voice: "quirky",
  },
  {
    slug: "myth-busters",
    name: "Myth Busters",
    tagline: "Myths debunked and the surprising \u201cactually\u201d",
    kind: "guest",
    colour: "#d2e0e8",
    voice: "witty",
  },
  {
    slug: "future-stuff",
    name: "Future Stuff",
    tagline: "Concept tech, sci-fi coming true and missions on the way",
    kind: "guest",
    colour: "#c9f0f5",
    voice: "witty",
  },
  {
    slug: "your-small-wins",
    name: "Your Small Wins",
    tagline: "Small wins worth a cheer, from people like you",
    kind: "guest",
    colour: "#d6ecc0",
    voice: "warm",
  },
  {
    slug: "letters-and-classifieds",
    name: "Letters & Classifieds",
    tagline: "Funny letters and gloriously playful small ads",
    kind: "guest",
    colour: "#f0e6d2",
    voice: "quirky",
  },
  {
    slug: "feel-good-health",
    name: "Feel Good Health",
    tagline: "Sleep, wellbeing and the small science of feeling good",
    kind: "guest",
    colour: "#d4f2e4",
    voice: "warm",
  },
  {
    slug: "wheels",
    name: "Wheels",
    tagline: "Supercars, EVs, trains, planes and weird vehicles",
    kind: "guest",
    colour: "#ffd0b5",
    voice: "witty",
  },
  {
    slug: "creators",
    name: "Creator Economy",
    tagline: "YouTubers, streamers and creators doing fun things",
    kind: "guest",
    colour: "#f7c9e0",
    voice: "witty",
  },
  {
    slug: "pets-corner",
    name: "Pets Corner",
    tagline: "Cats, dogs and the pets who run the house",
    kind: "guest",
    colour: "#fbe2c2",
    voice: "warm",
  },
  {
    slug: "weird-local",
    name: "Weird Laws & Local",
    tagline: "Odd councils, dog mayors and gloriously strange local rules",
    kind: "guest",
    colour: "#e4e9b8",
    voice: "quirky",
  },
  {
    slug: "kids-and-schools",
    name: "Kids & Schools",
    tagline: "Kid inventors, school wins and young champions",
    kind: "guest",
    colour: "#c9e4ff",
    voice: "warm",
  },
  {
    slug: "weird-jobs",
    name: "Weird Jobs",
    tagline: "Unusual careers, brave switches and very cool internships",
    kind: "guest",
    colour: "#eed8c8",
    voice: "quirky",
  },
  {
    slug: "homes",
    name: "Homes & Buildings",
    tagline: "Tiny houses, treehouses, weird buildings and cosy rooms",
    kind: "guest",
    colour: "#dcd6f0",
    voice: "warm",
  },
] as const satisfies readonly {
  slug: string;
  name: string;
  tagline: string;
  kind: "core" | "guest";
  colour: string;
  voice: "witty" | "quirky" | "warm";
  /** Weekend-only sections: the day whose lineup prints them. */
  weekend?: "saturday" | "sunday";
}[];

/** A section as the database stores it (without the seed-only `weekend` tag). */
export const sectionRow = ({
  weekend: _weekend,
  ...s
}: (typeof sections)[number] & { weekend?: string }) => s;

/** The daily sections, in print order (weekdays). */
export const dailySections = sections.filter((s) => s.kind === "core" && !("weekend" in s));

/** The lineup of a weekend day, in print order. */
export const weekendSections = (day: "saturday" | "sunday") =>
  sections.filter((s) => "weekend" in s && s.weekend === day);

export type SectionSlug = (typeof sections)[number]["slug"];
