// Yay Attax: the shapes of a card. Pure types only, shared by the data files (leagues/*.ts), the
// draws, the album, Card Clash, Deck Battle and the share image.
//
// Cards are collectible cards of real, popular characters and people, in twelve leagues. Each
// league is a set family with its own frame, its own four stats (1–99) and its own "kind" (a
// Pokémon's type, a footballer's position, a fighter's weight class…).

export type LeagueId =
  | "pokemon"
  | "wwe"
  | "football"
  | "ipl"
  | "ufc"
  | "nba"
  | "marvel"
  | "dc"
  | "ben10"
  | "anime"
  | "f1"
  | "tv";

export const LEAGUE_IDS: readonly LeagueId[] = [
  "pokemon",
  "wwe",
  "football",
  "ipl",
  "ufc",
  "nba",
  "marvel",
  "dc",
  "ben10",
  "anime",
  "f1",
  "tv",
];

export type Rarity = "common" | "rare" | "epic" | "legendary";

export const RARITIES: readonly Rarity[] = ["common", "rare", "epic", "legendary"];

/**
 * When a card's subject was at their peak. Older eras are rarer: a 2010s card is Rare or better,
 * a 2000s card Epic or better, an all-time legend Epic or Legendary.
 */
export type Era = "current" | "2010s" | "2000s" | "legend";

export const ERAS: readonly Era[] = ["current", "2010s", "2000s", "legend"];

/** Four stats, 1–99, in the order of the league's `stats` names (leagues/meta.ts). */
export type Stats4 = readonly [number, number, number, number];

/** One card as a league's data file writes it. */
export type CardDef = {
  /** Unique within the league, kebab-case: "erling-haaland". Also the image's file name. */
  slug: string;
  name: string;
  /**
   * The league's own kind: a Pokémon's type ("fire", "grass/poison"), a footballer's position
   * ("ST"), a fighter's weight class, a Marvel/DC card's side ("hero", "villain", "antihero"),
   * a Ben 10 alien's species, an F1 car's "car"…
   */
  kind: string;
  /**
   * The team, club, series or show it belongs to ("Man City", "One Piece", "Breaking Bad"),
   * printed on the card and used for the album's sets and Deck Battle's team bonus.
   */
  team: string;
  /** The album set within the league (defaults to `team`). */
  set?: string;
  stats: Stats4;
  rarity: Rarity;
  era: Era;
  /** Relative pull weight among cards of the same rarity (default 1; fan favourites lower). */
  weight?: number;
  /** One line for the back of the card. */
  bio: string;
  /** Signature move, finisher, ability or quirk. */
  move?: string;
  /** Accent colour for the frame (a club's, a type's…), "#rrggbb". */
  colour?: string;
  /** A headline number printed big (a footballer's overall rating, a Pokémon's HP). */
  rating?: number;
  /** Pokémon: the official base stats (HP, the higher of Attack and Sp. Atk, Defense, Speed). */
  base?: Stats4;
  /** Pokémon: National Dex number and evolution line. */
  dex?: number;
  stage?: 1 | 2 | 3;
  /** The slug this card evolves into (collect 3 copies to evolve). */
  evolvesTo?: string;
  /** Season it was released in (default 1). */
  season?: number;
  /**
   * The day it drops into packs, "YYYY-MM-DD" (default: its season's first day). Until then it
   * isn't in any pack, scratch card or lucky dip, nor in the album (see drops.ts).
   */
  releasedOn?: string;
};

/** Where a card's picture came from (generated by scripts/fetch_card_images.py). */
export type CardImage = { src: string; credit: string };

/** A card as the app uses it: its data plus its league, id, number and picture. */
export type Card = CardDef & {
  /** `${league}:${slug}`. */
  id: string;
  league: LeagueId;
  set: string;
  season: number;
  releasedOn: string;
  /** Its number in the league, 1-based, and the league's size ("No. 7/64"). */
  no: number;
  of: number;
  image: CardImage | null;
};
