// The first half of the delight check (PLAN §9): a deterministic blocklist, run before any model
// sees a candidate. It is deliberately trigger-happy. A false reject costs nothing; a false allow
// costs trust. It runs over the headline, the summary and the full source text, because The Yay
// News carries no bad news at all, not even as backstory.

/** Each entry is a word stem matched at a word boundary, grouped by why it is here. */
export const BLOCKLIST: Record<string, readonly string[]> = {
  death: [
    "dead",
    "death",
    "deaths",
    "die",
    "died",
    "dies",
    "dying",
    "killed",
    "killing",
    "kills",
    "fatal",
    "fatally",
    "fatalities",
    "obituary",
    "funeral",
    "passed away",
    "rest in peace",
    "mourn",
    "mourning",
    "grieving",
    "grief",
    "bereaved",
    "corpse",
    "body was found",
    "remains were",
    "late husband",
    "late wife",
    "late father",
    "late mother",
    "late son",
    "late daughter",
    "late grandfather",
    "late grandmother",
    "late friend",
    "memory of the late",
    "honour of the late",
    "honor of the late",
    "in memory of",
    "in loving memory",
    "posthumous",
    "posthumously",
    "widowed",
    "widower",
    "orphaned",
    "lost his battle",
    "lost her battle",
    "hospice",
    "life support",
  ],
  violence: [
    "murder",
    "murdered",
    "homicide",
    "stabbing",
    "stabbed",
    "shooting",
    "shootings",
    "gunman",
    "gunfire",
    "assault",
    "assaulted",
    "attack",
    "attacked",
    "attacks",
    "bomb",
    "bombing",
    "explosion",
    "terror",
    "terrorist",
    "terrorism",
    "hostage",
    "massacre",
    "abuse",
    "abused",
    "rape",
    "kidnap",
    "kidnapped",
    "violence",
    "violent",
    "weapon",
    "weapons",
    "missile",
    "missiles",
  ],
  war: [
    "war",
    "wars",
    "warfare",
    "invasion",
    "airstrike",
    "airstrikes",
    "troops",
    "genocide",
    "refugee",
    "refugees",
    "conflict",
    "ceasefire",
    "militia",
    "unrest",
    "hostilities",
    "security concerns",
    "security situation",
    "relocated due to",
    "moved due to",
    "because of the war",
    "tensions in",
  ],
  illness: [
    "cancer",
    "tumour",
    "tumor",
    "terminal",
    "disease",
    "outbreak",
    "pandemic",
    "epidemic",
    "virus",
    "covid",
    "infection",
    "overdose",
    "suicide",
    "depression",
    "dementia",
    "hospitalised",
    "hospitalized",
    "intensive care",
    "diagnosed",
    "injured",
    "injuries",
    "injury",
    "paralysed",
    "paralyzed",
    "amputat",
    "illness",
    "illnesses",
    "ailing",
    "chemotherapy",
    "chemo",
    "leukaemia",
    "leukemia",
    "heart attack",
    "surgery",
    "transplant",
    "diagnosis",
    "terminally",
    "sick child",
    "seriously ill",
    "critically ill",
    "brain injury",
    "coma",
    "stroke survivor",
    "wheelchair-bound",
    "disabled after",
    "measles",
    "ebola",
    "mpox",
  ],
  disaster: [
    "disaster",
    "tragedy",
    "tragic",
    "catastrophe",
    "catastrophic",
    "crash",
    "crashed",
    "collision",
    "earthquake",
    "tsunami",
    "hurricane",
    "tornado",
    "wildfire",
    "wildfires",
    "flood",
    "flooding",
    "famine",
    "drought",
    "heatwave",
    "evacuat",
    "collapse",
    "collapsed",
    "extinct",
    "extinction",
    "endangered",
    "poaching",
    "climate crisis",
    "emergency",
    "tropical storm",
    "storm damage",
    "storm hit",
    "storm hits",
    "severe weather",
    "extreme weather",
    "cyclone",
    "typhoon",
    "landslide",
    "landslides",
    "avalanche",
    "blaze",
    "inferno",
    "burned down",
    "burnt down",
    "floods",
    "sinkhole",
    "wreckage",
    "rubble",
    "aftermath",
    "devastation",
    "destroyed",
    "power cut",
    "power cuts",
    "survivors",
    "rescue workers",
    "rescue teams",
    "rescue crews",
    "search and rescue",
    "derailed",
    "derailment",
    "plane crash",
    "car crash",
  ],
  crime: [
    "crime",
    "criminal",
    "arrest",
    "arrested",
    "prison",
    "jail",
    "jailed",
    "convicted",
    "sentenced",
    "police",
    "lawsuit",
    "sued",
    "suing",
    "fraud",
    "scam",
    "scandal",
    "stolen",
    "theft",
    "hacked",
    "data breach",
    "ransomware",
    "investigation",
    "charged with",
    "robbery",
    "robbed",
    "robber",
    "burglary",
    "burglar",
    "burglars",
    "smuggling",
    "smuggled",
    "smuggler",
    "shoplifting",
    "shoplifter",
    "vandal",
    "vandals",
    "vandalism",
    "vandalised",
    "vandalized",
    "fugitive",
    "suspect",
    "suspects",
    "on trial",
    "stood trial",
    "offender",
    "offenders",
    "detained",
    "custody",
    "inmate",
    "inmates",
    "prisoners",
    "pleaded guilty",
    "found guilty",
    "heist",
    "looted",
    "looting",
    "trespass",
    "trespassing",
    "illegal",
    "illegally",
  ],
  money: [
    "layoff",
    "layoffs",
    "laid off",
    "redundancies",
    "recession",
    "inflation",
    "bankrupt",
    "bankruptcy",
    "downturn",
    "stocks fell",
    "shares fell",
    "plunge",
    "plunged",
    "slump",
    "crisis",
    "debt",
    "shutdown",
    "tariff",
    "tariffs",
    "sanctions",
    "poverty",
    "homeless",
    "homelessness",
  ],
  politics: [
    "election",
    "elections",
    "senator",
    "senate",
    "congress",
    "parliament",
    "prime minister",
    "white house",
    "republican",
    "democrat",
    "trump",
    "biden",
    "putin",
    "protest",
    "protests",
    "riot",
    "immigration",
    "deport",
    "politics",
    "political",
    "politician",
    "politicians",
    "lawmaker",
    "lawmakers",
    "legislation",
    "legislator",
    "legislators",
    "minister",
    "ministers",
    "governor",
    "campaign trail",
    "voters",
    "voter",
    "ballot",
    "polling station",
    "opposition party",
    "opposition leader",
    "ruling party",
    "partisan",
    "mps",
    "democrats",
    "republicans",
    "modi",
    "starmer",
    "labour party",
    "conservative party",
    "tory",
    "tories",
    "bjp",
    "geopolitical",
    "diplomatic",
    "embassy",
  ],
  mood: [
    "controversy",
    "controversial",
    "backlash",
    "outrage",
    "slammed",
    "furious",
    "fear",
    "fears",
    "threat",
    "threatened",
    "threatens",
    "warning",
    "danger",
    "dangerous",
    "victim",
    "victims",
    "horror",
    "horrific",
    "devastating",
    "devastated",
    "heartbreaking",
    "struggle",
    "struggling",
    "toxic",
    "banned",
    "cancelled",
    "canceled",
    "delayed",
    "recall",
    "lost his",
    "lost her",
    "lost their",
    "rip",
  ],
  // Grumbles and discomfort: light in tone, but not the paper's kind of story.
  gripes: [
    "sweltering",
    "heatwave",
    "heat wave",
    "scorching",
    "return to office",
    "return-to-office",
    "burnout",
    "burned out",
    "quiet quitting",
    "toxic boss",
    "micromanaging",
    "micromanager",
    "cost of living",
    "cost-of-living",
    "commuter misery",
    "delays and cancellations",
    "sacked",
    "suspended",
    "suspension",
    "banned",
    "doping",
    "scandal",
    "relegated",
    "relegation",
    "humiliat",
    "thrashed",
    "crushing defeat",
    "furious",
    "slammed",
    "backlash",
  ],
  // Job cuts, however they are dressed.
  jobs: [
    "job cuts",
    "job losses",
    "jobs cut",
    "cut jobs",
    "cuts jobs",
    "cutting jobs",
    "axe jobs",
    "axes jobs",
    "jobs axed",
    "axing",
    "jobs at risk",
    "lay off",
    "lays off",
    "laying off",
    "made redundant",
    "workforce reduction",
    "headcount reduction",
    "restructuring",
    "lost their jobs",
    "lost his job",
    "lost her job",
    "unemployment",
    "unemployed",
    "hiring freeze",
    "strike action",
    "on strike",
  ],
  legal: [
    "lawsuit",
    "lawsuits",
    "sues",
    "legal action",
    "legal battle",
    "legal fight",
    "legal dispute",
    "class action",
    "class-action",
    "litigation",
    "court case",
    "in court",
    "high court",
    "supreme court",
    "court ruling",
    "court hearing",
    "court order",
    "judge ruled",
    "injunction",
    "antitrust",
    "infringement",
    "regulator fined",
    "fined",
    "penalty notice",
  ],
  // Prices going up and the cost of living, even as a "how to save" hook.
  prices: [
    "price rise",
    "price rises",
    "prices rise",
    "prices rising",
    "rising prices",
    "price hike",
    "price hikes",
    "fare hike",
    "rate hike",
    "rate hikes",
    "price increase",
    "price increases",
    "prices soar",
    "soaring prices",
    "prices surge",
    "more expensive",
    "pricier",
    "costlier",
    "energy bills",
    "energy bill",
    "bills rise",
    "rent rise",
    "rent rises",
    "rent hike",
    "unaffordable",
    "affordability",
    "cost-of-living crisis",
    "price cap",
    "stagflation",
  ],
  // War and conflict, including whatever was moved or cancelled because of it.
  relocation: [
    "displaced",
    "fled",
    "fleeing",
    "relocated from",
    "war-torn",
    "conflict zone",
    "amid the conflict",
    "amid tensions",
    "wartime",
    "occupied territory",
    "shelling",
    "frontline",
    "front line",
    "air raid",
    "blockade",
  ],
  scandal: [
    "scandal",
    "scandals",
    "disgraced",
    "misconduct",
    "allegation",
    "allegations",
    "alleged",
    "allegedly",
    "accused",
    "accusation",
    "accusations",
    "cheating",
    "cheated",
    "resigned",
    "resignation",
    "resigns",
    "ousted",
    "was fired",
    "been fired",
    "got fired",
    "whistleblower",
    "cover-up",
    "wrongdoing",
  ],
  // "Sad but…": a happy ending on a sad start is still a sad story.
  sadBut: [
    "sad",
    "sadly",
    "bittersweet",
    "silver lining",
    "despite losing",
    "after losing",
    "survivor",
    "survived",
    "hardship",
    "heartbroken",
    "heartbreak",
    "tearful",
    "in tears",
    "loneliness",
    "grieve",
  ],
  animalHarm: [
    "left for dead",
    "run over",
    "hit by a car",
    "struck by a car",
    "abandoned",
    "neglected",
    "neglect",
    "cruelty",
    "mistreated",
    "mistreatment",
    "starving",
    "starved",
    "malnourished",
    "emaciated",
    "entangled",
    "stranded",
    "trapped",
    "rescued from",
    "was rescued",
    "were rescued",
    "had to be rescued",
    "cull",
    "culled",
    "culling",
    "slaughter",
    "slaughtered",
    "euthanised",
    "euthanized",
    "was put down",
    "roadkill",
    "oil spill",
    "trophy hunting",
    "wounded",
    "bleeding",
    "mauled",
    "bitten",
  ],
  clickbait: ["you won't believe", "heartwarming", "shocking", "nsfw"],
};

type Entry = { group: string; word: string };

// Entries indexed by their first word, so a text is read once, word by word, however long the list.
// A stem (an entry ending in "at": "amputat", "evacuat") matches any word it begins.
const BY_FIRST_WORD = new Map<string, Entry[]>();
const STEMS: Entry[] = [];
for (const [group, words] of Object.entries(BLOCKLIST)) {
  for (const w of words) {
    const word = w.toLowerCase();
    if (word.endsWith("at") && !/[^\p{L}]/u.test(word)) {
      STEMS.push({ group, word });
      continue;
    }
    const first = word.match(/^\p{L}+/u)?.[0] ?? word;
    BY_FIRST_WORD.set(first, [...(BY_FIRST_WORD.get(first) ?? []), { group, word }]);
  }
}
const LETTER = /\p{L}/u;

export type BlocklistHit = { group: string; word: string };

/**
 * The first blocklisted term in `text` (earliest in the text), or null when it is clean. Terms match
 * whole words: "war" is not in "award", and "attack" is not in "attacks" unless listed.
 */
export function blocklistHit(text: string): BlocklistHit | null {
  const t = text.replace(/[’‘]/g, "'").toLowerCase();
  for (const m of t.matchAll(/\p{L}+/gu)) {
    const at = m.index ?? 0;
    for (const e of BY_FIRST_WORD.get(m[0]) ?? []) {
      if (!t.startsWith(e.word, at)) continue;
      const next = t[at + e.word.length];
      if (next === undefined || !LETTER.test(next)) return { group: e.group, word: e.word };
    }
    for (const e of STEMS) if (m[0].startsWith(e.word)) return { group: e.group, word: e.word };
  }
  return null;
}
