// The first half of the delight check (PLAN §9): a deterministic blocklist, run before any model
// sees a candidate. It is deliberately trigger-happy. A false reject costs nothing; a false allow
// costs trust. It runs over the headline, the summary and the full source text, because The Yay
// News carries no bad news at all, not even as backstory.

/** Each entry is a word stem matched at a word boundary, grouped by why it is here. */
export const BLOCKLIST: Record<string, readonly string[]> = {
  death: [
    "dead",
    "death",
    "deaths",
    "die",
    "died",
    "dies",
    "dying",
    "killed",
    "killing",
    "kills",
    "fatal",
    "fatally",
    "fatalities",
    "obituary",
    "funeral",
    "passed away",
    "rest in peace",
    "mourn",
    "mourning",
    "grieving",
    "grief",
    "bereaved",
    "corpse",
    "body was found",
    "remains were",
  ],
  violence: [
    "murder",
    "murdered",
    "homicide",
    "stabbing",
    "stabbed",
    "shooting",
    "shootings",
    "gunman",
    "gunfire",
    "assault",
    "assaulted",
    "attack",
    "attacked",
    "attacks",
    "bomb",
    "bombing",
    "explosion",
    "terror",
    "terrorist",
    "terrorism",
    "hostage",
    "massacre",
    "abuse",
    "abused",
    "rape",
    "kidnap",
    "kidnapped",
    "violence",
    "violent",
    "weapon",
    "weapons",
    "missile",
    "missiles",
  ],
  war: [
    "war",
    "wars",
    "warfare",
    "invasion",
    "airstrike",
    "airstrikes",
    "troops",
    "genocide",
    "refugee",
    "refugees",
    "conflict",
    "ceasefire",
    "militia",
    "unrest",
    "hostilities",
    "security concerns",
    "security situation",
    "relocated due to",
    "moved due to",
    "because of the war",
    "tensions in",
  ],
  illness: [
    "cancer",
    "tumour",
    "tumor",
    "terminal",
    "disease",
    "outbreak",
    "pandemic",
    "epidemic",
    "virus",
    "covid",
    "infection",
    "overdose",
    "suicide",
    "depression",
    "dementia",
    "hospitalised",
    "hospitalized",
    "intensive care",
    "diagnosed",
    "injured",
    "injuries",
    "injury",
    "paralysed",
    "paralyzed",
    "amputat",
  ],
  disaster: [
    "disaster",
    "tragedy",
    "tragic",
    "catastrophe",
    "catastrophic",
    "crash",
    "crashed",
    "collision",
    "earthquake",
    "tsunami",
    "hurricane",
    "tornado",
    "wildfire",
    "wildfires",
    "flood",
    "flooding",
    "famine",
    "drought",
    "heatwave",
    "evacuat",
    "collapse",
    "collapsed",
    "extinct",
    "extinction",
    "endangered",
    "poaching",
    "climate crisis",
    "emergency",
  ],
  crime: [
    "crime",
    "criminal",
    "arrest",
    "arrested",
    "prison",
    "jail",
    "jailed",
    "convicted",
    "sentenced",
    "police",
    "lawsuit",
    "sued",
    "suing",
    "fraud",
    "scam",
    "scandal",
    "stolen",
    "theft",
    "hacked",
    "data breach",
    "ransomware",
    "investigation",
  ],
  money: [
    "layoff",
    "layoffs",
    "laid off",
    "redundancies",
    "recession",
    "inflation",
    "bankrupt",
    "bankruptcy",
    "downturn",
    "stocks fell",
    "shares fell",
    "plunge",
    "plunged",
    "slump",
    "crisis",
    "debt",
    "shutdown",
    "tariff",
    "tariffs",
    "sanctions",
    "poverty",
    "homeless",
    "homelessness",
  ],
  politics: [
    "election",
    "elections",
    "senator",
    "senate",
    "congress",
    "parliament",
    "prime minister",
    "white house",
    "republican",
    "democrat",
    "trump",
    "biden",
    "putin",
    "protest",
    "protests",
    "riot",
    "immigration",
    "deport",
  ],
  mood: [
    "controversy",
    "controversial",
    "backlash",
    "outrage",
    "slammed",
    "furious",
    "fear",
    "fears",
    "threat",
    "threatened",
    "threatens",
    "warning",
    "danger",
    "dangerous",
    "victim",
    "victims",
    "horror",
    "horrific",
    "devastating",
    "devastated",
    "heartbreaking",
    "struggle",
    "struggling",
    "toxic",
    "banned",
    "cancelled",
    "canceled",
    "delayed",
    "recall",
    "lost his",
    "lost her",
    "lost their",
    "rip",
  ],
  // Grumbles and discomfort: light in tone, but not the paper's kind of story.
  gripes: [
    "sweltering",
    "heatwave",
    "heat wave",
    "scorching",
    "return to office",
    "return-to-office",
    "burnout",
    "burned out",
    "quiet quitting",
    "toxic boss",
    "micromanaging",
    "micromanager",
    "cost of living",
    "cost-of-living",
    "commuter misery",
    "delays and cancellations",
    "sacked",
    "suspended",
    "suspension",
    "banned",
    "doping",
    "scandal",
    "relegated",
    "relegation",
    "humiliat",
    "thrashed",
    "crushing defeat",
    "furious",
    "slammed",
    "backlash",
  ],
  clickbait: ["you won't believe", "heartwarming", "shocking", "nsfw"],
};

const PATTERNS = Object.entries(BLOCKLIST).flatMap(([group, words]) =>
  words.map((w) => ({
    group,
    word: w,
    re: new RegExp(
      `(?:^|[^\\p{L}])${w.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}${w.endsWith("at") ? "" : "(?![\\p{L}])"}`,
      "iu",
    ),
  })),
);

export type BlocklistHit = { group: string; word: string };

/** The first blocklisted term in `text`, or null when it is clean. */
export function blocklistHit(text: string): BlocklistHit | null {
  const normalised = text.replace(/[’‘]/g, "'");
  for (const p of PATTERNS) if (p.re.test(normalised)) return { group: p.group, word: p.word };
  return null;
}
