// Generated by scripts/fetch_card_images.py from scripts/card-images/anime.json. Do not edit:
// change the manifest and run the script again.

import type { CardImage } from "../types.ts";

export const images: Record<string, CardImage> = {
  "monkey-d-luffy": { src: "/cards/anime/monkey-d-luffy.png", credit: "Wikipedia · Fair use" },
  "satoru-gojo": {
    src: "/cards/anime/satoru-gojo.png",
    credit: "Wikipedia · Akutami, Gege, Fair use",
  },
  "naruto-uzumaki": { src: "/cards/anime/naruto-uzumaki.png", credit: "Wikipedia · Fair use" },
  goku: { src: "/cards/anime/goku.jpg", credit: "Wikipedia · Shueisha; Akira Toriyama, Fair use" },
};
