// Generated by scripts/fetch_card_images.py from scripts/card-images/ben10.json. Do not edit:
// change the manifest and run the script again.

import type { CardImage } from "../types.ts";

export const images: Record<string, CardImage> = {
  "ben-tennyson": { src: "/cards/ben10/ben-tennyson.png", credit: "Ben10 Fandom wiki" },
  heatblast: { src: "/cards/ben10/heatblast.png", credit: "Ben10 Fandom wiki" },
  "four-arms": { src: "/cards/ben10/four-arms.png", credit: "Ben10 Fandom wiki" },
  xlr8: { src: "/cards/ben10/xlr8.png", credit: "Ben10 Fandom wiki" },
};
