// Generated by scripts/fetch_card_images.py from scripts/card-images/dc.json. Do not edit:
// change the manifest and run the script again.

import type { CardImage } from "../types.ts";

export const images: Record<string, CardImage> = {
  batman: { src: "/cards/dc/batman.jpg", credit: "Wikipedia · DC Comics, Fair use" },
  superman: { src: "/cards/dc/superman.png", credit: "Wikipedia · Jason Fabok, Fair use" },
  "wonder-woman": { src: "/cards/dc/wonder-woman.jpg", credit: "Dc Fandom wiki" },
  joker: { src: "/cards/dc/joker.jpg", credit: "Wikipedia · Fair use" },
};
