// Generated by scripts/fetch_card_images.py from scripts/card-images/f1.json. Do not edit:
// change the manifest and run the script again.

import type { CardImage } from "../types.ts";

export const images: Record<string, CardImage> = {
  "lando-norris": {
    src: "/cards/f1/lando-norris.jpg",
    credit: "Wikimedia Commons · Original: Steffen Prößdorf; Derivative…, CC BY-SA 4.0",
  },
  "max-verstappen": {
    src: "/cards/f1/max-verstappen.jpg",
    credit: "Wikimedia Commons · Steffen Prößdorf, CC BY-SA 4.0",
  },
  "lewis-hamilton": {
    src: "/cards/f1/lewis-hamilton.jpg",
    credit: "Wikimedia Commons · Picture by Lauren Hurley / No 10 Downi…, OGL 3",
  },
  "ayrton-senna": {
    src: "/cards/f1/ayrton-senna.jpg",
    credit: "Wikimedia Commons · File:Ayrton Senna 2.jpg: Instituto Ayr…, CC BY 2.0",
  },
};
