// Yay Attax · Club Football. Match Attax style: a position, a club, an overall rating (roughly
// the players' game ratings) and four stats.

import type { CardDef } from "../types.ts";

export const cards: CardDef[] = [
  {
    slug: "erling-haaland",
    name: "Erling Haaland",
    kind: "ST",
    team: "Man City",
    rating: 91,
    stats: [96, 45, 76, 89],
    rarity: "common",
    era: "current",
    bio: "Scored 36 Premier League goals in his first season, a league record.",
    move: "Near-post rocket",
    colour: "#6cabdd",
  },
  {
    slug: "kylian-mbappe",
    name: "Kylian Mbappé",
    kind: "ST",
    team: "Real Madrid",
    rating: 91,
    stats: [94, 38, 84, 97],
    rarity: "rare",
    era: "current",
    bio: "A World Cup winner at 19, and a hat-trick in the 2022 final.",
    move: "Curled finish",
    colour: "#febe10",
  },
  {
    slug: "lamine-yamal",
    name: "Lamine Yamal",
    kind: "RW",
    team: "Barcelona",
    rating: 89,
    stats: [88, 40, 88, 90],
    rarity: "common",
    era: "current",
    bio: "Won Euro 2024 at 17, and its youngest-ever scorer.",
    move: "Outside-of-the-boot curler",
    colour: "#a50044",
  },
  {
    slug: "lionel-messi",
    name: "Lionel Messi",
    kind: "RW",
    team: "Barcelona",
    rating: 95,
    stats: [97, 38, 99, 88],
    rarity: "legendary",
    era: "legend",
    weight: 0.8,
    bio: "Eight Ballon d'Ors, a record, and the 2022 World Cup with Argentina.",
    move: "Slalom dribble",
    colour: "#a50044",
  },
  {
    slug: "cristiano-ronaldo",
    name: "Cristiano Ronaldo",
    kind: "ST",
    team: "Real Madrid",
    rating: 94,
    stats: [98, 40, 86, 93],
    rarity: "legendary",
    era: "legend",
    weight: 0.8,
    bio: "Five Champions Leagues and the most goals in men's international football.",
    move: "Knuckleball free kick",
    colour: "#febe10",
  },
];
