// Generated by scripts/fetch_card_images.py from scripts/card-images/football.json. Do not edit:
// change the manifest and run the script again.

import type { CardImage } from "../types.ts";

export const images: Record<string, CardImage> = {
  "erling-haaland": {
    src: "/cards/football/erling-haaland.jpg",
    credit: "Wikimedia Commons · Bryan Berlin, CC BY-SA 4.0",
  },
  "kylian-mbappe": {
    src: "/cards/football/kylian-mbappe.jpg",
    credit: "Wikimedia Commons · Bryan Berlin, CC BY-SA 4.0",
  },
  "lamine-yamal": {
    src: "/cards/football/lamine-yamal.jpg",
    credit: "Wikimedia Commons · Bryan Berlin, CC BY-SA 4.0",
  },
  "lionel-messi": {
    src: "/cards/football/lionel-messi.jpg",
    credit: "Wikimedia Commons · Bryan Berlin, CC BY-SA 4.0",
  },
  "cristiano-ronaldo": {
    src: "/cards/football/cristiano-ronaldo.jpg",
    credit: "Wikimedia Commons · Bryan Berlin, CC BY-SA 4.0",
  },
};
