// Generated by scripts/fetch_card_images.py from scripts/card-images/ipl.json. Do not edit:
// change the manifest and run the script again.

import type { CardImage } from "../types.ts";

export const images: Record<string, CardImage> = {
  "virat-kohli": {
    src: "/cards/ipl/virat-kohli.jpg",
    credit: "Wikimedia Commons · Prime Minister's Office, GODL-India",
  },
  "rohit-sharma": {
    src: "/cards/ipl/rohit-sharma.jpg",
    credit: "Wikimedia Commons · Prime Minister's Office, GODL-India",
  },
  "jasprit-bumrah": {
    src: "/cards/ipl/jasprit-bumrah.jpg",
    credit: "Wikimedia Commons · Prime Minister's Office, GODL-India",
  },
  "ms-dhoni": { src: "/cards/ipl/ms-dhoni.jpg", credit: "Wikimedia Commons · RIGI, CC BY 3.0" },
};
