// Generated by scripts/fetch_card_images.py from scripts/card-images/marvel.json. Do not edit:
// change the manifest and run the script again.

import type { CardImage } from "../types.ts";

export const images: Record<string, CardImage> = {
  "spider-man": {
    src: "/cards/marvel/spider-man.jpg",
    credit: "Wikipedia · Mike McKone and Morry Hollowell / Marv…, Fair use",
  },
  "iron-man": { src: "/cards/marvel/iron-man.jpg", credit: "Wikipedia · Marvel Comics, Fair use" },
  hulk: { src: "/cards/marvel/hulk.png", credit: "Wikipedia · Fair use" },
  thanos: {
    src: "/cards/marvel/thanos.png",
    credit: "Wikipedia · Dike Ruan / Marvel Comics, Fair use",
  },
};
