// Generated by scripts/fetch_card_images.py from scripts/card-images/nba.json. Do not edit:
// change the manifest and run the script again.

import type { CardImage } from "../types.ts";

export const images: Record<string, CardImage> = {
  "lebron-james": {
    src: "/cards/nba/lebron-james.jpg",
    credit: "Wikimedia Commons · Erik Drost, CC BY 2.0",
  },
  "stephen-curry": {
    src: "/cards/nba/stephen-curry.jpg",
    credit: "Wikimedia Commons · Clément Bardot, CC BY-SA 4.0",
  },
  "kobe-bryant": {
    src: "/cards/nba/kobe-bryant.jpg",
    credit: "Wikimedia Commons · Keith Allison, CC BY-SA 2.0",
  },
  "michael-jordan": {
    src: "/cards/nba/michael-jordan.jpg",
    credit: "Wikimedia Commons · DOD photo by D. Myles Cullen, PD",
  },
};
