// Generated by scripts/fetch_card_images.py from scripts/card-images/pokemon.json. Do not edit:
// change the manifest and run the script again.

import type { CardImage } from "../types.ts";

export const images: Record<string, CardImage> = {
  pikachu: {
    src: "/cards/pokemon/pikachu.png",
    credit: "Official artwork © The Pokémon Company, via PokéAPI",
  },
  charmander: {
    src: "/cards/pokemon/charmander.png",
    credit: "Official artwork © The Pokémon Company, via PokéAPI",
  },
  charmeleon: {
    src: "/cards/pokemon/charmeleon.png",
    credit: "Official artwork © The Pokémon Company, via PokéAPI",
  },
  charizard: {
    src: "/cards/pokemon/charizard.png",
    credit: "Official artwork © The Pokémon Company, via PokéAPI",
  },
  mewtwo: {
    src: "/cards/pokemon/mewtwo.png",
    credit: "Official artwork © The Pokémon Company, via PokéAPI",
  },
};
