// Generated by scripts/fetch_card_images.py from scripts/card-images/tv.json. Do not edit:
// change the manifest and run the script again.

import type { CardImage } from "../types.ts";

export const images: Record<string, CardImage> = {
  eleven: { src: "/cards/tv/eleven.jpg", credit: "Wikipedia · Netflix, Fair use" },
  "wednesday-addams": {
    src: "/cards/tv/wednesday-addams.jpg",
    credit: "Wikimedia Commons · Harald Krichel, CC BY-SA 4.0",
  },
  "walter-white": { src: "/cards/tv/walter-white.jpg", credit: "Wikipedia · AMC, Fair use" },
  "michael-scott": { src: "/cards/tv/michael-scott.jpg", credit: "Wikipedia · Fair use" },
};
