// Generated by scripts/fetch_card_images.py from scripts/card-images/ufc.json. Do not edit:
// change the manifest and run the script again.

import type { CardImage } from "../types.ts";

export const images: Record<string, CardImage> = {
  "alex-pereira": {
    src: "/cards/ufc/alex-pereira.jpg",
    credit: "Wikimedia Commons · U.S. Department of the Interior, PD",
  },
  "jon-jones": {
    src: "/cards/ufc/jon-jones.jpg",
    credit: "Wikimedia Commons · Senate Democrats, CC BY 2.0",
  },
  "conor-mcgregor": {
    src: "/cards/ufc/conor-mcgregor.jpg",
    credit: "Wikimedia Commons · U.S. Secretary of Defense, PD",
  },
  "khabib-nurmagomedov": {
    src: "/cards/ufc/khabib-nurmagomedov.jpg",
    credit: "Wikimedia Commons · Airotcivss, CC BY-SA 4.0",
  },
};
