// Generated by scripts/fetch_card_images.py from scripts/card-images/wwe.json. Do not edit:
// change the manifest and run the script again.

import type { CardImage } from "../types.ts";

export const images: Record<string, CardImage> = {
  "roman-reigns": {
    src: "/cards/wwe/roman-reigns.jpg",
    credit: "Wikimedia Commons · Diego Serrano, CC BY 2.0",
  },
  "john-cena": {
    src: "/cards/wwe/john-cena.jpg",
    credit: "Wikimedia Commons · Gage Skidmore, CC BY-SA 3.0",
  },
  "the-rock": {
    src: "/cards/wwe/the-rock.jpg",
    credit: "Wikimedia Commons · Harald Krichel, CC BY-SA 4.0",
  },
  "the-undertaker": {
    src: "/cards/wwe/the-undertaker.jpg",
    credit: "Wikimedia Commons · Pfc. Hilario Martinez, PD",
  },
};
