// The source allowlist (PLAN §9, stage 1). This is data: it is synced into the Source table at the
// start of every run, and a source switched off there (enabled = false) stays off. Each source is
// tagged with the sections it can feed; the classifier picks one of them per item.
//
// Not fetchable when last checked (2026-09-30), so left out: techbrew.com (403 to every client),
// worldanimalnews.com (403), apnews.com/oddities (403), reuters.com/business (401) and
// bloomberg.com/india (a bot wall; Bloomberg's public technology feed stands in).
import type { SourceDef } from "./types.ts";

export const SOURCES: SourceDef[] = [
  // ——— Good-news desks ———
  {
    slug: "good-news-network",
    name: "Good News Network",
    url: "https://www.goodnewsnetwork.org/feed/",
    type: "rss",
    sections: [
      "internet",
      "discoveries",
      "sports",
      "money",
      "good-humans",
      "your-small-wins",
      "kids-and-schools",
      "animal-kingdom",
      "pets-corner",
      "world-records",
      "planet-wins",
    ],
  },
  {
    slug: "positive-news",
    name: "Positive News",
    url: "https://www.positive.news/feed/",
    type: "rss",
    sections: ["discoveries", "tech", "internet", "planet-wins", "good-humans", "feel-good-health"],
  },
  {
    slug: "reasons-to-be-cheerful",
    name: "Reasons to be Cheerful",
    url: "https://reasonstobecheerful.world/feed/",
    type: "rss",
    sections: [
      "tech",
      "startups",
      "internet",
      "money",
      "planet-wins",
      "good-humans",
      "weird-local",
    ],
  },
  {
    slug: "optimist-daily",
    name: "The Optimist Daily",
    url: "https://www.optimistdaily.com/feed/",
    type: "rss",
    sections: [
      "discoveries",
      "tech",
      "internet",
      "brain-snacks",
      "planet-wins",
      "feel-good-health",
    ],
  },
  {
    slug: "reddit-upliftingnews",
    name: "r/UpliftingNews",
    url: "https://www.reddit.com/r/UpliftingNews/top/.rss?t=day",
    type: "rss",
    sections: [
      "internet",
      "discoveries",
      "sports",
      "good-humans",
      "your-small-wins",
      "kids-and-schools",
    ],
  },

  // ——— Discoveries: space, animals, plants, science ———
  {
    slug: "nasa-apod",
    name: "NASA Astronomy Picture of the Day",
    url: "https://api.nasa.gov/planetary/apod",
    type: "api",
    adapter: "nasa-apod",
    sections: ["discoveries"],
  },
  {
    slug: "spaceflight-news",
    name: "Spaceflight News",
    url: "https://api.spaceflightnewsapi.net/v4/articles/?limit=25",
    type: "api",
    adapter: "spaceflight-news",
    sections: ["discoveries", "tech", "future-stuff"],
  },
  {
    slug: "nasa-news",
    name: "NASA",
    url: "https://www.nasa.gov/news-release/feed/",
    type: "rss",
    sections: ["discoveries"],
  },
  {
    slug: "nasa-image-of-the-day",
    name: "NASA Image of the Day",
    url: "https://www.nasa.gov/feeds/iotd-feed/",
    type: "rss",
    sections: ["discoveries"],
  },
  {
    slug: "esa-space-science",
    name: "ESA",
    url: "https://www.esa.int/rssfeed/Our_Activities/Space_Science",
    type: "rss",
    sections: ["discoveries"],
  },
  {
    slug: "sciencedaily-offbeat",
    name: "ScienceDaily",
    url: "https://www.sciencedaily.com/rss/strange_offbeat.xml",
    type: "rss",
    sections: ["discoveries", "tiny-science", "brain-snacks"],
  },
  {
    slug: "sciencedaily-animals",
    name: "ScienceDaily",
    url: "https://www.sciencedaily.com/rss/plants_animals.xml",
    type: "rss",
    sections: ["discoveries", "animal-kingdom"],
  },
  {
    slug: "phys-org-animals",
    name: "Phys.org",
    url: "https://phys.org/rss-feed/biology-news/plants-animals/",
    type: "rss",
    sections: ["discoveries", "animal-kingdom"],
  },
  {
    slug: "reddit-space",
    name: "r/space",
    url: "https://www.reddit.com/r/space/top/.rss?t=day",
    type: "rss",
    sections: ["discoveries"],
  },

  // ——— Play: games and comics ———
  {
    slug: "nintendo-life",
    name: "Nintendo Life",
    url: "https://www.nintendolife.com/feeds/latest",
    type: "rss",
    sections: ["play", "nostalgia"],
  },
  {
    slug: "rock-paper-shotgun",
    name: "Rock Paper Shotgun",
    url: "https://www.rockpapershotgun.com/feed",
    type: "rss",
    sections: ["play", "nostalgia"],
  },
  {
    slug: "game-developer",
    name: "Game Developer",
    url: "https://www.gamedeveloper.com/rss.xml",
    type: "rss",
    sections: ["play", "tech"],
  },
  {
    slug: "pc-gamer",
    name: "PC Gamer",
    url: "https://www.pcgamer.com/rss/",
    type: "rss",
    sections: ["play"],
  },
  {
    slug: "reddit-indiegaming",
    name: "r/IndieGaming",
    url: "https://www.reddit.com/r/IndieGaming/top/.rss?t=day",
    type: "rss",
    sections: ["play"],
  },

  // ——— Tech: clever things people made ———
  {
    slug: "hackaday",
    name: "Hackaday",
    url: "https://hackaday.com/blog/feed/",
    type: "rss",
    sections: ["tech", "play"],
  },
  {
    slug: "raspberry-pi",
    name: "Raspberry Pi",
    url: "https://www.raspberrypi.com/news/feed/",
    type: "rss",
    sections: ["tech"],
  },
  {
    slug: "adafruit",
    name: "Adafruit",
    url: "https://blog.adafruit.com/feed/",
    type: "rss",
    sections: ["tech"],
  },
  {
    slug: "github-blog",
    name: "The GitHub Blog",
    url: "https://github.blog/feed/",
    type: "rss",
    sections: ["tech"],
  },

  // ——— Screen and Music ———
  {
    slug: "slashfilm",
    name: "/Film",
    url: "https://www.slashfilm.com/feed/",
    type: "rss",
    sections: ["screen"],
  },
  {
    slug: "stereogum",
    name: "Stereogum",
    url: "https://www.stereogum.com/feed/",
    type: "rss",
    sections: ["music"],
  },

  // ——— Sports ———

  // ——— Money (only the fun kind) ———
  {
    slug: "planet-money",
    name: "NPR Planet Money",
    url: "https://feeds.npr.org/510289/podcast.xml",
    type: "rss",
    sections: ["money"],
  },
  {
    slug: "freakonomics",
    name: "Freakonomics",
    url: "https://freakonomics.com/feed/",
    type: "rss",
    sections: ["money", "brain-snacks"],
  },

  // ——— Internet: culture, creators and odd news ———
  {
    slug: "kottke",
    name: "Kottke",
    url: "https://feeds.kottke.org/main",
    type: "rss",
    sections: ["internet", "art-and-design", "brain-snacks"],
  },
  {
    slug: "boing-boing",
    name: "Boing Boing",
    url: "https://boingboing.net/feed",
    type: "rss",
    sections: ["internet", "tech", "weird-local", "nostalgia"],
  },
  {
    slug: "atlas-obscura",
    name: "Atlas Obscura",
    url: "https://www.atlasobscura.com/feeds/latest",
    type: "rss",
    sections: [
      "internet",
      "food-and-drink",
      "time-machine",
      "brain-snacks",
      "postcards",
      "dig-site",
      "homes",
      "weird-jobs",
    ],
  },

  // ——— Guest sections: words, food, history, art and design ———
  {
    slug: "merriam-webster-wotd",
    name: "Merriam-Webster",
    url: "https://www.merriam-webster.com/wotd/feed/rss2",
    type: "rss",
    sections: ["word-nerd"],
  },
  {
    slug: "open-culture",
    name: "Open Culture",
    url: "https://www.openculture.com/feed",
    type: "rss",
    sections: ["art-and-design", "time-machine", "shelf", "nostalgia"],
  },
  {
    slug: "public-domain-review",
    name: "The Public Domain Review",
    url: "https://publicdomainreview.org/rss.xml",
    type: "rss",
    sections: ["time-machine", "art-and-design"],
  },
  {
    slug: "dezeen",
    name: "Dezeen",
    url: "https://www.dezeen.com/feed/",
    type: "rss",
    sections: ["art-and-design", "homes"],
  },
  {
    slug: "wikipedia-on-this-day",
    name: "Wikipedia",
    url: "https://api.wikimedia.org/feed/v1/wikipedia/en/onthisday/selected",
    type: "api",
    adapter: "wikipedia-onthisday",
    sections: ["time-machine"],
  },

  // ——— The owner's allowlist (2026-09): mainstream outlets, one feed or scrape per desk ———
  // The first section listed is the source's home section; the rest are the secondary sections it
  // can be pulled into when a page runs short.

  // Internet & digital culture
  {
    slug: "mashable-digital-culture",
    name: "Mashable",
    url: "https://mashable.com/category/digital-culture",
    type: "api",
    adapter: "scrape",
    linkPattern: "^https://mashable\\.com/life/[a-z0-9-]{12,}$",
    sections: ["internet", "tech", "creators"],
  },
  {
    slug: "vox-internet-culture",
    name: "Vox",
    url: "https://www.vox.com/rss/internet-culture/index.xml",
    type: "rss",
    maxAgeHours: 168,
    sections: ["internet"],
  },
  {
    slug: "huck-internet-culture",
    name: "Huck",
    url: "https://www.huckmag.com/topic/internet-culture/feed",
    type: "rss",
    maxAgeHours: 168,
    sections: ["internet", "art-and-design", "creators"],
  },

  // Tech, startups and business
  {
    slug: "the-verge-tech",
    name: "The Verge",
    url: "https://www.theverge.com/rss/tech/index.xml",
    type: "rss",
    sections: ["tech", "internet"],
  },
  {
    slug: "the-verge",
    name: "The Verge",
    url: "https://www.theverge.com/rss/index.xml",
    type: "rss",
    sections: ["tech", "screen", "play", "music", "internet", "future-stuff"],
  },
  {
    slug: "wired",
    name: "Wired",
    url: "https://www.wired.com/feed/rss",
    type: "rss",
    sections: ["tech", "discoveries", "internet", "future-stuff"],
  },
  {
    slug: "techcrunch",
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    type: "rss",
    sections: ["tech", "startups", "money"],
  },
  {
    slug: "hacker-news",
    name: "Hacker News",
    url: "https://hn.algolia.com/api/v1/search?tags=front_page&numericFilters=points%3E150&hitsPerPage=30",
    type: "api",
    adapter: "hn-algolia",
    sections: ["tech", "startups", "discoveries", "nostalgia"],
  },

  // Space and science
  {
    slug: "space-com",
    name: "Space.com",
    url: "https://www.space.com/news",
    type: "api",
    adapter: "scrape",
    linkPattern:
      "^https://www\\.space\\.com/(astronomy|space-exploration|stargazing|science)/[a-z0-9/-]*[a-z0-9]+(-[a-z0-9]+){4,}$",
    sections: ["discoveries", "tech"],
  },
  {
    slug: "nature-news",
    name: "Nature",
    url: "https://www.nature.com/nature.rss",
    type: "rss",
    // Nature's feed mixes papers and journalism; the news pieces carry the d41586 DOI prefix.
    linkPattern: "/articles/d41586-",
    paywalled: true,
    maxAgeHours: 168,
    sections: ["discoveries"],
  },
  {
    slug: "sciencedaily-top",
    name: "ScienceDaily",
    url: "https://www.sciencedaily.com/rss/top/science.xml",
    type: "rss",
    sections: ["discoveries", "tech"],
  },
  {
    slug: "science-focus",
    name: "BBC Science Focus",
    url: "https://www.sciencefocus.com/news",
    type: "api",
    adapter: "scrape",
    linkPattern: "^https://www\\.sciencefocus\\.com/news/[a-z0-9-]{12,}$",
    maxAgeHours: 168,
    sections: ["discoveries"],
  },
  {
    slug: "phys-org",
    name: "Phys.org",
    url: "https://phys.org/rss-feed/",
    type: "rss",
    sections: ["discoveries", "tech"],
  },

  // Animals and plants
  {
    slug: "nat-geo-animals",
    name: "National Geographic",
    url: "https://www.nationalgeographic.com/animals",
    type: "api",
    adapter: "scrape",
    linkPattern: "^https://www\\.nationalgeographic\\.com/animals/article/[a-z0-9-]{8,}$",
    maxAgeHours: 336,
    sections: ["discoveries"],
  },

  // Food
  {
    slug: "delish-food-news",
    name: "Delish",
    url: "https://www.delish.com/rss/food-news.xml/",
    type: "rss",
    sections: ["food-and-drink", "internet", "money"],
  },
  {
    slug: "food-dive",
    name: "Food Dive",
    url: "https://www.fooddive.com/feeds/news/",
    type: "rss",
    maxAgeHours: 168,
    sections: ["food-and-drink", "money"],
  },

  // Video games
  {
    slug: "vgc",
    name: "Video Games Chronicle",
    url: "https://www.videogameschronicle.com/category/news/feed/",
    type: "rss",
    sections: ["play"],
  },
  {
    slug: "gamespot-news",
    name: "GameSpot",
    url: "https://www.gamespot.com/feeds/news/",
    type: "rss",
    sections: ["play", "screen"],
  },
  {
    slug: "ign-india",
    name: "IGN India",
    url: "https://in.ign.com/feed.xml",
    type: "rss",
    sections: ["play", "screen"],
  },

  // Music
  {
    slug: "billboard-music-news",
    name: "Billboard",
    url: "https://www.billboard.com/c/music/music-news/feed/",
    type: "rss",
    sections: ["music"],
  },
  {
    slug: "rolling-stone-music",
    name: "Rolling Stone",
    url: "https://www.rollingstone.com/music/music-news/feed/",
    type: "rss",
    sections: ["music"],
  },
  {
    slug: "rolling-stone-india",
    name: "Rolling Stone India",
    url: "https://rollingstoneindia.com/feed/",
    type: "rss",
    maxAgeHours: 168,
    sections: ["music", "screen"],
  },

  // Movies and TV
  {
    slug: "den-of-geek",
    name: "Den of Geek",
    url: "https://www.denofgeek.com/feed/",
    type: "rss",
    sections: ["screen", "play"],
  },
  {
    slug: "cbr-anime-news",
    name: "CBR",
    url: "https://www.cbr.com/feed/category/anime-news/",
    type: "rss",
    sections: ["screen"],
  },
  {
    slug: "rolling-stone-tv-movies",
    name: "Rolling Stone",
    url: "https://www.rollingstone.com/tv-movies/tv-movie-news/feed/",
    type: "rss",
    sections: ["screen"],
  },
  {
    slug: "esquire-tv",
    name: "Esquire",
    // Esquire has no TV-only feed; the entertainment feed, narrowed to its TV pages.
    url: "https://www.esquire.com/rss/entertainment.xml/",
    type: "rss",
    linkPattern: "/entertainment/(tv|movies)/",
    sections: ["screen", "music"],
  },

  // Finance and the economy (only the upbeat or curious angles survive the delight check)
  {
    slug: "economist-finance",
    name: "The Economist",
    url: "https://www.economist.com/finance-and-economics/rss.xml",
    type: "rss",
    paywalled: true,
    maxAgeHours: 168,
    perSource: 15,
    sections: ["money"],
  },
  {
    slug: "financial-times",
    name: "Financial Times",
    url: "https://www.ft.com/rss/home",
    type: "rss",
    paywalled: true,
    sections: ["money", "tech"],
  },
  {
    slug: "bloomberg-technology",
    name: "Bloomberg",
    // bloomberg.com/india serves a bot wall; its public feeds still work.
    url: "https://feeds.bloomberg.com/technology/news.rss",
    type: "rss",
    paywalled: true,
    sections: ["money", "tech", "startups"],
  },
  {
    slug: "livemint-money",
    name: "Mint",
    url: "https://www.livemint.com/rss/money",
    type: "rss",
    sections: ["money"],
  },
  {
    slug: "livemint-companies",
    name: "Mint",
    url: "https://www.livemint.com/rss/companies",
    type: "rss",
    sections: ["money", "startups", "tech"],
  },
  {
    slug: "cnbc-economy",
    name: "CNBC",
    url: "https://www.cnbc.com/id/20910258/device/rss/rss.html",
    type: "rss",
    maxAgeHours: 168,
    sections: ["money"],
  },
  {
    slug: "fortune-lifestyle",
    name: "Fortune",
    url: "https://fortune.com/section/lifestyle/",
    type: "api",
    adapter: "scrape",
    linkPattern: "^https://fortune\\.com/(20\\d\\d/\\d\\d/\\d\\d|article)/[a-z0-9-]{12,}/?$",
    sections: ["money", "internet", "food-and-drink", "weird-jobs"],
  },

  // Other and random: comics, oddities, history, art, facts
  {
    slug: "cbr-comics-news",
    name: "CBR",
    url: "https://www.cbr.com/feed/category/comics/news/",
    type: "rss",
    sections: ["play", "screen", "shelf"],
  },
  {
    slug: "history-today",
    name: "History Today",
    url: "https://www.historytoday.com/feed/rss.xml",
    type: "rss",
    maxAgeHours: 336,
    sections: ["time-machine", "dig-site"],
  },
  {
    slug: "smithsonian-smart-news",
    name: "Smithsonian Magazine",
    url: "https://www.smithsonianmag.com/rss/smart-news/",
    type: "rss",
    sections: [
      "discoveries",
      "time-machine",
      "art-and-design",
      "brain-snacks",
      "dig-site",
      "animal-kingdom",
    ],
  },
  {
    slug: "smithsonian-history",
    name: "Smithsonian Magazine",
    url: "https://www.smithsonianmag.com/rss/history/",
    type: "rss",
    maxAgeHours: 168,
    sections: ["time-machine", "dig-site"],
  },
  {
    slug: "artsy-news",
    name: "Artsy",
    url: "https://www.artsy.net/rss/news",
    type: "rss",
    maxAgeHours: 168,
    sections: ["art-and-design"],
  },
  {
    slug: "the-art-newspaper",
    name: "The Art Newspaper",
    url: "https://www.theartnewspaper.com/rss.xml",
    type: "rss",
    sections: ["art-and-design", "time-machine"],
  },
  {
    slug: "colossal",
    name: "Colossal",
    url: "https://www.thisiscolossal.com/feed/",
    type: "rss",
    maxAgeHours: 168,
    sections: ["art-and-design", "internet", "homes"],
  },
  {
    slug: "be-a-great-teacher-fun-fact",
    name: "Be A Great Teacher",
    url: "https://beagreatteacher.com/feed/",
    type: "rss",
    maxAgeHours: 336,
    sections: ["brain-snacks", "time-machine", "myth-busters"],
  },
  {
    slug: "the-fact-site",
    name: "The Fact Site",
    url: "https://www.thefactsite.com/feed/",
    type: "rss",
    // Facts keep: a month-old fact is still a fresh find.
    maxAgeHours: 24 * 45,
    sections: ["brain-snacks", "internet", "time-machine", "myth-busters", "world-records"],
  },
  {
    slug: "onthisday-articles",
    name: "OnThisDay.com",
    url: "https://www.onthisday.com/",
    type: "api",
    adapter: "scrape",
    linkPattern: "^https://www\\.onthisday\\.com/articles/[a-z0-9-]{8,}$",
    maxAgeHours: 24 * 365 * 5,
    sections: ["time-machine"],
  },

  // Sports: football first, then UFC, boxing, tennis, basketball, F1, cricket, running
  {
    slug: "bbc-sport-football",
    name: "BBC Sport",
    url: "https://feeds.bbci.co.uk/sport/football/rss.xml",
    type: "rss",
    perSource: 18,
    sections: ["sports"],
  },
  {
    slug: "sky-sports-football",
    name: "Sky Sports",
    url: "https://www.skysports.com/rss/12040",
    type: "rss",
    sections: ["sports"],
  },
  {
    slug: "espn-soccer",
    name: "ESPN",
    url: "https://www.espn.com/espn/rss/soccer/news",
    type: "rss",
    sections: ["sports"],
  },
  {
    slug: "ufc-news",
    name: "UFC",
    url: "https://www.ufc.com/rss/news",
    type: "rss",
    sections: ["sports"],
  },
  {
    slug: "mma-fighting",
    name: "MMA Fighting",
    url: "https://www.mmafighting.com/rss/index.xml",
    type: "rss",
    sections: ["sports"],
  },
  {
    slug: "sherdog",
    name: "Sherdog",
    url: "https://www.sherdog.com/rss/news.xml",
    type: "rss",
    sections: ["sports"],
  },
  {
    slug: "boxing-scene",
    name: "BoxingScene",
    url: "https://www.boxingscene.com/feed",
    type: "rss",
    browserAgent: true,
    sections: ["sports"],
  },
  {
    slug: "bbc-sport-boxing",
    name: "BBC Sport",
    url: "https://feeds.bbci.co.uk/sport/boxing/rss.xml",
    type: "rss",
    maxAgeHours: 168,
    sections: ["sports"],
  },
  {
    slug: "bbc-sport-tennis",
    name: "BBC Sport",
    url: "https://feeds.bbci.co.uk/sport/tennis/rss.xml",
    type: "rss",
    maxAgeHours: 168,
    sections: ["sports"],
  },
  {
    slug: "espn-tennis",
    name: "ESPN",
    url: "https://www.espn.com/espn/rss/tennis/news",
    type: "rss",
    sections: ["sports"],
  },
  {
    slug: "espn-nba",
    name: "ESPN",
    url: "https://www.espn.com/espn/rss/nba/news",
    type: "rss",
    sections: ["sports"],
  },
  {
    slug: "formula-1",
    name: "Formula 1",
    url: "https://www.formula1.com/en/latest/all.xml",
    type: "rss",
    sections: ["sports"],
  },
  {
    slug: "bbc-sport-f1",
    name: "BBC Sport",
    url: "https://feeds.bbci.co.uk/sport/formula1/rss.xml",
    type: "rss",
    sections: ["sports"],
  },
  {
    slug: "espncricinfo",
    name: "ESPNcricinfo",
    url: "https://www.espncricinfo.com/rss/content/story/feeds/0.xml",
    type: "rss",
    sections: ["sports"],
  },
  {
    slug: "runners-world",
    name: "Runner's World",
    url: "https://www.runnersworld.com/rss/all.xml/",
    type: "rss",
    sections: ["sports"],
  },
  {
    slug: "irunfar",
    name: "iRunFar",
    url: "https://www.irunfar.com/feed",
    type: "rss",
    maxAgeHours: 168,
    sections: ["sports"],
  },
  // ——— Startups: launches, funding, founders (2026-10) ———
  {
    slug: "techcrunch-startups",
    name: "TechCrunch",
    url: "https://techcrunch.com/category/startups/feed/",
    type: "rss",
    sections: ["startups", "tech"],
  },
  {
    slug: "inc42",
    name: "Inc42",
    url: "https://inc42.com/feed/",
    type: "rss",
    sections: ["startups", "money"],
  },
  {
    slug: "yourstory",
    name: "YourStory",
    url: "https://yourstory.com/feed",
    type: "rss",
    sections: ["startups", "money"],
  },
  {
    slug: "crunchbase-news",
    name: "Crunchbase News",
    url: "https://news.crunchbase.com/feed/",
    type: "rss",
    sections: ["startups", "money"],
  },
  {
    slug: "sifted",
    name: "Sifted",
    url: "https://sifted.eu/feed",
    type: "rss",
    sections: ["startups"],
  },
  {
    slug: "hacker-news-show",
    name: "Hacker News",
    url: "https://hn.algolia.com/api/v1/search?tags=show_hn&numericFilters=points%3E80&hitsPerPage=30",
    type: "api",
    adapter: "hn-algolia",
    sections: ["startups", "tech"],
  },
  {
    slug: "product-hunt",
    name: "Product Hunt",
    url: "https://www.producthunt.com/feed",
    type: "rss",
    sections: ["startups", "tech"],
  },

  // ——— Music: albums, gigs, festivals, artists (2026-10) ———
  {
    slug: "pitchfork-news",
    name: "Pitchfork",
    url: "https://pitchfork.com/feed/feed-news/rss",
    type: "rss",
    sections: ["music"],
  },
  {
    slug: "nme-music",
    name: "NME",
    url: "https://www.nme.com/news/music/feed",
    type: "rss",
    sections: ["music"],
  },
  {
    slug: "consequence-music",
    name: "Consequence",
    url: "https://consequence.net/category/music/feed/",
    type: "rss",
    sections: ["music"],
  },

  // ——— Brain Snacks: fun facts, general knowledge, social science (2026-10) ———
  {
    slug: "mental-floss",
    name: "Mental Floss",
    url: "https://www.mentalfloss.com/rss.xml",
    type: "rss",
    sections: ["brain-snacks", "time-machine", "word-nerd", "myth-busters"],
    browserAgent: true,
  },
  {
    slug: "psypost",
    name: "PsyPost",
    url: "https://www.psypost.org/feed/",
    type: "rss",
    sections: ["tiny-science", "brain-snacks", "feel-good-health"],
  },

  // ——— Guest sections (2026-10): one or more verified feeds per guest ———
  {
    slug: "hypebeast",
    name: "Hypebeast",
    url: "https://hypebeast.com/feed",
    type: "rss",
    sections: ["drops", "art-and-design"],
  },
  {
    slug: "sneaker-news",
    name: "Sneaker News",
    url: "https://sneakernews.com/feed/",
    type: "rss",
    sections: ["drops"],
  },
  {
    slug: "highsnobiety",
    name: "Highsnobiety",
    url: "https://www.highsnobiety.com/feed/",
    type: "rss",
    sections: ["drops", "art-and-design"],
  },
  {
    slug: "the-better-india",
    name: "The Better India",
    url: "https://thebetterindia.com/feed/",
    type: "rss",
    sections: ["india-desk", "good-humans", "planet-wins", "kids-and-schools"],
  },
  {
    slug: "grist",
    name: "Grist",
    url: "https://grist.org/feed/",
    type: "rss",
    sections: ["planet-wins"],
  },
  {
    slug: "anthropocene",
    name: "Anthropocene",
    url: "https://www.anthropocenemagazine.org/feed/",
    type: "rss",
    sections: ["planet-wins", "tiny-science"],
  },
  {
    slug: "book-riot",
    name: "Book Riot",
    url: "https://bookriot.com/feed/",
    type: "rss",
    sections: ["shelf"],
  },
  {
    slug: "publishers-weekly",
    name: "Publishers Weekly",
    url: "https://www.publishersweekly.com/pw/feeds/recent/index.xml",
    type: "rss",
    sections: ["shelf"],
  },
  {
    slug: "live-science",
    name: "Live Science",
    url: "https://www.livescience.com/feeds/all",
    type: "rss",
    sections: ["myth-busters", "tiny-science", "dig-site", "discoveries"],
  },
  {
    slug: "ancient-origins",
    name: "Ancient Origins",
    url: "https://www.ancient-origins.net/rss.xml",
    type: "rss",
    sections: ["dig-site", "time-machine"],
  },
  {
    slug: "heritage-daily",
    name: "HeritageDaily",
    url: "https://www.heritagedaily.com/category/archaeology/feed",
    type: "rss",
    sections: ["dig-site"],
  },
  {
    slug: "time-extension",
    name: "Time Extension",
    url: "https://www.timeextension.com/feeds/latest",
    type: "rss",
    sections: ["nostalgia", "play"],
  },
  {
    slug: "new-atlas",
    name: "New Atlas",
    url: "https://newatlas.com/index.rss",
    type: "rss",
    sections: ["future-stuff", "wheels", "homes", "tech"],
  },
  {
    slug: "carscoops",
    name: "Carscoops",
    url: "https://www.carscoops.com/feed/",
    type: "rss",
    sections: ["wheels"],
  },
  {
    slug: "electrek",
    name: "Electrek",
    url: "https://electrek.co/feed/",
    type: "rss",
    sections: ["wheels", "planet-wins"],
  },
  {
    slug: "tubefilter",
    name: "Tubefilter",
    url: "https://www.tubefilter.com/feed/",
    type: "rss",
    sections: ["creators", "internet"],
  },
  {
    slug: "upi-odd-news",
    name: "UPI",
    url: "https://rss.upi.com/news/odd_news.rss",
    type: "rss",
    sections: ["world-records", "weird-local", "weird-jobs", "internet"],
  },
  {
    slug: "designboom",
    name: "designboom",
    url: "https://www.designboom.com/feed/",
    type: "rss",
    sections: ["homes", "art-and-design", "wheels"],
  },
  {
    slug: "sciencedaily-mind-brain",
    name: "ScienceDaily",
    url: "https://www.sciencedaily.com/rss/mind_brain.xml",
    type: "rss",
    sections: ["feel-good-health", "tiny-science"],
  },
  {
    slug: "sciencealert",
    name: "ScienceAlert",
    url: "https://www.sciencealert.com/feed",
    type: "rss",
    sections: ["tiny-science", "myth-busters", "discoveries"],
  },
  {
    slug: "bored-panda",
    name: "Bored Panda",
    url: "https://www.boredpanda.com/feed/",
    type: "rss",
    sections: ["pets-corner", "internet", "homes", "weird-jobs"],
  },
  {
    slug: "cn-traveler",
    name: "Condé Nast Traveler",
    url: "https://www.cntraveler.com/feed/rss",
    type: "rss",
    sections: ["postcards", "food-and-drink"],
  },
  {
    slug: "gnn-animals",
    name: "Good News Network",
    url: "https://www.goodnewsnetwork.org/category/news/animals/feed/",
    type: "rss",
    sections: ["animal-kingdom", "pets-corner"],
  },
  {
    slug: "gnn-inspiring",
    name: "Good News Network",
    url: "https://www.goodnewsnetwork.org/category/news/inspiring/feed/",
    type: "rss",
    sections: ["good-humans", "kids-and-schools", "your-small-wins", "weird-jobs"],
  },
];
