/** Fortune-teller fortunes: short, warm, funny, and always good news. */
export const FORTUNES: readonly string[] = [
  "A stranger will compliment your shoes before lunch.",
  "A pigeon will nod at you respectfully.",
  "You will find a crisp you forgot you had.",
  "Your toast will land butter side up.",
  "The next song on the radio will be one you love.",
  "A dog will choose you as its favourite person today.",
  "Your tea will be exactly the right temperature.",
  "Both of your socks will match. Mostly.",
  "Somebody will laugh at your joke, and mean it.",
  "The sun will come out just as you step outside.",
  "Your train will arrive on time and there will be a seat.",
  "A cat will blink slowly at you. That's a cat hug.",
  "Today your hair will behave beautifully.",
  "An old friend is about to think of you fondly.",
  "Somewhere, a biscuit has your name on it.",
  "The last slice of cake will be yours.",
  "A robin will keep you company in the garden.",
  "Every traffic light will turn green for you.",
  "You will remember a word that was on the tip of your tongue.",
  "A baby will wave at you from a pushchair.",
  "Your pen will not run out when it matters.",
  "Tonight's sleep will be the cosy kind.",
  "A rainbow is on its way. Keep an eye out.",
  "Someone will hold a door open for you.",
  "Your plant has secretly grown a new leaf.",
  "The queue will move faster than you expected.",
  "An excellent idea will arrive in the shower.",
  "A forgotten sweet will turn up in an old coat pocket.",
  "Your houseplant is proud of you.",
  "A ladybird may land on your sleeve for good luck.",
  "The kettle will boil the moment you need it.",
  "Lunch will be even tastier than you hoped.",
  "Someone will save you the comfy chair.",
  "A duck will quack at you in a friendly manner.",
  "Your favourite mug will be clean and waiting.",
  "The bus driver will wave you on with a smile.",
  "An unexpected parcel of joy is heading your way.",
  "You will laugh so hard you snort. Worth it.",
  "A squirrel will perform a small acrobatic show for you.",
  "Your umbrella will be exactly where you left it.",
  "The weather will be kinder than the forecast said.",
  "Today you will spot a dog wearing a jumper.",
  "Your next cup of tea will taste like a hug.",
  "Somebody nearby is about to hum your favourite tune.",
  "Your shoelaces will stay tied all day.",
  "A cloud shaped like a rabbit will float by.",
  "You will get the good trolley at the supermarket.",
  "The toaster will pop at the perfect moment.",
  "A child will tell you a wonderfully weird fact.",
  "Your jokes will land especially well this afternoon.",
  "Look up tonight: a star is winking at you.",
  "Your bike will have air in both tyres.",
  "A neighbour will give you a cheerful wave.",
  "Your phone will be charged when you need it most.",
  "Someone will say thank you and really mean it.",
  "Soup is in your near future. Lovely, warm soup.",
  "The biscuit will not break when you dunk it.",
  "A blackbird will sing just for you at dusk.",
  "Your socks will be warm from the radiator.",
  "You will make someone smile without even trying.",
  "Your garden will surprise you with a flower.",
  "A friend will send you a very silly photo.",
  "The lift will arrive the moment you press the button.",
  "Your packed lunch will be better than you remember packing.",
  "Your teacher will be in an excellent mood.",
  "The answer will come to you right before the question.",
  "A bee will visit your windowsill and leave politely.",
  "Your favourite jumper is fresh out of the wash.",
  "A goose will honk at you in approval.",
  "Your spelling will be flawless all day.",
  "The crossword clue that stumped you will suddenly click.",
  "Someone will offer you the last chip.",
  "Your cat will choose your lap over the keyboard.",
  "A butterfly is planning to cross your path.",
  "Today's puddles will all be small enough to jump.",
  "The film you pick tonight will be a corker.",
  "A snail will make excellent progress on your behalf.",
  "The cafe will have your favourite cake in.",
  "Your umbrella will not turn inside out.",
  "You will hear a really good laugh from across the street.",
  "Clean sheets are in your future. Bliss.",
  "Someone will remember exactly how you take your tea.",
  "A lovely smell of baking will drift your way.",
  "Your dog will do the trick when people are watching.",
  "Expect a pleasantly short queue at the post office.",
  "The first strawberry you eat will be the sweetest.",
  "Your fringe will fall just right.",
  "A small child will call you a superhero.",
  "The pigeons will leave your chips alone.",
  "An autumn leaf will land perfectly in your hand.",
  "Your wobbly table leg will stop wobbling.",
  "The train window seat is yours today.",
  "A cow in a field will look at you thoughtfully.",
  "Your favourite song will play in the shop.",
  "You will step on a very satisfying crunchy leaf.",
  "Someone will lend you exactly the pen you needed.",
  "The sun will warm your face at just the right moment.",
  "A frog will say hello from the pond.",
  "Your homework will be easier than it looks.",
  "Somebody will tell you that you look well rested.",
  "You will find the end of the sticky tape first time.",
  "A tiny dog will bark at you with great enthusiasm.",
  "Your crumpet will have exactly the right number of holes.",
  "Your wifi will be strong and true.",
  "The car park will have a space right by the door.",
  "A good book will find you this week.",
  "Your cup of cocoa will come with extra marshmallows.",
  "A snowflake-sized bit of kindness will land on you.",
  "Your favourite pen will turn up in a coat pocket.",
  "The bread will be perfectly fresh when you slice it.",
  "Someone will pick you first for their team.",
  "A seagull will politely ignore your sandwich.",
  "Your paper aeroplane will fly further than ever.",
  "Everyone will sing happy birthday in tune.",
  "The fruit bowl will have one perfectly ripe banana.",
  "Your train will have a quiet carriage and it will be quiet.",
  "Your meeting will finish five minutes early.",
  "A colleague will bring in doughnuts.",
  "Your inbox will be pleasantly quiet.",
  "A hedgehog will pass through your garden tonight.",
  "Your pencil will stay sharp until the very end.",
  "Today the washing will dry before the rain.",
  "An owl will hoot goodnight to you.",
  "A friendly horse will let you pat its nose.",
  "You will hear the ice cream van's tune and smile.",
  "Your favourite podcast has a new episode.",
  "Your peas will all stay on your fork.",
  "Someone will give you a genuinely useful tip.",
  "The tomatoes on your plant are about to go red.",
  "Your gloves will still be a pair by spring.",
  "A cheerful postcard is on its way to someone like you.",
  "Your dance moves will be admired, possibly by a cat.",
  "The best seat on the sofa will be free.",
  "A long-lost sock will return from the washing machine.",
  "Pancakes will flip perfectly this week.",
  "The shop will have exactly one left, and it's yours.",
  "A fox will trot past and give you a cool look.",
  "Your picnic will be wasp-free.",
  "Today your bin goes out on the right day.",
  "A stranger will ask you for directions and you'll know the way.",
  "You will sneak a perfect nap into the afternoon.",
  "Your tennis ball will clear the net every time.",
  "The swings in the park will be free.",
  "Someone will draw you a picture. Treasure it.",
  "Your baked potato will be fluffy all the way through.",
  "A gentle breeze will arrive exactly when you need it.",
  "Your library book will be the page-turning kind.",
  "The ducks will come straight to you at the pond.",
  "Your jar will open on the first twist.",
  "A tiny spider will build a web and it will be beautiful.",
  "Good news will arrive in a small envelope.",
  "Your pizza will have the perfect cheese pull.",
  "You will whistle a tune and get it right.",
  "The bath will be the perfect temperature first time.",
  "Your bus will come just as you reach the stop.",
  "Someone will notice your excellent hat.",
  "Your stew will taste even better tomorrow.",
  "A dog in a car window will look delighted to see you.",
  "Your mum will laugh at your joke. Well done.",
  "The moon will look especially big tonight.",
  "A friend will share their chips without being asked.",
  "Your wellies will keep your feet perfectly dry.",
  "Your sandcastle will survive the tide.",
  "The best autumn conker will be lying at your feet.",
  "A robin will perch on your spade.",
  "Your scarf will be exactly cosy enough.",
  "This evening you will find the TV remote on the first try.",
  "An excellent pun will occur to you at the right moment.",
  "Your recorder will play every note in tune.",
  "The fish in the pond will come up to say hello.",
  "Your seeds will sprout sooner than expected.",
  "Somebody will pass you the salt before you ask.",
  "Your tent will go up without a single argument.",
  "A kind message will brighten your evening.",
  "The last train home will be warm and on time.",
  "Your beans on toast will be absolutely perfect.",
  "A horse chestnut tree will drop a shiny gift.",
  "Tomorrow morning the birds will sing you awake.",
  "Your jigsaw will have all its pieces.",
  "Your knees will feel springy on the stairs.",
  "Someone will ask how you are and wait for the answer.",
  "The rain will stop just before you leave.",
  "A new favourite biscuit is about to enter your life.",
  "Your apple will be crisp, not floury.",
  "A friendly wave will come from a passing tractor.",
  "Your balloon will stay up for days.",
  "The sticker will peel off in one go.",
  "Your gravy will have no lumps.",
  "A kind driver will let you out at the junction.",
  "Your fringe trim will turn out brilliantly.",
  "The best chocolate in the box will be the one you pick.",
  "A small dog will fall asleep on your feet.",
  "Your plan for the weekend will come together nicely.",
  "Your brolly will be needed and you'll have it.",
  "The new pen you try will write beautifully.",
  "Someone will want to hear about your hobby.",
  "Your custard will be skin-free.",
  "A heron will stand very still for your photo.",
  "The playground will be all yours for five minutes.",
  "Your teacup will not leave a ring on the table.",
  "A giggle will ambush you in a quiet room.",
  "Your packed bag will have everything you need.",
  "The first cup of tea of the day will be a good one.",
  "Your kite will catch the wind first time.",
  "A dragonfly will hover near you like a tiny helicopter.",
  "Nobody will take your spot on the train.",
  "Your morning porridge will be just right.",
  "Your fairy lights will untangle easily.",
  "A pal will save you a seat.",
  "The daisies on the lawn will all turn to face you.",
  "Your bread will rise beautifully.",
  "Someone will say your name in a very happy voice.",
  "Your little brother or sister will share their sweets.",
  "A cat on a wall will allow you to stroke it.",
  "The sea will be warmer than you expect.",
  "Your ice lolly won't drip down your arm.",
  "An extra chip is hiding at the bottom of the bag.",
  "Your birdfeeder will be busy today.",
  "Your fingers will be warm all day.",
  "An elderly neighbour will tell you a brilliant story.",
  "The shoe that pinched will suddenly fit perfectly.",
  "Your cat will bring you a leaf. It's a gift.",
  "Hot chocolate is strongly indicated.",
  "Your song choice will get everyone dancing.",
  "Your favourite colour will turn up everywhere today.",
  "A tiny moment of peace will find you after lunch.",
  "Your bus will have the cosy seat above the heater.",
  "The chocolate biscuits will be at the top of the tin.",
  "Your new trainers will feel like clouds.",
  "Somebody will make you a cup of tea without asking.",
  "The sunset tonight will be worth stopping for.",
  "Your first bite of toast will be the perfect crunch.",
  "A pal will remember your favourite film.",
  "Your wonky shelf will turn out to be perfectly level.",
  "The school dinner will be the good one.",
  "Your painting will dry without a single smudge.",
  "A cheerful whistle will float down your street.",
  "Your runner beans will climb higher than ever.",
  "An hour will feel like two in the nicest way.",
  "Your umbrella and the rain will never meet today.",
  "Your spaghetti will not splash your shirt.",
  "A dog will bring you its ball. Throw it.",
  "Your rice will be fluffy, not sticky.",
  "The tree outside your window is quietly waving.",
  "Your laugh will make someone else laugh.",
  "The vending machine will drop two by mistake.",
  "A lovely, lazy morning is in your future.",
  "Your origami crane will fold perfectly.",
  "Somebody will be very glad you came.",
  "A happy surprise is hiding in the next fortnight.",
  "Your timing will be impeccable all afternoon.",
  "The postman will bring something nice for once.",
  "A family of ducklings will cross your path.",
  "Your grandparents will tell you that you've grown.",
  "The cushion will be exactly where your head wants it.",
  "Your boiled egg will be perfectly dippy.",
  "Warm socks are in your immediate future.",
  "Your bouncy ball will bounce higher than the shed.",
  "Your pet will do something so funny you'll tell everyone.",
  "A passing jogger will give you a cheery thumbs up.",
  "Your walk home will be full of good smells.",
  "Someone will cheer you on today, even quietly.",
  "Your kindness will come back to you by Friday.",
  "An impressive snowman is in your future.",
  "Your cress will grow a fine green moustache.",
  "The bees will love your lavender.",
  "Your carriage will be the one that stops by the exit.",
  "The back of the fridge holds a pleasant surprise: cheese.",
  "A quiet cup of tea will turn into a great chat.",
  "The best leaf pile in town will be yours to jump in.",
];

/** Colour words for the fortune teller's outer flaps (spelled out one fold per letter). */
export const COLOURS: readonly string[] = [
  "RED",
  "TANGERINE",
  "BLUE",
  "TEAL",
  "LILAC",
  "CORAL",
  "MANGO",
  "LEMON",
  "LIME",
  "MINT",
  "PEACH",
  "PLUM",
  "ROSE",
  "GOLD",
  "AMBER",
  "INDIGO",
  "VIOLET",
  "SCARLET",
  "CRIMSON",
  "CHERRY",
  "OCHRE",
  "MUSTARD",
  "SAGE",
  "OLIVE",
  "JADE",
  "EMERALD",
  "COBALT",
  "NAVY",
  "AQUA",
  "CYAN",
  "MAGENTA",
  "FUCHSIA",
  "PINK",
  "SAFFRON",
  "APRICOT",
  "HONEY",
  "CARAMEL",
  "CREAM",
  "SILVER",
  "COPPER",
  "LAVENDER",
  "PISTACHIO",
  "TURQUOISE",
  "BUTTER",
  "ORANGE",
  "GREEN",
  "YELLOW",
  "PURPLE",
  "RUBY",
  "SAPPHIRE",
];
