import type { Riddle } from "./types.ts";

/** The riddle bank: one a day, no repeats for as long as the bank lasts. */
export const RIDDLES: readonly Riddle[] = [
  ["What has hands but can't clap?", "A clock"],
  ["What has keys but can't open a single lock?", "A piano"],
  ["What gets wetter the more it dries?", "A towel"],
  ["The more you take, the more you leave behind. What are they?", "Footsteps"],
  ["What has a neck but no head, and wears a cap?", "A bottle"],
  [
    "I speak without a mouth and hear without ears. I come alive in caves and valleys. What am I?",
    "An echo",
  ],
  ["What has an eye but cannot see, and is always threaded?", "A needle"],
  ["What goes up every birthday but never comes down?", "Your age"],
  ["What has lots of teeth but never bites?", "A comb"],
  ["What can travel all around the world while staying in one corner?", "A stamp"],
  ["What has one head, one foot and four legs?", "A bed"],
  [
    "What runs but never walks, has a mouth but never talks, and has a bed but never sleeps?",
    "A river",
  ],
  ["What has a thumb and four fingers but isn't alive?", "A glove"],
  ["What is full of holes but still holds water?", "A sponge"],
  ["What gets bigger the more you take away from it?", "A hole"],
  ["What belongs to you, but other people use it far more than you do?", "Your name"],
  ["What can you keep after you've given it to someone?", "Your word"],
  ["What has a ring but no finger?", "A telephone"],
  ["Which building has the most stories?", "A library"],
  ["What has four wheels and flies?", "A rubbish lorry"],
  ["What kind of room has no doors or windows?", "A mushroom"],
  ["What has a bark but no bite?", "A tree"],
  ["What starts with T, ends with T, and has T in it?", "A teapot"],
  ["Some months have 30 days, some have 31. How many have 28?", "All of them"],
  ["What comes down but never goes up?", "Rain"],
  ["What has a head and a tail but no body?", "A coin"],
  ["What can fill a whole room but takes up no space?", "Light"],
  ["What has four legs but never walks anywhere?", "A table"],
  ["What is always in front of you but can never be seen?", "The future"],
  ["What has cities but no houses, forests but no trees, and water but no fish?", "A map"],
  ["What word is spelled incorrectly in every dictionary?", "Incorrectly"],
  ["What goes through towns and over hills but never moves?", "A road"],
  ["What gets sharper the more you use it?", "Your brain"],
  ["What can you hold in your right hand but never in your left?", "Your left elbow"],
  ["What is so fragile that saying its name breaks it?", "Silence"],
  ["What goes up and down all day but never moves?", "A staircase"],
  ["Forwards I am heavy, backwards I am not. What am I?", "A ton"],
  ["What is black when it's clean and white when it's dirty?", "A blackboard"],
  ["What has a spine but no bones?", "A book"],
  ["What has thirteen hearts but no other organs?", "A pack of cards"],
  ["What kind of band never plays any music?", "A rubber band"],
  ["What invention lets you look right through a wall?", "A window"],
  [
    "If you drop me I'm sure to crack, but smile at me and I'll always smile back. What am I?",
    "A mirror",
  ],
  ["I'm tall when I'm young and short when I'm old. What am I?", "A candle"],
  ["What has a tongue but can't taste, and goes everywhere you go?", "A shoe"],
  [
    "What comes once in a minute, twice in a moment, but never in a thousand years?",
    "The letter M",
  ],
  ["What starts with P, ends with E and has thousands of letters?", "A post office"],
  ["What can you serve but never eat?", "A tennis ball"],
  ["What goes all the way around the garden but never moves?", "A fence"],
  ["What do you call a bear with no teeth?", "A gummy bear"],
  ["Where does today come before yesterday?", "In a dictionary"],
  ["What can you make that nobody can see?", "A noise"],
  ["What is always coming but never arrives?", "Tomorrow"],
  ["What gets answered but never asks a question?", "A doorbell"],
  ["What has a heart that never beats, and leaves you can eat?", "An artichoke"],
  ["What is orange and sounds like a parrot?", "A carrot"],
  ["What loses its head in the morning and gets it back at night?", "A pillow"],
  ["What kind of tree fits in your hand?", "A palm"],
  ["What has ears but can't hear, and grows in tall green rows?", "Corn"],
  ["What kind of coat is best put on wet?", "A coat of paint"],
  ["What word becomes shorter when you add two letters to it?", "Short"],
  ["What starts with E, ends with E, and usually contains only one letter?", "An envelope"],
  ["What has lots of eyes but can't see a thing?", "A potato"],
  ["What goes up when the rain comes down?", "An umbrella"],
  ["What kind of cup can't hold any tea?", "A cupcake"],
  ["What is taller than a tree, has roots nobody sees, and never grows?", "A mountain"],
  ["What is always at the end of a rainbow?", "The letter W"],
  ["Which letter of the alphabet holds the most water?", "The letter C"],
  ["Which letter of the alphabet is a small green vegetable?", "The letter P"],
  ["Which letter of the alphabet goes best with biscuits?", "The letter T"],
  ["What question can you never truthfully answer with 'yes'?", "Are you asleep?"],
  ["What is harder to catch the faster you run?", "Your breath"],
  ["What falls all winter but never gets hurt?", "Snow"],
  ["What flies when you're having fun?", "Time"],
  ["What has a neck but no head, and two arms but no hands?", "A shirt"],
  ["What kind of key opens a banana?", "A monkey"],
  ["What whistles in the kitchen without any lips?", "A kettle"],
  ["What has lots of buttons, lives on the sofa, and always goes missing?", "A remote control"],
  ["What has a trunk but never packs for holidays?", "An elephant"],
  [
    "What has hundreds of needles but can't sew, and snuffles round the garden at night?",
    "A hedgehog",
  ],
  ["What has to be broken before you can use it?", "An egg"],
  ["What has four eyes but can't see?", "Mississippi"],
  ["What sort of stones are never found in the sea?", "Dry ones"],
  ["What do you call a sleeping dinosaur?", "A dino-snore"],
  [
    "What wears a crown but has never been royal, and is spiky outside and sweet inside?",
    "A pineapple",
  ],
  ["I rise every morning in the east and set every evening in the west. What am I?", "The sun"],
  ["What is bought by the metre and worn by the foot?", "A carpet"],
  [
    "What has keys but no locks, space but no room, and lets you enter but never go inside?",
    "A keyboard",
  ],
  ["What has a long tail and flies without wings, but only when you hold on?", "A kite"],
  ["What do you throw away when you want to use it, and pull back when you're done?", "An anchor"],
  ["What does a cat have that no other animal has?", "Kittens"],
  ["What can be cracked, made, told and played?", "A joke"],
  ["What must be taken before you can get it?", "Your picture"],
  ["What's black and white and read all over?", "A newspaper"],
  ["What goes round and round the wood but never goes into it?", "Bark"],
  ["What has a pupil but has never been to school?", "Your eye"],
  ["What always comes at the end of everything?", "The letter G"],
  ["What flies all day and never goes anywhere?", "A flag"],
  ["What can you hear but not see or touch, even though you control it?", "Your voice"],
  ["What is it that you'll never, ever see again?", "Yesterday"],
  ["What is right in the middle of Paris?", "The letter R"],
  ["What is too much for one, just right for two, and nothing at all for three?", "A secret"],
  ["What grows bigger the more you give it away?", "A smile"],
  ["What wears a coat all winter and pants all summer?", "A dog"],
  ["What kind of shoes can you make out of banana skins?", "Slippers"],
  ["What has two legs but can't walk on its own?", "A pair of trousers"],
  ["What has a bow but no arrows, and is best when it's unwrapped?", "A present"],
  ["What do you call a fish with no eyes?", "A fsh"],
  ["What goes 'zzub zzub'?", "A bee flying backwards"],
  ["What has a bill but never pays it?", "A duck"],
  ["What has a point, spins all day, and falls over when it's tired?", "A spinning top"],
  ["What do you call a snowman in July?", "A puddle"],
  ["What has sharp teeth but never eats, and loves a good plank?", "A saw"],
  ["In which month do people sleep the least?", "February"],
  ["What never gets any wetter, no matter how much it rains on it?", "The sea"],
  ["What do you call a deer with no eyes?", "No idea"],
  ["What has four legs and a back but no body?", "A chair"],
  ["What goes all the way around the world but never leaves its place?", "The equator"],
  ["What kind of dog always knows the time?", "A watchdog"],
  ["Which is heavier: a tonne of feathers or a tonne of bricks?", "Neither"],
  ["How many letters are there in 'the alphabet'?", "Eleven"],
  ["What kind of music are balloons afraid of?", "Pop music"],
  ["What do you get if you cross a sheep with a kangaroo?", "A woolly jumper"],
  ["What kind of bow can never be tied?", "A rainbow"],
  ["What stays hot even in the fridge?", "Mustard"],
  ["What's brown and sticky?", "A stick"],
  ["What gets smaller every time it has a bath?", "A bar of soap"],
  ["Why did the bicycle fall over?", "It was two tired"],
  ["What has a cap and ink but no head?", "A pen"],
  ["What has lead in its middle and gets shorter the harder it works?", "A pencil"],
  ["What is full of memories but owns nothing at all?", "A photo album"],
  ["What has lots of leaves but never drops them in autumn, and ends up in a salad?", "A lettuce"],
  ["What has scales but can't weigh itself, and no legs to stand on?", "A snake"],
  ["What can jump higher than a house?", "Anything"],
  ["What kind of ant is enormous?", "A gi-ant"],
  ["Which number is odd until you take away its first letter?", "Seven"],
  ["What do you call a dog that does magic tricks?", "A labracadabrador"],
  ["What do snowmen eat for lunch?", "Iceburgers"],
  ["What has three feet but can't walk?", "A yardstick"],
  ["What do you call a train loaded with toffee?", "A chew-chew train"],
  ["What is round and sweet with a hole in the middle?", "A doughnut"],
  ["What kind of lion never roars?", "A dandelion"],
  ["What tastes better than it smells?", "Your tongue"],
  ["What's the best thing to put into a pie?", "Your teeth"],
  ["What goes round and round all summer and keeps you cool?", "A fan"],
  ["What has twenty-one spots but isn't a leopard?", "A dice"],
  [
    "What's in seasons, seconds, centuries and minutes, but not in decades, years or days?",
    "The letter N",
  ],
  ["What comes once in a year, twice in a week, but never in a day?", "The letter E"],
  ["What part of a bird is never in the sky, can swim in the sea and stay dry?", "Its shadow"],
  ["What do you call a sleepy bull?", "A bulldozer"],
  ["What did the sea say to the shore?", "Nothing, it just waved"],
  ["What is the longest word in the English language?", "Smiles"],
  ["What moves without legs and always carries its house?", "A snail"],
  ["What is a cat's favourite colour?", "Purr-ple"],
  ["What goes in dry, comes out wet, and makes a lovely brew?", "A teabag"],
  ["Where do cows go on a night out?", "The moo-vies"],
  ["What do you call a dinosaur with an enormous vocabulary?", "A thesaurus"],
  ["What did one plate say to the other plate?", "Lunch is on me"],
  ["What has no beginning, no end and no middle?", "A circle"],
  ["What kind of water can never freeze?", "Hot water"],
  [
    "What has a head like a cat, feet like a cat and a tail like a cat, but isn't a cat?",
    "A kitten",
  ],
  ["What meal can you never eat for breakfast?", "Lunch"],
  ["Who is bigger: Mr Bigger, or Mr Bigger's baby?", "The baby"],
  ["What has no hands but might knock on your door one day?", "Opportunity"],
  ["What has bristles, visits twice a day, and makes you grin?", "A toothbrush"],
  ["What has one eye, sits on a tripod, and asks everyone to say cheese?", "A camera"],
  ["What sweeps the floor without any arms, then leans in the corner all day?", "A broom"],
  ["What starts life as a caterpillar and ends up with painted wings?", "A butterfly"],
  ["What has strings but isn't a puppet, and makes music when you strum it?", "A guitar"],
  ["What is bright yellow, hangs in bunches and is never straight?", "A banana"],
  ["What has a face that changes every night but never looks in a mirror?", "The moon"],
  ["What spreads round a room faster than news, but can't be seen?", "Laughter"],
];
