import type { Clued } from "./types.ts";

/** Five-letter crossword answers, each with one or more clues. */
export const FIVE_LETTER_WORDS: readonly Clued[] = [
  // A
  ["APPLE", "Crunchy fruit, one a day keeps the doctor away", "Big ___ (New York's nickname)"],
  ["ACORN", "Tiny seed with big oak-tree dreams", "Squirrel's favourite snack"],
  ["ADORE", "Love to bits", "Think the world of"],
  ["AGREE", "See eye to eye", "Nod along happily"],
  ["ALARM", "Clock's wake-up call", "Morning bell you might snooze"],
  ["ALBUM", "Book of holiday snaps", "Collection of songs on a record"],
  ["ALERT", "Wide awake and watchful", "Bright-eyed and on the ball"],
  ["AMAZE", "Wow completely", "Leave open-mouthed with wonder"],
  ["AMBER", "Honey-coloured gem", "Middle traffic light"],
  ["ANGLE", "What a protractor measures", "Point of view"],
  ["ANKLE", "Joint just above the foot", "Where a sock often stops"],
  ["APRON", "Cook's cover-up", "Baker's pinny"],
  ["ARENA", "Big venue for concerts and games", "Stadium stage"],
  ["AROMA", "Smell of fresh coffee, say", "Lovely whiff from the oven"],
  ["ASIDE", "Stage whisper to the audience", "Off to one side"],
  ["AWAKE", "Up and about", "Not asleep"],
  ["AWARD", "Trophy or medal", "Prize for a job well done"],
  ["AWARE", "In the know", "Mindful"],
  ["ATTIC", "Room under the roof", "Where old treasures gather dust"],
  ["ADOPT", "Give a rescue pup a home", "Take on as your own"],
  ["AISLE", "Walkway between shop shelves", "Seat choice that isn't the window"],
  ["ALIKE", "Like two peas in a pod", "Very similar"],
  ["ALOFT", "Up in the air", "High overhead, like a kite"],
  ["ALPHA", "First Greek letter", "___ and omega (start and end)"],
  ["AMPLE", "Plenty and then some", "More than enough"],
  ["ANVIL", "Blacksmith's heavy block", "Tiny bone in the ear"],
  ["ATLAS", "Book full of maps", "Globe-trotter's reference"],
  ["AUDIO", "Sound, to a technician", "___ book (story you listen to)"],
  ["AWOKE", "Opened one's eyes after a nap", "Came to in the morning"],
  ["ARISE", "Get up, as the sun does", "Crop up"],
  ["APART", "Separated", "Poles ___ (very different)"],
  ["ADMIT", "Let in", "Own up"],
  ["AHEAD", "In front", "Leading the race"],
  ["ALOUD", "Out loud, as in reading", "So everyone can hear"],
  ["ALTOS", "Choir singers between sopranos and tenors", "Low female voices"],
  ["ADAPT", "Adjust to fit", "Roll with the changes"],
  ["AGILE", "Nimble as a mountain goat", "Quick on one's feet"],
  ["AWASH", "Flooded, as with good news", "Covered in water"],

  // B
  ["BACON", "Breakfast rashers", "Bring home the ___"],
  ["BADGE", "Scout's sewn-on reward", "Pin-on emblem"],
  ["BAGEL", "Ring-shaped bread roll", "Bread with a hole in the middle"],
  ["BAKER", "Bread maker", "One who rises early to make rolls"],
  ["BANJO", "Twangy stringed instrument", "Bluegrass strummer's choice"],
  ["BASIL", "Herb in pesto", "Leafy friend of tomato"],
  ["BEACH", "Place for sandcastles", "Seaside stretch of sand"],
  ["BEARD", "Chin's whiskery coat", "What a lumberjack might grow"],
  ["BEANS", "They're baked in a tin", "Jelly ___ (chewy sweets)"],
  ["BEGIN", "Get going", "Kick off"],
  ["BELLS", "They ring out on a wedding day", "Jingle ___"],
  ["BENCH", "Park seat", "Where the substitutes sit"],
  ["BERRY", "Small juicy fruit", "Straw- or blue- follower"],
  ["BIRCH", "Tree with white peeling bark", "Silver ___"],
  ["BLEND", "Mix together smoothly", "Whizz in a mixer"],
  ["BLINK", "Quick shut of the eyes", "In the ___ of an eye"],
  ["BLOOM", "Flower's big moment", "Burst into blossom"],
  ["BLUSH", "Go pink with delight", "Rosy make-up"],
  ["BOARD", "Chess needs one", "Get on a train or plane"],
  ["BOOTS", "Wellies, for example", "Footwear for puddle-jumping"],
  ["BRAIN", "Your thinking cap's contents", "Clever clogs"],
  ["BRAVE", "Bold as a lion", "Courageous"],
  ["BREAD", "Loaf", "Sandwich essential"],
  ["BRICK", "Building block", "Reliable friend, in old slang"],
  ["BRIDE", 'She says "I do"', "Wedding-day star, often in white"],
  ["BRING", "Carry along", "___ a smile to someone's face"],
  ["BRISK", "Pleasantly quick, like a morning walk", "Fresh and chilly"],
  ["BROOK", "Babbling stream", "Little river"],
  ["BROOM", "Sweeping tool", "Witch's ride in stories"],
  ["BRUSH", "Painter's tool", "Tidy the hair"],
  ["BUDDY", "Pal", "Best mate"],
  ["BUILD", "Put together, like a sandcastle", "Construct"],
  ["BUNNY", "Fluffy hopper", "Easter rabbit"],
  ["BUNCH", "Bouquet", "A ___ of grapes"],
  ["BATCH", "A tray of freshly baked cookies", "Group made at once"],
  ["BELOW", "Underneath", "Downstairs"],
  ["BISON", "Shaggy beast of the plains", "Buffalo cousin"],
  ["BLANK", "Empty page", "Draw a ___ (forget)"],
  ["BLOCK", "Toy building cube", "Street's length"],
  ["BOOST", "Lift", "Pick-me-up"],
  ["BRAID", "Plait", "Woven hairstyle"],
  ["BREAK", "Tea time at work", "Summer holiday, perhaps"],
  ["BRIEF", "Short and sweet", "Quick"],
  ["BROWN", "Colour of chocolate", "Toast shade"],
  ["BUGLE", "Brass horn with no valves", "Scout camp wake-up call"],
  ["BASIN", "Washing-up bowl", "Sink"],
  ["BLISS", "Pure happiness", "Seventh heaven"],
  ["BUMPY", "Like a cobbled road", "Not smooth"],

  // C
  ["CABIN", "Cosy log hut", "Ship's bedroom"],
  ["CAMEL", "Desert ride with a hump", "Ship of the desert"],
  ["CANAL", "Waterway for narrowboats", "Man-made river"],
  ["CANDY", "Sweets, to Americans", "___ floss (fairground treat)"],
  ["CANOE", "Paddle-powered boat", "Kayak's cousin"],
  ["CARGO", "Ship's load", "Freight"],
  ["CAROL", "Festive song", "Sing merrily"],
  ["CARRY", "Hold and take along", "Bear"],
  ["CHAIR", "Seat with a back", "Run the meeting"],
  ["CHALK", "Hopscotch-drawing stick", "Like ___ and cheese"],
  ["CHARM", "Bracelet dangle", "Win over with a smile"],
  ["CHART", "Pop music ranking", "Graph"],
  ["CHASE", "Game of tag, essentially", "Run after"],
  ["CHEER", "Hip-hip-hooray!", "Shout for your team"],
  ["CHESS", "Game of kings and pawns", "Checkmate is its goal"],
  ["CHEST", "Pirate's treasure box", "Drawers for clothes"],
  ["CHICK", "Baby hen", "Fluffy yellow Easter bird"],
  ["CHIME", "Doorbell sound", "Ring like a clock"],
  ["CHIRP", "Songbird's sound", "Cricket's chatter"],
  ["CHORD", "Three notes played together", "Guitar shape"],
  ["CHORE", "Job like washing up", "Household task"],
  ["CHUNK", "Big piece", "Hunk of cheese"],
  ["CLASS", "School group", "Style and grace"],
  ["CLEAN", "Spick and span", "Tidy up"],
  ["CLEAR", "Crystal-like", "Cloudless"],
  ["CLIMB", "Go up a tree", "Scale a hill"],
  ["CLOCK", "It has hands but can't clap", "Timekeeper on the wall"],
  ["CLOTH", "Fabric", "Table cover"],
  ["CLOUD", "Fluffy thing in the sky", "Silver lining holder"],
  ["CLOWN", "Circus funny-person", "Red-nosed joker"],
  ["COACH", "Team trainer", "Bus for a school trip"],
  ["COAST", "Seaside", "Glide along with no effort"],
  ["COCOA", "Hot bedtime drink", "Chocolate's bean"],
  ["CORAL", "Reef builder", "Pinky-orange colour"],
  ["COUCH", "Sofa", "___ potato"],
  ["COUNT", "One, two, three...", "Tally up"],
  ["CRAFT", "Knitting or pottery, say", "Boat"],
  ["CRANE", "Long-legged wading bird", "Building-site lifter"],
  ["CREAM", "Topping for scones", "Milk's rich top"],
  ["CREEK", "Small stream", "Up the ___ (in a pickle)"],
  ["CRISP", "Fresh and crunchy", "Autumn-morning-like"],
  ["CROWN", "Royal headwear", "Top of the head"],
  ["CRUMB", "Tiny bit of cake", "Birds love one of these"],
  ["CRUST", "Pie's golden lid", "Edge of a pizza"],
  ["CURLY", "Like a pig's tail", "Wavy, as hair"],
  ["CYCLE", "Ride a bike", "Washing machine setting"],
  ["CABLE", "Wire", "___ car (mountain ride)"],
  ["CATCH", "Game of throw and ___", "Grab in mid-air"],
  ["CEDAR", "Fragrant evergreen", "Wood for pencils"],
  ["CHAIN", "Linked loops", "Daisy ___"],
  ["COMET", "Space visitor with a tail", "Streak in the night sky"],
  ["COMIC", "Funny paper", "Stand-up performer"],
  ["CROWD", "Throng", "Three's one, so they say"],
  ["CHILD", "Youngster", "Kid"],
  ["CHIPS", "Fish's partner", "Wood shavings"],
  ["CLAMP", "Grip tightly", "Tool that holds wood steady"],
  ["CLIFF", "Seaside rock face", "___hanger (tense ending)"],
  ["CLOAK", "Superhero's cape", "Long flowing garment"],
  ["CORNY", "Like a groan-worthy joke", "Cheesy"],
  ["CRAZE", "Fad", "Playground trend"],

  // D
  ["DAILY", "Every day", "Newspaper that comes out each morning"],
  ["DAIRY", "Milk and cheese section", "Where cows are milked"],
  ["DAISY", "White-petalled flower", "Fresh as a ___"],
  ["DANCE", "Boogie", "Waltz or tango"],
  ["DEPTH", "How deep something is", "Out of one's ___"],
  ["DIARY", "Dear ___...", "Journal"],
  ["DINER", "American roadside cafe", "Restaurant customer"],
  ["DITTO", "Same again", "Me too!"],
  ["DIVER", "Pool jumper", "Snorkeller's deeper cousin"],
  ["DOZEN", "Twelve", "Eggbox count"],
  ["DRAFT", "First go at a story", "Rough version"],
  ["DRAMA", "Theatre class", "Soap opera stuff"],
  ["DREAM", "Night-time adventure", "Big hope"],
  ["DRESS", "Frock", "Get your clothes on"],
  ["DRIFT", "Float along", "Snow pile"],
  ["DRIVE", "Take the car", "Motivation"],
  ["DOUGH", "Bread before baking", "What pizza starts as"],
  ["DUVET", "Snuggly bed cover", "Quilt"],
  ["DECOR", "Room style", "Interior design"],
  ["DELTA", "River's mouth", "Greek D"],
  ["DENIM", "Jeans fabric", "Blue cotton twill"],
  ["DINGO", "Wild Australian dog", "Outback howler"],
  ["DIZZY", "Spun around too much", "Giddy"],
  ["DRUMS", "Rhythm makers", "Kit behind the band"],
  ["DWELL", "Live", "Reside"],
  ["DEBUT", "First appearance", "Opening night"],

  // E
  ["EAGER", "Keen as mustard", "Raring to go"],
  ["EAGLE", "Bird with a golden variety", "Golf score two under par"],
  ["EARLY", "Before time", "The ___ bird catches the worm"],
  ["EARTH", "Our home planet", "Soil"],
  ["EASEL", "Artist's stand", "Frame for a canvas"],
  ["EIGHT", "Number of legs on an octopus", "Figure skater's figure"],
  ["ELBOW", "Arm's bend", "___ grease (hard work)"],
  ["ELDER", "Older one", "Tree with fragrant flowers"],
  ["EMBER", "Glowing coal", "Campfire's last glow"],
  ["EMPTY", "Nothing inside", "Like a licked-clean plate"],
  ["ENJOY", "Have fun with", "Relish"],
  ["ENTER", "Come in", "Keyboard's big key"],
  ["EQUAL", "The same", "Fair and even"],
  ["ERASE", "Rub out", "Wipe clean"],
  ["ESSAY", "School writing task", "Short piece of prose"],
  ["EVENT", "Happening", "Sports day race"],
  ["EXACT", "Spot on", "Precise"],
  ["EXTRA", "Bonus", "Background actor"],
  ["EVERY", "Each and ___", "All"],
  ["EXIST", "Be", "Be real"],
  ["ENTRY", "Way in", "Competition submission"],
  ["EPOCH", "Era", "Long period of history"],
  ["ERUPT", "Burst out, like a volcano", "Break into laughter"],
  ["EVOKE", "Bring to mind", "Call up a memory"],
  ["ELITE", "The very best", "Top-notch"],
  ["EMAIL", "Message from your inbox", "Send a note electronically"],
  ["ENVOY", "Messenger", "Diplomat"],

  // F
  ["FABLE", "Tale with a moral", "The Tortoise and the Hare, for one"],
  ["FAIRY", "Wish-granting sprite", "Tooth ___"],
  ["FANCY", "Posh", "Take a liking to"],
  ["FEAST", "Big celebratory meal", "Banquet"],
  ["FENCE", "Garden border", "Sit on the ___ (can't decide)"],
  ["FERRY", "Boat that crosses a channel", "Carry across water"],
  ["FETCH", "Dog's favourite game", "Go and get"],
  ["FIELD", "Meadow", "Sports pitch"],
  ["FIFTY", "Half a hundred", "Five tens"],
  ["FINCH", "Small songbird", "Gold- or bull- bird"],
  ["FLAME", "Candle's glow", "Old ___ (past sweetheart)"],
  ["FLASH", "Camera burst", "In a ___ (very quickly)"],
  ["FLOAT", "Bob on water", "Parade vehicle"],
  ["FLOCK", "Group of sheep", "Gather in crowds"],
  ["FLOOR", "Thing you walk on", "Storey"],
  ["FLOUR", "Cake's main ingredient", "Baker's white powder"],
  ["FLUTE", "Silver woodwind instrument", "Pipe played sideways"],
  ["FOCUS", "Concentrate", "Get the picture sharp"],
  ["FOGGY", "Misty", "Hazy, as a memory"],
  ["FORTY", "Four tens", "Life begins at it, some say"],
  ["FORUM", "Meeting place for discussion", "Online message board"],
  ["FRAME", "Picture border", "Glasses' rims"],
  ["FRESH", "Just baked", "Crisp and new"],
  ["FROST", "Icy morning coating", "Ice a cake"],
  ["FRUIT", "Apple or orange", "Result of hard work"],
  ["FUDGE", "Sweet crumbly treat", "Oh, ___! (mild exclamation)"],
  ["FUNNY", "Hilarious", "Ha-ha"],
  ["FERNS", "Feathery green plants", "Leafy woodland plants"],
  ["FLOSS", "String for teeth", "Candy ___ (fairground fluff)"],
  ["FORGE", "Blacksmith's workshop", "Create with hard work"],
  ["FROTH", "Cappuccino's foam", "Bubbly top"],
  ["FLUFF", "Soft stuff on a chick", "Tiny tuft"],
  ["FIRST", "Number one", "Gold medal position"],
  ["FLAIR", "Natural talent", "Style"],
  ["FROGS", "Lily-pad leapers", "Tadpoles grow into these"],

  // G
  ["GECKO", "Lizard that climbs walls", "Sticky-toed reptile"],
  ["GIANT", "Beanstalk resident", "Huge"],
  ["GLOBE", "World in a ball", "Snow ___"],
  ["GLORY", "Triumph", "Morning ___ (flower)"],
  ["GLOVE", "Mitten's cousin", "Fits like a ___"],
  ["GLEAM", "Shine", "Twinkle in the eye"],
  ["GLIDE", "Soar smoothly", "Skate along"],
  ["GOOSE", "Honking bird", "Golden egg layer, in a tale"],
  ["GRACE", "Elegance", "Poise"],
  ["GRADE", "School mark", "Level"],
  ["GRAIN", "Wheat or rice", "Wood's pattern"],
  ["GRAND", "Magnificent", "Piano type"],
  ["GRAPE", "Vine fruit", "Raisin, once"],
  ["GRAPH", "Chart with axes", "Plot the results"],
  ["GRASS", "Lawn stuff", "Where cows graze"],
  ["GRAVY", "Sunday roast sauce", "Meaty pour-over"],
  ["GREAT", "Terrific", "Big and brilliant"],
  ["GREEN", "Colour of go", "Village lawn"],
  ["GREET", "Say hello to", "Welcome"],
  ["GRILL", "Barbecue rack", "Cook under the heat"],
  ["GUIDE", "Tour leader", "Show the way"],
  ["GUEST", "Visitor", "Party invitee"],
  ["GUSTO", "Enthusiasm", "Zest"],
  ["GIFTS", "Presents", "Talents"],
  ["GOALS", "Things scored in football", "Aims"],
  ["GIDDY", "Dizzy with delight", "Light-headed"],
  ["GLAZE", "Shiny coating on a bun", "Pottery finish"],
  ["GNOME", "Garden ornament with a pointy hat", "Little bearded figure"],

  // H
  ["HABIT", "Routine", "Something done without thinking"],
  ["HAPPY", "Chuffed", "Full of joy"],
  ["HASTE", "Hurry", "More ___, less speed"],
  ["HATCH", "Come out of the egg", "Trapdoor"],
  ["HAVEN", "Safe place", "Harbour"],
  ["HAZEL", "Nut tree", "Greeny-brown eye colour"],
  ["HEART", "Love symbol", "Core of the matter"],
  ["HEDGE", "Leafy garden wall", "Row of privet"],
  ["HELLO", "Greeting", "Hi there!"],
  ["HERBS", "Parsley and thyme", "Garden flavourings"],
  ["HERON", "Long-legged fishing bird", "Grey wader"],
  ["HIKER", "Trail walker", "Rambler"],
  ["HOBBY", "Pastime", "Stamp collecting, for one"],
  ["HONEY", "Bee's sweet product", "Term of endearment"],
  ["HORSE", "Pony's big sibling", "Gymnastics apparatus"],
  ["HOTEL", "Place to stay on holiday", "Inn"],
  ["HOUSE", "Home", "Family dwelling"],
  ["HUMID", "Muggy", "Sticky, weather-wise"],
  ["HURRY", "Rush", "Get a move on"],
  ["HUSKY", "Sled dog", "Deep and throaty, as a voice"],
  ["HOVER", "Hang in the air like a hummingbird", "Float"],
  ["HINGE", "Door pivot", "Swing point"],
  ["HIPPO", "River horse, informally", "Big-mouthed African animal"],
  ["HOIST", "Lift", "Raise a flag"],
  ["HEAVY", "Weighty", "Hard to lift"],
  ["HUMUS", "Rich, dark garden soil", "Compost's crumbly result"],
  ["HAIKU", "Poem of five-seven-five", "Short Japanese verse"],

  // I
  ["ICING", "Cake topping", "The ___ on the cake"],
  ["IDEAL", "Perfect", "Just right"],
  ["IDEAS", "Bright sparks", "Brainwaves"],
  ["IGLOO", "Snow-block house", "Dome of ice"],
  ["IMAGE", "Picture", "Reflection"],
  ["INDEX", "Back-of-book guide", "Pointer finger"],
  ["INNER", "Inside", "___ child"],
  ["INPUT", "Contribution", "Data entered"],
  ["ISSUE", "Edition of a newspaper", "Topic"],
  ["IVORY", "Creamy white", "Piano key colour"],
  ["ITEMS", "Things on a list", "Articles"],
  ["INLET", "Small bay", "Narrow sea arm"],
  ["IRONY", "When things turn out the opposite", "Wry twist"],
  ["INTRO", "Song's opening bars", "Opening"],

  // J
  ["JAUNT", "Short fun trip", "Outing"],
  ["JELLY", "Wobbly party dessert", "___ and ice cream"],
  ["JEANS", "Denim trousers", "Blue legwear"],
  ["JEWEL", "Gem", "Crown decoration"],
  ["JOKER", "Prankster", "Wild card"],
  ["JOLLY", "Cheerful", "Merry and bright"],
  ["JUICE", "Orange squeeze", "Breakfast drink"],
  ["JUICY", "Full of flavour, like a peach", "Succulent"],
  ["JUMBO", "Extra large", "___ jet"],

  // K
  ["KAYAK", "Paddle boat that's a palindrome", "Canoe cousin"],
  ["KEBAB", "Food on a skewer", "Barbecue stick"],
  ["KITES", "Things flown on a windy day", "Soaring toys on strings"],
  ["KNACK", "Special skill", "Flair"],
  ["KNEAD", "Work dough", "Massage bread before baking"],
  ["KNEEL", "Get down, as for a proposal", "Bend low"],
  ["KNOCK", "Rap on the door", 'Joke opener before "Who\'s there?"'],
  ["KOALA", "Eucalyptus-munching marsupial", "Tree-hugging bear-like animal"],
  ["KAZOO", "Hum-into-it instrument", "Buzzy toy musical instrument"],

  // L
  ["LABEL", "Name tag", "Sticky tag"],
  ["LADLE", "Soup spoon", "Big scoop"],
  ["LARGE", "Big", "Size above medium"],
  ["LASER", "Beam of light", "Pointer in a presentation"],
  ["LATER", "See you ___!", "Afterwards"],
  ["LAUGH", "Ha-ha", "Giggle"],
  ["LAYER", "Tier of a cake", "Hen that's good at its job"],
  ["LEARN", "Find out", "Study"],
  ["LEASH", "Dog's lead", "Walkies strap"],
  ["LEMON", "Sour yellow fruit", "___ meringue pie"],
  ["LEVEL", "Flat", "Game stage"],
  ["LIGHT", "Not heavy", "Bulb's glow"],
  ["LILAC", "Pale purple", "Fragrant spring shrub"],
  ["LIMIT", "Boundary", "The sky's the ___"],
  ["LINEN", "Bedding", "Crisp fabric"],
  ["LLAMA", "Andes animal", "Woolly camel cousin"],
  ["LOCAL", "Nearby", "Neighbourhood"],
  ["LODGE", "Cabin in the woods", "Beaver's home"],
  ["LOFTY", "Tall", "High-minded"],
  ["LOGIC", "Reasoning", "Sense"],
  ["LOOPS", "Rollercoaster twists", "Circles"],
  ["LOTUS", "Water lily", "Yoga pose"],
  ["LOYAL", "Faithful", "True-hearted"],
  ["LUCKY", "Fortunate", "Four-leaf clover owner"],
  ["LUNAR", "Of the moon", "___ eclipse"],
  ["LUNCH", "Midday meal", "Packed ___"],
  ["LYRIC", "Song line", "Word in a verse"],
  ["LEAFY", "Green and tree-lined", "Like a salad"],
  ["LEMUR", "Ring-tailed primate", "Madagascar animal"],
  ["LIVEN", "Perk up", "Brighten"],

  // M
  ["MAGIC", "Abracadabra stuff", "Wizardry"],
  ["MANGO", "Tropical fruit", "Yellow-orange smoothie flavour"],
  ["MAPLE", "Tree with syrup", "Leaf on the Canadian flag"],
  ["MARSH", "Swamp", "Wetland"],
  ["MATCH", "Football game", "Pair"],
  ["MEDAL", "Olympic award", "Gold, silver or bronze"],
  ["MELON", "Big juicy fruit", "Water-___"],
  ["MERRY", "Jolly", "Festive"],
  ["METAL", "Iron or copper", "Heavy ___ (loud rock)"],
  ["MIXER", "Food whizzer", "Party ice-breaker"],
  ["MODEL", "Role ___", "Miniature version"],
  ["MOOSE", "Big antlered deer", "Elk's relative"],
  ["MOTTO", "Slogan", "Saying to live by"],
  ["MOUSE", "Computer pointer", "Cheese lover"],
  ["MOUTH", "Where a river meets the sea", "It smiles"],
  ["MOVIE", "Film", "Flick"],
  ["MUDDY", "Like wellies after a walk", "Messy"],
  ["MUSIC", "Tunes", "Melodies"],
  ["MAKER", "Creator", "Builder"],
  ["MANOR", "Country house", "Stately home"],
  ["MIRTH", "Laughter", "Merriment"],
  ["MOTOR", "Engine", "Go-kart's hum-maker"],
  ["MOSSY", "Covered in soft green stuff", "Like a rolling stone isn't"],
  ["MIMIC", "Copycat", "Parrot, as a talent"],

  // N
  ["NAILS", "Hammer's targets", "Painted fingertips"],
  ["NANNY", "Childminder", "Grandma, affectionately"],
  ["NIECE", "Sister's daughter", "Aunt's young relative"],
  ["NIGHT", "When the stars come out to play", "Good ___, sleep tight"],
  ["NOBLE", "Honourable and good", "Like a knight in shining armour"],
  ["NOISE", "Racket from the band next door", "Din"],
  ["NORTH", "Where a compass needle points", "Up, on most maps"],
  ["NOVEL", "Book you can't put down", "Brand-new and original"],
  ["NUDGE", "Gentle elbow prod", "Friendly reminder"],
  ["NYLON", "Stretchy fabric in tights", "Tent material"],
  ["NACHO", "Cheesy tortilla chip", "Crunchy cinema snack"],
  ["NESTS", "Homes built from twigs", "Fits inside, like dolls"],
  ["NOTCH", "Small V-shaped cut", "Top-___ (first-class)"],

  // O
  ["OASIS", "Palm-shaded spot in a desert", "Refreshing retreat"],
  ["OCEAN", "Atlantic or Pacific", "Home of the blue whale"],
  ["OFFER", "Kind proposal", "Hold out a helping hand"],
  ["OFTEN", "Lots of times", "Frequently"],
  ["OLIVE", "Green pizza topping", "Branch held out in peace"],
  ["ONION", "Veg that can make you weep", "Bulb with many layers"],
  ["OPERA", "Show where everything is sung", "Soap ___"],
  ["ORBIT", "The moon's lap around Earth", "Circle in space"],
  ["ORDER", "Request at a cafe counter", "Neatness and tidiness"],
  ["OTTER", "Playful river swimmer", "Animal that holds hands while napping"],
  ["OUNCE", "Tiny weight", "Not an ___ of doubt"],
  ["OUTER", "On the outside", "___ space"],
  ["OWNER", "Proud pet parent", "Possessor"],
  ["OZONE", "Earth's sun-shielding layer", "Bracing seaside air, fondly"],
  ["OTHER", "The grass is greener on the ___ side", "Different one"],
  ["OPTIC", "To do with the eye", "___ fibre (light-carrying cable)"],
  ["OCTET", "Group of eight musicians", "Double quartet"],

  // P
  ["PAINT", "Stuff on an artist's palette", "Colour in the walls"],
  ["PANDA", "Bamboo-munching bear", "Black-and-white cuddly animal"],
  ["PAPER", "What this news is printed on", "Origami material"],
  ["PARTY", "Birthday bash", "Balloons-and-cake celebration"],
  ["PASTA", "Spaghetti or penne", "Italian staple, often al dente"],
  ["PATCH", "Pumpkin ___", "Mend a hole in jeans"],
  ["PEACE", "Calm and quiet", "Harmony"],
  ["PEACH", "Fuzzy stone fruit", "A real ___ (lovely person)"],
  ["PEARL", "Oyster's treasure", "Gem from the sea"],
  ["PECAN", "Nut in a sticky pie", "Maple syrup's crunchy partner"],
  ["PEDAL", "Bike part you push", "Piano's foot lever"],
  ["PENNY", "Copper coin", "The ___ drops (it finally makes sense)"],
  ["PEONY", "Big, blousy pink flower", "Early-summer garden bloom"],
  ["PERCH", "Bird's resting spot", "Freshwater fish"],
  ["PIANO", "Instrument with 88 keys", "Grand ___"],
  ["PIECE", "Slice of cake", "Jigsaw bit"],
  ["PILOT", "Person in the cockpit", "First episode of a TV series"],
  ["PINCH", "Tiny bit of salt", "At a ___ (if need be)"],
  ["PIZZA", "Pie with a margherita variety", "Takeaway that comes in slices"],
  ["PLACE", "Spot", "Set a ___ at the table"],
  ["PLAID", "Tartan pattern", "Checked fabric"],
  ["PLAIN", "Simple and unfussy", "Wide, flat grassland"],
  ["PLANE", "Jumbo jet, say", "Woodworker's smoothing tool"],
  ["PLANT", "Sunflower or fern", "Pop seeds in the ground"],
  ["PLATE", "Dinner dish", "Clean your ___"],
  ["PLAZA", "Open town square", "Spot for a fountain and a chat"],
  ["PLUME", "Fancy feather", "Wisp of steam"],
  ["PLUMS", "Purple fruits for jam", "Sugar ___ (festive sweets)"],
  ["POINT", "Sharp tip", "Score in a game"],
  ["POLAR", "___ bear", "From near the North or South Pole"],
  ["POPPY", "Red wildflower", "Bloom of the cornfields"],
  ["PORCH", "Covered front step", "Spot for a rocking chair"],
  ["POUCH", "Kangaroo's pocket", "Little drawstring bag"],
  ["PRIZE", "Reward for the winner", "First ___"],
  ["PROUD", "Chuffed to bits", "Beaming, like a parent at sports day"],
  ["PUPIL", "Student", "Black centre of the eye"],
  ["PUPPY", "Young pooch", "___ love"],
  ["PURSE", "Little money bag", "Pucker, as lips"],
  ["PETAL", "One of a daisy's many", "Rose part"],
  ["PHONE", "Ring someone", "Mobile"],
  ["PHOTO", "Snap for the album", "Say cheese for this"],
  ["PRISM", "Glass that splits light into a rainbow", "Triangular solid"],
  ["PRINT", "Put on paper", "Paw mark in the snow"],
  ["PROSE", "Writing that doesn't rhyme", "Ordinary language"],
  ["PASTE", "Wallpaper glue", "Copy and ___"],
  ["PEARS", "Fruits that can be poached", "Apples' cousins"],
  ["PIPER", "Player of the pipes", "He who pays the ___ calls the tune"],
  ["POEMS", "Verses", "Limericks and sonnets"],
  ["PANEL", "Quiz show judges", "Flat section of a fence"],
  ["PAUSE", "Button for a quick break", "Stop for a moment"],
  ["PIXEL", "Tiny dot on a screen", "Picture element"],
  ["PLUCK", "Courage", "Play a harp string"],

  // Q
  ["QUACK", "Duck's hello", "Pond sound"],
  ["QUAIL", "Small bird with speckled eggs", "Plump little ground bird"],
  ["QUART", "Two pints", "Old liquid measure"],
  ["QUEEN", "Most powerful chess piece", "Hive's head bee"],
  ["QUEST", "Heroic journey", "Search for treasure"],
  ["QUICK", "Fast as a flash", "Speedy"],
  ["QUIET", "Hush!", "Peaceful"],
  ["QUILT", "Patchwork bed cover", "Cosy stitched blanket"],
  ["QUIRK", "Charming oddity", "Little habit that makes you you"],
  ["QUOTE", "Famous saying", "Builder's estimate"],
  ["QUOTA", "Fair share", "Set amount"],

  // R
  ["RADIO", "Wireless, in Grandad's day", "Tune in to this"],
  ["RAINY", "Wellies weather", "Saving for a ___ day"],
  ["RAISE", "Lift up", "Bring up, as children"],
  ["RALLY", "Long tennis exchange", "Gather together for a cause"],
  ["RANCH", "Cattle farm", "Cowboy's spread"],
  ["RANGE", "Mountain chain", "Old-fashioned kitchen cooker"],
  ["RAVEN", "Glossy black bird", "Jet-black, as hair"],
  ["REACH", "Stretch out for", "Arrive at"],
  ["READY", "___, steady, go!", "All set"],
  ["RELAX", "Put your feet up", "Unwind"],
  ["REPLY", "Answer a letter", "Write back"],
  ["RHYME", "Nursery ___", "Cat and hat, for example"],
  ["RIDER", "Person in the saddle", "Cyclist or jockey"],
  ["RIDGE", "Hill's crest", "Raised line"],
  ["RIVER", "It has a mouth but never eats", "Flowing water"],
  ["ROAST", "Sunday dinner", "Cook in the oven"],
  ["ROBIN", "Red-breasted garden bird", "Christmas card favourite"],
  ["ROBOT", "Mechanical helper", "Machine that might vacuum for you"],
  ["ROCKY", "Stony, like a path", "A bit wobbly"],
  ["ROUND", "Shaped like a wheel", "Quiz section"],
  ["ROUTE", "Way to go", "Bus's path"],
  ["ROYAL", "Fit for a king", "Regal"],
  ["RULER", "Twelve-inch measuring stick", "Monarch"],
  ["RURAL", "Out in the countryside", "Rustic"],
  ["RACER", "Speedy competitor", "Go-kart, say"],
  ["RAPID", "Very fast", "Quick-fire"],
  ["RATIO", "Two parts to one, say", "Proportion"],
  ["REALM", "Kingdom", "Fairy-tale domain"],
  ["RELAY", "Baton race", "Pass on a message"],
  ["RINSE", "Wash off the suds", "Swish with water"],
  ["ROOST", "Where hens settle down", "Rule the ___"],
  ["ROSES", "Red blooms for sweethearts", "Everything's coming up these"],
  ["ROWER", "Oar puller", "Boat crew member"],
  ["RADAR", "Palindromic tracking system", "Off the ___ (unnoticed)"],
  ["REEDS", "Tall waterside grasses", "Clarinet parts"],
  ["ROVER", "Explorer on Mars", "Wanderer"],

  // S
  ["SALAD", "Leafy side dish", "Fruit ___"],
  ["SALSA", "Tomato dip with a kick", "Lively Latin dance"],
  ["SANDY", "Like a beach towel", "Gritty"],
  ["SAUCE", "Pasta topping", "Ketchup, for one"],
  ["SCALE", "Do-re-mi-fa-so-la-ti-do", "Climb up"],
  ["SCARF", "Woolly neck warmer", "Snowman's accessory"],
  ["SCENE", "Part of an act in a play", "Beautiful view"],
  ["SCENT", "Smell a bloodhound follows", "Perfume"],
  ["SCONE", "Cream tea bake", "Jam first or cream first? Discuss"],
  ["SCOOP", "Ice-cream serving", "News exclusive"],
  ["SCOUT", "Camping club member", "Look around for"],
  ["SEEDS", "Tiny starters for a garden", "Sunflower ___"],
  ["SERVE", "Tennis opener", "Dish up dinner"],
  ["SEVEN", "Days in a week", "Colours of the rainbow"],
  ["SHADE", "Cool spot under a tree", "Tone of a colour"],
  ["SHAPE", "Circle or square", "Keep in good ___"],
  ["SHARE", "Divide fairly", "It's nice to do this with friends"],
  ["SHEEP", "Animals counted at bedtime", "Woolly flock"],
  ["SHELF", "Spot for your books", "Ledge"],
  ["SHELL", "Seaside find you can hear the sea in", "Tortoise's home"],
  ["SHINE", "Rise and ___!", "Polish until it gleams"],
  ["SHIRT", "Buttoned top", "Keep your ___ on! (stay calm)"],
  ["SHORE", "Where the waves lap", "Seaside"],
  ["SHRUB", "Garden bush", "Hedge plant"],
  ["SKATE", "Glide across the ice", "Roller ___"],
  ["SLATE", "Roof tile rock", "Clean ___ (fresh start)"],
  ["SLEEP", "Forty winks", "What dormice do all winter"],
  ["SLIDE", "Playground chute", "Hair clip"],
  ["SLOTH", "Slow, upside-down tree-dweller", "Leisurely rainforest mammal"],
  ["SMALL", "Teeny", "It's a ___ world"],
  ["SMART", "Clever", "Dressed to impress"],
  ["SMILE", "Say cheese!", "Grin from ear to ear"],
  ["SNACK", "Nibble between meals", "Crackers, perhaps"],
  ["SNAIL", "Slowcoach with a shell", "___ mail (old-fashioned post)"],
  ["SNOWY", "Like a winter wonderland", "White, as an owl"],
  ["SOLAR", "Powered by the sun", "___ system"],
  ["SOLID", "Not liquid or gas", "Dependable"],
  ["SOUND", "What you hear", "Safe and ___"],
  ["SPACE", "The final frontier", "Room to spare"],
  ["SPADE", "Digging tool", "Playing card suit"],
  ["SPARK", "Bright idea's beginning", "Tiny flash"],
  ["SPEAK", "Talk", "___ up! (louder, please)"],
  ["SPICE", "Cinnamon or ginger", "Variety is the ___ of life"],
  ["SPOON", "Soup scoop", "Cutlery for pudding"],
  ["SPORT", "Football or tennis", "Good ___ (fair player)"],
  ["SPRAY", "Sea mist", "Spritz"],
  ["STAGE", "Where actors tread the boards", "Step along the way"],
  ["STAIR", "One step up", "Part of a flight"],
  ["STAMP", "It goes on an envelope", "Stomp your feet"],
  ["STAND", "Get up on your feet", "Market stall"],
  ["STARS", "Night-sky twinklers", "Leading actors"],
  ["START", "Get going", "Ready, steady, go!"],
  ["STEAM", "Kettle's breath", "Full ___ ahead"],
  ["STEEL", "Strong metal", "Man of ___ (superhero)"],
  ["STONE", "Pebble", "Peach's centre"],
  ["STORY", "Once upon a time...", "Bedtime tale"],
  ["STRAW", "Milkshake sipper", "Scarecrow stuffing"],
  ["STUDY", "Hit the books", "Home office"],
  ["SUGAR", "Sweetener in tea", "Term of endearment"],
  ["SUNNY", "Bright and cheerful", "Day for a picnic"],
  ["SUPER", "Fantastic", "Hero's prefix"],
  ["SWEET", "Sugary", "Kind and lovely"],
  ["SWIFT", "Speedy", "Bird that sleeps on the wing"],
  ["SWING", "Playground ride", "Big-band jazz style"],
  ["SAUNA", "Finnish steam room", "Hot wooden cabin"],
  ["SEALS", "Flippered swimmers", "Closes an envelope"],
  ["SENSE", "Touch or taste", "It makes ___ (it's logical)"],
  ["SHEET", "Bed linen", "Piece of paper"],
  ["SHINY", "Brand-new and gleaming", "Glossy"],
  ["SKILL", "Talent", "Know-how"],
  ["SLOPE", "Ski run", "Hillside"],
  ["SNORE", "Zzz, noisily", "Sound from a deep sleeper"],
  ["SONAR", "Sound-based sea scanner", "Bat-like echo tech"],
  ["SPELL", "Abracadabra, perhaps", "Say the letters in order"],
  ["SPOKE", "Bicycle wheel rod", "Talked"],
  ["SPRIG", "Little stem of holly", "Herb twig"],
  ["SQUID", "Inky sea creature", "Ten-armed swimmer"],
  ["STEER", "Turn the wheel", "Guide"],
  ["STICK", "Fetch toy for a dog", "Glue in place"],
  ["STILL", "Motionless", "Calm, like a pond"],
  ["STRUM", "Play a guitar", "Brush the strings"],
  ["SWAMP", "Home for frogs and alligators", "Bog"],
  ["SWEEP", "Use a broom", "Chimney cleaner"],
  ["SWIRL", "Twirl of whipped cream", "Spiral"],
  ["SALTY", "Like seawater", "Crisps' flavour, often"],
  ["SMELL", "Sniff", "Wake up and ___ the coffee"],
  ["SOCKS", "Odd ones vanish in the wash", "Toasty foot covers"],
  ["SAVVY", "Street-smart", "In the know"],
  ["SIEVE", "Kitchen strainer", "Memory like a ___ (forgetful)"],
  ["STORK", "Long-legged bird of baby legend", "Big white wading bird"],

  // T
  ["TABLE", "Dining furniture", "Times ___"],
  ["TACOS", "Crunchy Mexican shells", "Tuesday treats, for some"],
  ["TALES", "Fairy ___", "Stories"],
  ["TALLY", "Keep count", "Score so far"],
  ["TANGO", "It takes two to do this", "Dramatic ballroom dance"],
  ["TASTE", "Sense of the tongue", "Try a nibble"],
  ["TEACH", "Educate", "Show how it's done"],
  ["TEETH", "Pearly whites", "Chompers"],
  ["TEMPO", "Musical speed", "Pace"],
  ["TENTS", "Camping homes", "Big tops, e.g."],
  ["THANK", "Show gratitude to", "___ you very much!"],
  ["THEME", "Party idea", "Tune for a TV show"],
  ["THREE", "Trio", "Number of little pigs"],
  ["THUMB", "Green ___ (gardener's gift)", "Hitch-hiker's signal"],
  ["TIARA", "Sparkly princess headpiece", "Jewelled headband"],
  ["TIDAL", "Like a rock pool's comings and goings", "Moon-driven, as the sea"],
  ["TIGER", "Striped big cat", "Grr-eat stripy jungle cat"],
  ["TIMER", "Egg ___", "Kitchen countdown clock"],
  ["TOAST", "Breakfast bread", "Warm by the fire"],
  ["TODAY", "This very day", "Here and now"],
  ["TOKEN", "Game piece", "Small symbol of thanks"],
  ["TOOTH", "Sweet ___", "Molar"],
  ["TORCH", "Handheld light", "Olympic flame carrier"],
  ["TOTAL", "Sum at the end", "Complete"],
  ["TOWEL", "Beach ___", "Drying cloth"],
  ["TOWER", "Tall building", "Rapunzel's home"],
  ["TRACK", "Running circuit", "Song on an album"],
  ["TRAIL", "Hiking path", "Follow the footprints"],
  ["TRAIN", "Choo-choo", "Practise hard"],
  ["TREAT", "Goodie", "My ___! (I'm paying)"],
  ["TREND", "Latest fashion", "Direction things are going"],
  ["TRUCK", "Lorry", "Fire engine, e.g."],
  ["TRULY", "Honestly", "Yours ___"],
  ["TRUNK", "Elephant's nose", "Tree's base"],
  ["TRUST", "Believe in", "Faith in someone"],
  ["TULIP", "Dutch spring flower", "Cup-shaped bloom"],
  ["TUTOR", "Private teacher", "Coach for exams"],
  ["TWIGS", "Bits of a nest", "Small sticks"],
  ["TWINS", "Pair born together", "Double trouble"],
  ["TWIRL", "Spin like a ballerina", "Twist around"],
  ["THYME", "Herb that sounds like the clock", "Parsley, sage, rosemary and ___"],
  ["TOPAZ", "Golden-yellow gem", "November birthstone"],
  ["TRAIT", "Quality", "Characteristic"],
  ["TREES", "Oaks and elms", "They're found in woods"],
  ["TUNES", "Melodies", "Songs to hum"],
  ["TIDES", "Ebb and flow", "Sea's twice-daily movements"],
  ["TAPIR", "Snouted rainforest mammal", "Animal with a tiny trunk"],
  ["TOPIC", "Subject", "Talking point"],
  ["TRIKE", "Three-wheeled bike", "Toddler's ride"],
  ["TWEED", "Woolly jacket fabric", "Country-gent cloth"],

  // U
  ["ULTRA", "Extremely, as a prefix", "Super-duper"],
  ["UNCLE", "Parent's brother", "Bob's your ___!"],
  ["UNDER", "Below", "___ the weather (not tip-top)"],
  ["UNITE", "Come together", "Join forces"],
  ["UNITY", "Togetherness", "Oneness"],
  ["UNTIL", "Up to the time", "Till"],
  ["UPPER", "Higher", "Keep a stiff ___ lip"],
  ["URBAN", "Of the city", "Town-based"],
  ["USUAL", "The ___, please (regular's order)", "Normal"],
  ["UTTER", "Say out loud", "Complete, total"],
  ["USHER", "Cinema seat guide", "Show in"],
  ["UNZIP", "Open a coat", "Undo a bag"],

  // V
  ["VALUE", "Worth", "Hold dear"],
  ["VIDEO", "Clip to watch", "Recording"],
  ["VIEWS", "Scenic sights", "Opinions"],
  ["VILLA", "Holiday house with a pool", "Grand country home"],
  ["VINYL", "What LPs are made of", "Record material"],
  ["VIOLA", "Violin's bigger sibling", "Pansy relative"],
  ["VISIT", "Pop round", "Trip to see Gran"],
  ["VITAL", "Essential", "Absolutely key"],
  ["VIVID", "Bright and bold", "Like a lively imagination"],
  ["VOCAL", "Of the voice", "Outspoken"],
  ["VOICE", "Singer's instrument", "Speak up for"],
  ["VALET", "Car parker at a hotel", "Gentleman's helper"],
  ["VERSE", "Chorus's partner", "Poetry"],
  ["VAULT", "Gymnast's leap", "Jump over"],
  ["VENUE", "Concert location", "Hall for a party"],
  ["VISOR", "Sun shade on a cap", "Helmet's flip-down"],

  // W
  ["WAFER", "Thin crispy biscuit", "Ice-cream sandwich layer"],
  ["WAGON", "Cart", "Covered ___"],
  ["WALTZ", "Dance in three-four time", "Stroll in confidently"],
  ["WATCH", "Timepiece on your wrist", "Keep an eye on"],
  ["WATER", "H2O", "Give the plants a drink"],
  ["WAVES", "Sea ripples", "Hellos from afar"],
  ["WHALE", "Big sea creature", "Having a ___ of a time"],
  ["WHEAT", "Grain for bread", "Golden field crop"],
  ["WHEEL", "Round thing on a bike", "Ferris ___"],
  ["WHISK", "Beat the eggs", "Balloon-shaped kitchen tool"],
  ["WHOLE", "All of it", "In one piece"],
  ["WIDTH", "Breadth", "Side-to-side measure"],
  ["WINDY", "Blustery", "Perfect kite weather"],
  ["WINGS", "Bird's flappers", "Theatre's sides"],
  ["WITTY", "Quick with a quip", "Clever and funny"],
  ["WORDS", "What a dictionary defines", "Vocabulary"],
  ["WORLD", "Earth", "Out of this ___ (amazing)"],
  ["WORTH", "Value", "Well ___ the wait"],
  ["WRITE", "Put pen to paper", "Pen a letter"],
  ["WOVEN", "Like a basket", "Interlaced"],
  ["WHIRL", "Spin round and round", "Give it a ___ (try it)"],
  ["WEAVE", "Make cloth on a loom", "Zigzag through a crowd"],
  ["WIDEN", "Make broader", "Open up, as eyes in wonder"],
  ["WRIST", "Where a watch goes", "Hand's joint"],

  // Y
  ["YACHT", "Sailing boat for a regatta", "Posh boat"],
  ["YEARN", "Long for", "Pine"],
  ["YIELD", "Harvest amount", "Give way"],
  ["YODEL", "Alpine song", "Mountain-top warble"],
  ["YOUNG", "Youthful", "___ at heart"],
  ["YOUTH", "Early years", "Young people"],
  ["YUMMY", "Delicious", "Tasty, to a toddler"],
  ["YEAST", "What makes bread rise", "Baker's ingredient"],

  // Z
  ["ZEBRA", "Striped horse", "___ crossing"],
  ["ZESTY", "Tangy, like lemon", "Full of zing"],
  ["ZIPPY", "Speedy and lively", "Nippy, like a little car"],

  // extras
  ["CHAMP", "Winner!", "Top of the league"],
  ["CHEWY", "Like toffee", "Takes some munching"],
  ["CLING", "Hold on tight", "___ film (sandwich wrap)"],
  ["CRATE", "Wooden box for apples", "Pup's cosy den"],
  ["CREST", "Top of a wave", "Family emblem"],
  ["DIGIT", "Finger or toe", "Any number from 0 to 9"],
  ["DRAKE", "Male duck", "Mallard with a green head"],
  ["EXCEL", "Do brilliantly", "Shine at school"],
  ["FAUNA", "Animal life", "Flora's partner"],
  ["FLORA", "Plant life", "Fauna's partner"],
  ["FIZZY", "Bubbly, like lemonade", "Sparkling"],
  ["FOYER", "Theatre lobby", "Entrance hall"],
  ["FRILL", "Ruffle on a skirt", "No-___ (simple and basic)"],
  ["GROVE", "Little orchard", "Cluster of trees"],
  ["JAZZY", "Bright and snazzy", "Swinging, musically"],
  ["KIOSK", "Little booth selling ice creams", "Newsstand"],
  ["LATTE", "Milky coffee", "Cafe order with froth"],
  ["MERIT", "Worthiness", "Gold star for good work"],
  ["MOCHA", "Chocolatey coffee", "Coffee-brown colour"],
  ["AGLOW", "Beaming with happiness", "Shining softly"],
  ["ALIGN", "Line up neatly", "Put in a row"],
  ["ALLOW", "Let", "Say yes to"],
  ["AMUSE", "Tickle pink", "Entertain"],
  ["ATOLL", "Ring-shaped coral island", "Lagoon's reef ring"],
  ["AZURE", "Sky blue", "Colour of a Mediterranean sea"],
  ["INLAY", "Decorative pattern set into wood", "Mosaic work"],
  ["ISLET", "Tiny island", "Speck of land in a lake"],
  ["ELFIN", "Small and delicate, like a pixie", "Impish"],
  ["EDGES", "Borders of a jigsaw, done first", "Brinks"],
  ["DOLLY", "Toy baby", "Cart for moving boxes"],
];
