import type { Clued } from "./types.ts";

/** Nine-letter crossword answers for the Sunday crossword, each with one or more clues. */
export const NINE_LETTER_WORDS: readonly Clued[] = [
  // A
  ["ACCORDION", "Squeezebox with buttons and bellows", "Instrument you play by squashing it"],
  ["ACROBATIC", "Full of flips and tumbles", "Like a trapeze act"],
  ["ADVENTURE", "Exciting journey into the unknown", "Quest with a map and a packed lunch"],
  ["AFTERNOON", "Time for tea and a biscuit", "The bit of the day after lunch"],
  ["ALLIGATOR", "Toothy swamp reptile with a broad snout", "See you later, ___!"],
  ["ALLOTMENT", "Rented patch for growing runner beans", "Plot for keen gardeners"],
  ["AMBITIOUS", "Aiming high", "Dreaming big and working for it"],
  ["ANIMATION", "Cartoon-making, frame by frame", "Liveliness"],
  ["ARCHITECT", "Designer of buildings", "Person who draws up the house plans"],
  ["ASPARAGUS", "Green spears served with butter", "Vegetable with a pointy tip"],
  ["ASTRONAUT", "Space traveller", "Moonwalker in a big white suit"],
  ["AUTOGRAPH", "Famous signature for a fan", "Star's scribble in your book"],
  // B
  ["BADMINTON", "Game played with a shuttlecock", "Racket sport named after a stately home"],
  ["BALLERINA", "Dancer on her tiptoes", "Star of Swan Lake"],
  ["BANDSTAND", "Park platform for a brass band", "Seaside stage with a roof"],
  ["BEANSTALK", "Jack's very tall climb", "Giant plant from a magic seed"],
  ["BEDSPREAD", "Cover on top of the duvet", "Quilt that makes the bed look smart"],
  ["BEEKEEPER", "Honey farmer in a veiled hat", "Hive minder"],
  ["BLACKBIRD", "Songbird with an orange beak", "Garden singer in four and twenty pies"],
  ["BLUEBELLS", "Spring flowers that carpet the woods", "Nodding woodland blooms"],
  ["BLUEBERRY", "Little fruit for muffins", "Berry that dyes your tongue"],
  ["BOOKSHELF", "Home for your library", "Plank full of paperbacks"],
  ["BOOMERANG", "Curved stick that comes back", "Throw it and duck!"],
  ["BRAINWAVE", "Sudden clever idea", "Light-bulb moment"],
  ["BREAKFAST", "First meal of the day", "Cereal time"],
  ["BRILLIANT", "Absolutely smashing", "Dazzlingly bright"],
  ["BUCCANEER", "Swashbuckling pirate", "Seafaring rogue with a parrot"],
  ["BUMBLEBEE", "Fuzzy buzzer in the flowerbed", "Big, round, striped pollinator"],
  ["BUTTERCUP", "Yellow flower held under the chin", "Shiny meadow bloom"],
  ["BUTTERFLY", "Fluttery insect that was a caterpillar", "Swimming stroke with a big splash"],
  // C
  ["CANDLELIT", "Glowing softly, like a dinner for two", "Lit by little flames"],
  ["CARPENTER", "Woodworker with a toolbox", "Person who might build you a shed"],
  ["CARTWHEEL", "Sideways spin on hands and feet", "Playground gymnastics move"],
  ["CELEBRATE", "Throw a party", "Mark a happy occasion"],
  ["CHAMOMILE", "Calming bedtime tea", "Daisy-like herb"],
  ["CHARACTER", "Person in a story", "A letter or a symbol"],
  ["CHOCOLATE", "Sweet treat from cocoa beans", "What an Easter egg is made of"],
  ["CHRISTMAS", "Festive day in December", "Season of crackers and carols"],
  ["CLOCKWORK", "Wind-up mechanism", "Like ___ (running smoothly)"],
  ["COASTLINE", "Where the land meets the sea", "Edge of the map, for sailors"],
  ["COMPANION", "Friend at your side", "Travelling chum"],
  ["CONDUCTOR", "Orchestra leader with a baton", "Ticket checker on a train"],
  ["CORIANDER", "Leafy herb for curries", "Cilantro, to Americans"],
  ["CORNFLOUR", "Powder for thickening gravy", "Custard's secret ingredient"],
  ["COURGETTE", "Zucchini, to Brits", "Green summer squash"],
  ["CRANBERRY", "Tart red berry for sauce", "Juice with a festive tang"],
  ["CRESCENDO", "Musical build-up to the loud bit", "Getting louder and louder"],
  ["CROCODILE", "Toothy reptile of the Nile", "Pairs of schoolchildren walking in a line"],
  ["CROISSANT", "Flaky French breakfast pastry", "Crescent of buttery layers"],
  ["CURIOSITY", "Wanting to know everything", "It makes you ask why"],
  // D
  ["DANDELION", "Yellow weed that turns into a clock", "Flower whose seeds you blow away"],
  ["DECKCHAIR", "Stripy folding seat at the seaside", "Sun lounger's cousin on the pier"],
  ["DELIGHTED", "Thrilled to bits", "Tickled pink"],
  ["DETECTIVE", "Solver of mysteries", "Sherlock, for one"],
  ["DISCOVERY", "Brand-new find", "Eureka moment"],
  ["DRAGONFLY", "Shimmering insect over the pond", "Four-winged flying jewel"],
  ["DRUMSTICK", "Beater for a snare", "Lolly with a raspberry and milk flavour"],
  // E
  ["ENCHANTED", "Under a magic spell", "Utterly charmed"],
  ["ENCOURAGE", "Cheer on", "Give a friendly push"],
  ["ENERGETIC", "Full of beans", "Bouncing off the walls"],
  ["ESPLANADE", "Seafront promenade", "Where you stroll with an ice cream"],
  ["EVERGREEN", "Tree that keeps its leaves all year", "Timelessly popular"],
  ["EVERYBODY", "All the people", "One and all"],
  ["EXCELLENT", "First-rate", "Top marks!"],
  ["EXCURSION", "Day trip", "Outing on a coach"],
  // F
  ["FAIRYTALE", "Once upon a time story", "Storybook with a happy ending"],
  ["FANTASTIC", "Brilliant", "Out of this world"],
  ["FINGERTIP", "Where your fingerprint is", "At your ___ (close to hand)"],
  ["FIREPLACE", "Cosy hearth", "Where stockings are hung"],
  ["FIREWORKS", "Bangs and sparkles in the night sky", "Bonfire Night display"],
  ["FISHERMAN", "Angler on the riverbank", "Person who tells tales of the one that got away"],
  ["FLOWERPOT", "Terracotta home for a geranium", "Container on the windowsill"],
  ["FOOTPRINT", "Mark left in the sand", "Clue a detective might measure"],
  ["FORTUNATE", "Lucky", "Blessed with good luck"],
  ["FREESTYLE", "Swimming race where you pick the stroke", "Improvised, like a rap"],
  ["FRUITCAKE", "Rich cake full of currants", "Traditional wedding cake"],
  // G
  ["GALLIVANT", "Gad about having fun", "Go off on jaunts"],
  ["GEOGRAPHY", "School subject with maps", "The lie of the land"],
  ["GOLDCREST", "Britain's tiniest bird", "Little bird with a golden stripe"],
  ["GRAPEVINE", "Plant that grows in a vineyard", "Heard it on the ___ (gossip)"],
  ["GRASSLAND", "Wide green prairie", "Meadow country"],
  ["GUITARIST", "Strummer in a band", "Player of six strings"],
  // H
  ["HAIRBRUSH", "Tangle tamer", "Bristly thing on the dressing table"],
  ["HANDSHAKE", "Friendly grip when you meet", "Deal sealer"],
  ["HANDSTAND", "Upside-down balance", "Gymnast's feet-in-the-air pose"],
  ["HAPPINESS", "Pure joy", "What this paper hopes to spread"],
  ["HARMONICA", "Mouth organ", "Blues player's pocket instrument"],
  ["HIBERNATE", "Sleep all winter", "What a dormouse does till spring"],
  ["HOMEGROWN", "From your own garden", "Local, like talent"],
  ["HOPSCOTCH", "Chalk-and-stone playground game", "Hop, skip and land in the squares"],
  ["HOURGLASS", "Sand timer", "Egg timer's grown-up cousin"],
  // I
  ["IMAGINARY", "Made-up", "Like a friend only you can see"],
  ["INVENTION", "Clever new creation", "Gadget from a boffin's shed"],
  // J
  ["JELLYBEAN", "Chewy sweet in every colour", "Bean you'd find in a sweet jar"],
  ["JELLYFISH", "Wobbly swimmer in the sea", "See-through sea drifter"],
  // L
  ["LABYRINTH", "Maze", "Puzzling network of paths"],
  ["LAMPLIGHT", "Glow from a lantern", "Soft light for reading"],
  ["LANDSCAPE", "Wide view of the countryside", "Picture that's wider than tall"],
  ["LIGHTNING", "Flash in a thunderstorm", "Bolt from the blue"],
  ["LIMOUSINE", "Stretchy posh car", "Chauffeur's long motor"],
  ["LIQUORICE", "Black chewy sweet", "Allsorts ingredient"],
  // M
  ["MARMALADE", "Orange spread on toast", "Paddington's favourite sandwich filling"],
  ["MEGAPHONE", "Cone for shouting through", "Loudhailer"],
  ["MERRIMENT", "Jolly fun", "Laughter and good cheer"],
  ["MIDSUMMER", "Around the longest day", "Shakespeare's night of dreams"],
  ["MILKSHAKE", "Thick drink with a straw", "Frothy strawberry treat"],
  ["MOONLIGHT", "Silvery night-time glow", "Light from the man in the moon"],
  // N
  ["NAVIGATOR", "Map reader on a voyage", "Person who says 'left here!'"],
  ["NECTARINE", "Smooth-skinned peach", "Juicy stone fruit"],
  ["NEWSPAPER", "What you're holding now", "Daily read with a crossword"],
  ["NIGHTFALL", "When darkness comes", "Dusk"],
  // O
  ["ORCHESTRA", "Big band of violins and brass", "Group led by a conductor"],
  ["OVERJOYED", "Over the moon", "Happy as can be"],
  // P
  ["PANTOMIME", "Christmas show with a dame", "Oh no it isn't! Oh yes it is!"],
  ["PAPERBACK", "Book with a bendy cover", "Holiday read"],
  ["PARACHUTE", "Skydiver's silk canopy", "Playground game with a giant rainbow sheet"],
  ["PARTRIDGE", "Bird in a pear tree", "Plump game bird"],
  ["PASSENGER", "Traveller on a bus", "Rider who isn't driving"],
  ["PATCHWORK", "Quilt made of scraps", "Colourful sewing of squares"],
  ["PEPPERONI", "Spicy sausage on a pizza", "Popular pizza topping"],
  ["PERFORMER", "Entertainer on stage", "Singer, dancer or juggler"],
  ["PERISCOPE", "Submarine's peeping tube", "Mirror tube for looking over walls"],
  ["PINEAPPLE", "Spiky tropical fruit", "Fruit with a leafy crown"],
  ["PLAYHOUSE", "Wendy house", "Theatre, or a den in the garden"],
  ["PORCUPINE", "Rodent with quills", "Prickly forest dweller"],
  ["PUPPETEER", "String puller at a Punch and Judy show", "Person working the marionettes"],
  // Q
  ["QUICKSTEP", "Speedy ballroom dance", "Brisk dance on Strictly"],
  // R
  ["RASPBERRY", "Red summer fruit", "Rude noise made with the lips"],
  ["RIVERBANK", "Where Ratty and Mole messed about in boats", "Side of the stream"],
  // S
  ["SANDPAPER", "Gritty sheet for smoothing wood", "Rough stuff in the toolbox"],
  ["SATELLITE", "Moon, for instance", "Orbiting dish in space"],
  ["SAXOPHONE", "Curvy jazz instrument", "Brass-looking woodwind"],
  ["SCARECROW", "Straw man in the field", "Crow's worst nightmare in a hat"],
  ["SCRAPBOOK", "Album of cuttings and tickets", "Book of keepsakes"],
  ["SEVENTEEN", "Ten plus seven", "Number of syllables in a haiku"],
  ["SHIPSHAPE", "Neat and tidy", "In apple-pie order"],
  ["SIGHTSEER", "Tourist with a camera", "Visitor ticking off the landmarks"],
  ["SNOWFLAKE", "Six-sided winter crystal", "No two are alike, they say"],
  ["SPAGHETTI", "Long pasta", "Stringy dish with meatballs"],
  ["SPARKLING", "Fizzy, as water", "Glittering"],
  ["SPECTACLE", "Grand show", "Quite a sight"],
  ["SPEEDBOAT", "Zippy motor on the lake", "Fast vessel with a big wake"],
  ["SPRINKLES", "Hundreds and thousands", "Colourful cake topping"],
  ["STAIRCASE", "Flight of steps", "The way up to bed"],
  ["STARGAZER", "Night-sky watcher", "Amateur astronomer"],
  ["STARLIGHT", "Twinkle from far away", "Glow from the heavens"],
  ["STEAMBOAT", "Paddle vessel on the Mississippi", "Boat powered by a boiler"],
  ["STOPWATCH", "Timer for a race", "Coach's ticking gadget"],
  ["STORYBOOK", "Book of tales at bedtime", "Like a happy ending"],
  ["SUNFLOWER", "Tall yellow bloom that follows the sun", "Flower whose seeds birds love"],
  ["SUNSCREEN", "Lotion for the beach", "Protection factor in a bottle"],
  ["SUPERSTAR", "Very famous performer", "Absolute legend"],
  ["SWEETCORN", "Yellow kernels on the cob", "Veg with butter at a barbecue"],
  // T
  ["TELEPHONE", "Thing that rings", "Invention of Alexander Graham Bell"],
  ["TELESCOPE", "Stargazer's tube", "Spyglass"],
  ["THRILLING", "Edge-of-your-seat exciting", "Hair-raisingly fun"],
  ["TIMETABLE", "List of when the trains run", "School lesson planner"],
  ["TRAVELLER", "Globetrotter", "Person with a suitcase"],
  ["TREEHOUSE", "Den up in the branches", "Hideout reached by rope ladder"],
  ["TRUMPETER", "Brass player in a band", "Swan named for its call"],
  ["TURQUOISE", "Blue-green gemstone", "Colour of a tropical sea"],
  // V
  ["VEGETABLE", "Carrot or cabbage", "One of your five a day"],
  ["VOLUNTEER", "Helper who isn't paid", "Put your hand up for the job"],
  // W
  ["WALLPAPER", "Patterned covering for walls", "Background picture on your screen"],
  ["WATERFALL", "Cascade down a cliff", "Niagara, for one"],
  ["WATERMILL", "Wheel-turning building by a river", "Old flour maker powered by a stream"],
  ["WHIRLWIND", "Spinning gust", "Romance that happens very fast"],
  ["WONDERFUL", "Marvellous", "Simply lovely"],
  ["WORDSMITH", "Clever writer", "Person handy with language"],
  ["WORKBENCH", "Table in the shed for projects", "Woodworker's sturdy surface"],
  // X, Y, Z
  ["XYLOPHONE", "Instrument played with little hammers", "X is for this, in many alphabet books"],
  ["YESTERDAY", "The day before today", "Beatles song about the past"],
  ["YOUNGSTER", "Little one", "Kid"],
  ["ZOOKEEPER", "Person who feeds the penguins", "Animal carer at the zoo"],
];
