import type { Clued } from "./types.ts";

/** Three-letter crossword answers, each with one or more clues. */
export const THREE_LETTER_WORDS: readonly Clued[] = [
  // A
  ["ACE", "Top card in the pack", "Serve your opponent can't touch"],
  ["ACT", "Play a part on stage", "One chunk of a play"],
  ["ADD", "Put together, like two and two", "Toss in one more"],
  ["ADO", "Much ___ About Nothing"],
  ["AGE", "It goes up by one every birthday"],
  ["AGO", "In the past, as in 'long ___'"],
  ["AID", "Help in a tricky moment", "Lend a hand"],
  ["AIM", "Point at the target", "Goal you're shooting for"],
  ["AIR", "What balloons are full of", "Tune you might whistle"],
  ["ALL", "Every single one", "___ aboard!"],
  ["AND", "Word that joins fish to chips"],
  ["ANT", "Tiny worker that lifts far more than its weight", "Picnic's uninvited guest"],
  ["ANY", "Is there ___ cake left?"],
  ["APE", "Gorilla or chimp", "Copy someone's moves"],
  ["APP", "Program on your phone"],
  ["APT", "Just right for the moment", "Fitting"],
  ["ARC", "A rainbow's shape", "Curve traced by a thrown ball"],
  ["ARE", "We ___ the champions!"],
  ["ART", "What galleries hang on their walls", "Painting and drawing, at school"],
  ["ASH", "Tree whose seeds are called keys", "Grey dust left in the grate"],
  ["ASK", "Put a question", "Politely request"],
  ["ATE", "Had lunch, say", "Wolfed down"],
  ["AWE", "Wide-eyed wonder", "Jaw-dropping feeling"],
  // B
  ["BAA", "A lamb's one-word speech", "Sheep's bleat"],
  ["BAG", "Carrier for the shopping", "School ___"],
  ["BAT", "Cricket essential", "Winged flyer that hangs upside down"],
  ["BAY", "Curved bit of coastline", "Horse of a reddish-brown colour"],
  ["BED", "Where dreams happen", "Flower ___ in the garden"],
  ["BEE", "Buzzy maker of honey", "Spelling ___"],
  ["BIB", "Baby's mealtime napkin", "Messy eater's cover-up"],
  ["BID", "Offer at an auction", "Try, as in make a ___ for it"],
  ["BIG", "Opposite of small", "Like an elephant's ears"],
  ["BIN", "Where the rubbish goes"],
  ["BIT", "A small piece", "Just a ___ nippy out today"],
  ["BOA", "Feathery scarf, or a big snake"],
  ["BOB", "Bounce about on the waves", "Short, neat haircut"],
  ["BOG", "Squelchy patch of wetland", "Peaty marsh"],
  ["BOW", "Take one when the audience claps", "Ribbon tied on a present"],
  ["BOX", "Where a present waits to be opened", "A cat's favourite cardboard home"],
  ["BOY", "Young lad", "Son, perhaps"],
  ["BUD", "Flower that hasn't opened yet", "Chum, in America"],
  ["BUG", "Beetle or ladybird, loosely", "Glitch in the code"],
  ["BUN", "Sticky iced treat", "Hair piled up on top"],
  ["BUS", "Double-decker, for one", "School ___"],
  ["BUY", "Pay for at the shop", "Snap up a bargain"],
  ["BYE", "Cheerio!", "See you later!"],
  // C
  ["CAB", "Black taxi", "Front bit of a lorry"],
  ["CAN", "Tin of beans", "Yes, you ___!"],
  ["CAP", "Peaked hat", "Top on a bottle"],
  ["CAR", "Four wheels and a boot", "Something to wash on Sunday"],
  ["CAT", "Purring pet", "It may land on its feet"],
  ["COB", "Corn on the ___", "Male swan"],
  ["COD", "Fish from the chippy", "Fish in fish fingers"],
  ["COG", "Toothed wheel in a clock", "Small part of a big machine"],
  ["COT", "Baby's bed with bars", "Where a baby naps"],
  ["COW", "Moo-maker in the meadow", "Mother of a calf"],
  ["CUB", "Young bear or lion", "Junior Scout"],
  ["CUE", "Signal for an actor to speak", "Snooker stick"],
  ["CUP", "Mug's cousin", "Trophy for the winners"],
  // D
  ["DAB", "Tiny touch of paint", "Small flat fish"],
  ["DAD", "Pa", "He tells the worst jokes, lovingly"],
  ["DAM", "Beaver's building project", "Wall that holds back a river"],
  ["DAY", "Sunrise to sunset", "Have a nice ___!"],
  ["DEN", "Cosy hideout", "Fox's home"],
  ["DEW", "Morning droplets on the grass", "Sparkle on a spider's web at dawn"],
  ["DIG", "Use a spade", "What a dog does for buried treasure"],
  ["DIM", "Not very bright, like a lamp", "Turn down the lights"],
  ["DIP", "Quick swim", "Salsa, to a crisp"],
  ["DOE", "Female deer", "___, a deer, a female deer"],
  ["DOG", "Tail-wagging best friend"],
  ["DOT", "Tiny spot", "Join the ___s puzzle"],
  ["DRY", "Not wet", "Like a desert"],
  ["DUE", "Expected, like a library book", "Owed"],
  ["DUG", "Used a spade", "Burrowed"],
  ["DUO", "Double act", "Batman and Robin, say"],
  ["DYE", "Colour a T-shirt", "Change the colour of your hair"],
  // E
  ["EAR", "Listener on the side of your head", "___ of corn"],
  ["EAT", "Tuck in", "Have your dinner"],
  ["EBB", "What the tide does as it goes out", "Fade away"],
  ["EEL", "Long, wriggly swimmer", "Slippery fish shaped like a snake"],
  ["EGG", "Boiled breakfast with soldiers", "Easter chocolate shape"],
  ["ELF", "Santa's little helper", "Pointy-eared helper in a story"],
  ["ELK", "Big deer with broad antlers", "Moose, in Europe"],
  ["ELM", "Tall, shady tree", "Tree with rough, toothy leaves"],
  ["EMU", "Big Australian bird that can't fly", "Bird that runs but can't fly"],
  ["END", "Finish", "The last word of a fairy tale"],
  ["ERA", "Period of history", "Age, as in the Victorian ___"],
  ["EWE", "Mother sheep", "Lamb's mum"],
  ["EYE", "What you see with", "Hole in a needle"],
  // F
  ["FAB", "Fantastic, in short", "Brilliant!"],
  ["FAD", "Craze that doesn't last", "Short-lived craze"],
  ["FAN", "It keeps you cool", "Supporter in the stands"],
  ["FAR", "A long way off", "Distant"],
  ["FED", "Gave dinner to", "Gave the ducks some bread"],
  ["FEE", "Charge for a service", "Price for a service"],
  ["FEW", "Not many", "A handful"],
  ["FIG", "Sweet fruit full of tiny seeds", "Fruit often dried"],
  ["FIN", "Fish's flap", "Dolphin's steering flap"],
  ["FIR", "Evergreen tree with needles", "Tree with cones"],
  ["FIT", "In great shape", "The right size"],
  ["FIX", "Mend", "Repair"],
  ["FLY", "Soar like a bird", "Buzzing insect at the window"],
  ["FOG", "Thick mist", "Weather that hides the view"],
  ["FOR", "Made ___ each other", "In favour of"],
  ["FOX", "Bushy-tailed wild dog", "Cunning creature in fables"],
  ["FRY", "Cook in a pan", "Small fish"],
  ["FUN", "A good time", "A jolly good time"],
  ["FUR", "A cat's coat", "Hair on a teddy bear"],
  // G
  ["GAP", "Space between", "Mind the ___!"],
  ["GEL", "Hair goo", "Set, like a jelly"],
  ["GEM", "Sparkling jewel", "Real treasure of a person"],
  ["GET", "Receive", "Understand, as a joke"],
  ["GNU", "Wildebeest by another name", "Horned antelope of Africa"],
  ["GOO", "Sticky, gloopy stuff", "Gloopy slime"],
  ["GOT", "Received", "Fetched"],
  ["GUM", "Chewy sweet", "Sticky tree sap"],
  ["GUY", "Fellow", "Bloke"],
  ["GYM", "Place for a workout", "PE lesson venue"],
  // H
  ["HAD", "Owned, once", "Owned in the past"],
  ["HAM", "Sandwich filling", "Over-the-top actor"],
  ["HAS", "Owns", "Holds"],
  ["HAT", "Topper or bobble, say", "Bowler or beanie"],
  ["HAY", "Dried grass for horses", "Horse's dinner"],
  ["HEM", "Bottom edge of a skirt", "Sew up the edge"],
  ["HEN", "Egg-laying bird", "Mother chicken"],
  ["HER", "Not him", "That woman"],
  ["HID", "Kept out of sight", "Tucked away, like a squirrel's nuts"],
  ["HIM", "Not her", "That man"],
  ["HIP", "Joint you shake when you dance", "Trendy"],
  ["HIS", "Belonging to him", "Not hers"],
  ["HOG", "Keep all to yourself", "Big pig"],
  ["HOP", "A bunny's move", "Jump on one foot"],
  ["HOT", "Like a summer's day", "Spicy"],
  ["HOW", "___ are you?", "In what way?"],
  ["HUB", "Centre of a wheel", "Busy centre"],
  ["HUE", "Shade of colour", "Tint"],
  ["HUG", "Warm squeeze", "Cuddle"],
  ["HUM", "Sing with your lips closed", "Buzz like a bee"],
  ["HUT", "Small shelter", "Beach cabin"],
  // I
  ["ICE", "Frozen water", "Decorate a cake"],
  ["ICY", "Frosty", "Slippery with frost"],
  ["INK", "A pen's filling", "Octopus's cloud"],
  ["INN", "Cosy old place to stay the night"],
  ["ION", "Charged particle", "Particle with a charge"],
  ["IVY", "Climbing plant on old walls", "Holly's Christmas partner"],
  // J
  ["JAM", "Strawberry spread", "Traffic ___"],
  ["JAR", "Glass pot with a screw lid", "Home for pickles"],
  ["JAY", "Colourful bird of the crow family", "Bird with bright blue wing flashes"],
  ["JET", "Very fast plane", "Stream of water from a hose"],
  ["JIG", "Lively Irish dance", "Jolly dance"],
  ["JOB", "Work", "Good ___!"],
  ["JOG", "Gentle run", "Nudge a memory"],
  ["JOT", "Scribble down", "Tiny bit, as in not one ___"],
  ["JOY", "Great happiness", "Delight"],
  ["JUG", "Pourer for milk", "Water ___ on the table"],
  // K
  ["KEY", "It opens a lock", "One of 88 on a piano"],
  ["KID", "Child", "Young goat"],
  ["KIN", "Family", "Relatives"],
  ["KIT", "Football strip", "Set of tools"],
  // L
  ["LAB", "Science room", "Friendly dog, for short"],
  ["LAD", "Young fellow", "Boy"],
  ["LAG", "Fall behind", "Slow down behind"],
  ["LAP", "One trip round the track", "Where a cat curls up"],
  ["LED", "Went first", "Guided"],
  ["LEG", "Limb for walking", "Stage of a journey"],
  ["LEI", "Hawaiian flower necklace", "Garland for your neck"],
  ["LET", "Allow", "Rent out"],
  ["LID", "Top of a jar", "Saucepan top"],
  ["LIP", "Edge of a cup"],
  ["LIT", "Switched on, like a lamp", "Glowing, like a candle"],
  ["LOB", "High, gentle throw", "High tennis shot"],
  ["LOG", "Chunk of firewood", "Ship's diary"],
  ["LOT", "A great deal", "Plenty"],
  ["LOW", "Not high", "What a cow says, poetically"],
  // M
  ["MAN", "Gent", "Draughts piece"],
  ["MAP", "Guide for explorers", "Atlas page"],
  ["MAT", "Wipe your feet on it", "Yoga ___"],
  ["MAY", "Month of blossom", "___ I help you?"],
  ["MEN", "Gents", "Chaps"],
  ["MET", "Came across", "Bumped into"],
  ["MIX", "Stir together", "Blend"],
  ["MOO", "Cow's comment", "Farmyard call"],
  ["MOP", "Floor cleaner", "Mass of hair"],
  ["MOW", "Cut the lawn", "Trim the grass"],
  ["MUD", "Wet earth a pig loves", "Squelchy stuff after rain"],
  ["MUG", "Big cup for cocoa", "Tea holder"],
  ["MUM", "Ma", "Keep ___ (say nothing)"],
  // N
  ["NAN", "Granny", "Grandma"],
  ["NAP", "Short sleep", "Forty winks"],
  ["NET", "Back of the goal", "Butterfly catcher"],
  ["NEW", "Just made", "Brand ___"],
  ["NIB", "Point of a fountain pen", "Tip of a pen"],
  ["NOD", "Yes, without words", "Bob your head"],
  ["NOR", "Neither here ___ there"],
  ["NOT", "Word that turns yes to no", "By no means"],
  ["NOW", "At this moment", "Right ___!"],
  ["NUT", "Squirrel's snack", "Bolt's partner"],
  // O
  ["OAK", "Tree that grows from an acorn", "Mighty tree"],
  ["OAR", "Rowing paddle", "Blade for a rowing boat"],
  ["OAT", "Porridge grain", "Flapjack grain"],
  ["ODD", "Unusual", "Like 3, 5 or 7"],
  ["ODE", "Poem of praise", "Keats wrote one to a nightingale"],
  ["OFF", "Not on", "Switched ___"],
  ["OIL", "Olive product", "Squirt it on a squeaky hinge"],
  ["OLD", "Not new", "Like a treasured teddy"],
  ["ONE", "Single", "Hole in ___"],
  ["OPT", "Choose", "Pick"],
  ["ORB", "Glowing sphere", "Ball"],
  ["ORE", "Rock dug up for its metal", "Raw metal rock"],
  ["OUR", "Belonging to us", "Not their"],
  ["OUT", "Not in", "Away"],
  ["OWL", "Wise bird that works the night shift", "Hooter in the woods"],
  ["OWN", "Possess", "On your ___"],
  // P
  ["PAD", "Notebook for scribbles", "Lily ___"],
  ["PAL", "Friend", "Buddy"],
  ["PAN", "Frying ___", "Camera move from side to side"],
  ["PAT", "Gentle tap", "Stroke gently, like a puppy"],
  ["PAW", "Dog's foot", "Cat's foot"],
  ["PAY", "Hand over money", "Wages"],
  ["PEA", "Green veg in a pod", "The princess felt it under twenty mattresses"],
  ["PEG", "Clothes-line clip", "Tent anchor"],
  ["PEN", "Writer's tool", "Where sheep are kept"],
  ["PEP", "Energy and zip", "Get-up-and-go"],
  ["PET", "Cat, dog or hamster at home", "Animal friend at home"],
  ["PIE", "Pastry dish", "Easy as ___"],
  ["PIG", "Oinker in the sty", "Pink farm animal"],
  ["PIN", "Sharp little fastener", "Drawing ___"],
  ["PIP", "Apple seed", "Orange seed"],
  ["PIT", "Hole in the ground", "Cherry stone"],
  ["PLY", "Layer of wood or wool", "Strand of yarn"],
  ["POD", "A pea's home", "Seed case"],
  ["POP", "A bubble's last sound", "Fizzy drink"],
  ["PRO", "Expert", "Top player who gets paid"],
  ["PRY", "Nose around", "Snoop"],
  ["PUG", "Squashed-nose dog", "Small, wrinkly dog"],
  ["PUN", "Wordplay joke", "Joke with wordplay"],
  ["PUP", "Young dog or seal"],
  ["PUT", "Place", "Set down"],
  // R
  ["RAG", "Cleaning cloth", "Old cloth"],
  ["RAM", "Male sheep", "Male sheep with curly horns"],
  ["RAN", "Sprinted", "Dashed"],
  ["RAT", "Rodent with a long tail", "Clever rodent"],
  ["RAY", "Beam of sunshine", "Flat fish with wings"],
  ["RED", "Colour of strawberries", "Colour of a ladybird"],
  ["RIB", "Tease gently"],
  ["RID", "Get ___ of"],
  ["RIM", "Edge of a cup"],
  ["ROD", "Fishing ___"],
  ["ROE", "Fish eggs"],
  ["ROW", "Line of seats", "Pull the oars"],
  ["RUB", "Massage"],
  ["RUG", "Floor covering"],
  ["RUN", "Sprint", "Cricket score"],
  ["RYE", "Grain for dark bread"],
  // S
  ["SAG", "Droop"],
  ["SAP", "Tree's sticky juice"],
  ["SAT", "Took a seat"],
  ["SAW", "Carpenter's toothy tool", "Spotted"],
  ["SAX", "Jazzy horn, for short"],
  ["SAY", "Speak"],
  ["SEA", "Salty water"],
  ["SEE", "Spot"],
  ["SET", "Ready, ___, go!", "Collection of matching things"],
  ["SEW", "Stitch"],
  ["SHE", "Her, as a subject"],
  ["SHY", "Bashful"],
  ["SIP", "Tiny drink"],
  ["SIR", "Title for a knight"],
  ["SIT", "Take a seat", "Command for a puppy"],
  ["SIX", "Half a dozen"],
  ["SKI", "Glide down the slopes"],
  ["SKY", "The blue up above"],
  ["SLY", "Crafty"],
  ["SOW", "Plant seeds", "Mother pig"],
  ["SOY", "___ sauce"],
  ["SPA", "Place to relax and unwind"],
  ["SUB", "Replacement player"],
  ["SUM", "Maths problem"],
  ["SUN", "Star at the centre of our system"],
  // T
  ["TAB", "Browser ___", "Little label to pull"],
  ["TAG", "Playground chase game", "Price label"],
  ["TAN", "Light brown"],
  ["TAP", "Where water comes from at the sink"],
  ["TAR", "Black road goo"],
  ["TEA", "Cuppa", "Afternoon ___"],
  ["TEE", "Golf peg"],
  ["TEN", "Number of fingers"],
  ["TIE", "Knot at the collar", "Draw"],
  ["TIN", "Can of beans"],
  ["TIP", "Handy bit of advice", "Pointy end"],
  ["TOE", "This little piggy went to market"],
  ["TON", "Very heavy weight", "A hundred, in cricket"],
  ["TOO", "Also"],
  ["TOP", "Spinning toy", "Summit"],
  ["TOT", "Toddler"],
  ["TOW", "Pull along"],
  ["TOY", "Plaything"],
  ["TRY", "Attempt", "Rugby score"],
  ["TUB", "Bath"],
  ["TUG", "Pull hard", "Little boat that pulls big ships"],
  ["TWO", "A pair"],
  // U
  ["USE", "Put to work"],
  // V
  ["VAN", "Delivery vehicle"],
  ["VAT", "Big tank"],
  ["VET", "Animal doctor"],
  ["VIA", "By way of"],
  ["VIE", "Compete"],
  ["VOW", "Promise"],
  // W
  ["WAD", "Thick bundle of paper"],
  ["WAG", "What a happy dog's tail does", "Joker"],
  ["WAX", "Candle stuff"],
  ["WAY", "Path"],
  ["WEB", "Spider's home"],
  ["WED", "Marry"],
  ["WET", "Soaked"],
  ["WHO", "___ goes there?"],
  ["WHY", "Question word"],
  ["WIG", "Fake hair"],
  ["WIN", "Come first"],
  ["WIT", "Cleverness"],
  ["WOK", "Stir-fry pan"],
  ["WON", "Came first"],
  ["WOO", "Court"],
  ["WOW", "Amazing!"],
  ["WRY", "Dry and amused"],
  // Y
  ["YAK", "Long-haired ox"],
  ["YAM", "Sweet potato's cousin"],
  ["YAP", "Little dog's bark"],
  ["YAY", "Hooray!"],
  ["YES", "Opposite of no"],
  ["YET", "So far"],
  ["YEW", "Evergreen tree"],
  ["YOU", "Not me"],
  // Z
  ["ZAG", "Zig's partner"],
  ["ZAP", "Quick jolt"],
  ["ZIP", "Fastener"],
  ["ZOO", "Animal park"],
];

/** Four-letter crossword answers, each with one or more clues. */
export const FOUR_LETTER_WORDS: readonly Clued[] = [
  // A
  ["ABLE", "Up to the job", "Willing and ___"],
  ["ACRE", "Roughly a football pitch of farmland"],
  ["AFAR", "From a long way off"],
  ["AJAR", "Open just a crack", "When is a door not a door? When it's this!"],
  ["AKIN", "Similar, like two peas in a pod"],
  ["ALSO", "Too", "As well"],
  ["ALTO", "Singing voice just above tenor"],
  ["APEX", "The very tip-top"],
  ["ARCH", "Curved doorway", "The bendy bit under your foot"],
  ["AREA", "Length times width", "Neck of the woods"],
  ["ATOM", "Tiny building block of everything", "Smallest bit of an element"],
  ["AUNT", "Mum or Dad's sister", "She might send the best birthday cards"],
  ["AURA", "Special glow around someone"],
  ["AWAY", "Not at home", "Far, far ___"],
  ["AXIS", "Line the Earth spins around"],
  ["AXLE", "Rod that joins two wheels"],
  // B
  ["BABY", "Newest member of the family", "Little one in a pram"],
  ["BACK", "Opposite of front", "Be right ___!"],
  ["BAKE", "Make a cake in the oven", "Great British ___ Off"],
  ["BALL", "Round thing to kick or bounce", "Cinderella's big night out"],
  ["BAND", "Group that plays together", "Hair ___ for a ponytail"],
  ["BANK", "Grassy edge of a river", "Piggy ___"],
  ["BARK", "A dog's woof", "A tree's rough coat"],
  ["BARN", "Farm building full of hay"],
  ["BATH", "Bubbly soak with a rubber duck", "Tub full of bubbles"],
  ["BEAD", "Tiny ball threaded on a necklace"],
  ["BEAK", "Bird's pointy mouth"],
  ["BEAM", "Smile from ear to ear", "Ray of light"],
  ["BEAN", "Jelly ___", "Baked one on toast"],
  ["BEAR", "Teddy, for one", "Paddington, for one"],
  ["BEEP", "Sound of a car horn or a microwave"],
  ["BELL", "It rings for the end of school", "Ding-dong maker"],
  ["BELT", "Strap that holds your trousers up"],
  ["BEND", "Curve in the road", "What a gymnast does with ease"],
  ["BEST", "Tip-top", "Friend number one"],
  ["BIKE", "Two wheels and a bell", "Pedal-pusher's ride"],
  ["BIRD", "Robin or wren", "Early one that catches the worm"],
  ["BLUE", "Colour of a clear sky", "Colour of a robin's egg"],
  ["BOAT", "It floats with you inside", "Row, row, row your ___"],
  ["BOLD", "Brave and daring", "Thick, dark type"],
  ["BONE", "A dog's favourite buried treasure", "Your skeleton has over 200"],
  ["BOOK", "What a library lends", "Reserve a table"],
  ["BOOT", "Wellie, for one", "Where the car's luggage goes"],
  ["BORN", "Came into the world"],
  ["BOTH", "The pair of them"],
  ["BOWL", "What cereal goes in", "Send a cricket ball down"],
  ["BUSH", "Shrub in the garden", "Rose ___"],
  ["BUSY", "Buzzing about, like a bee"],
  ["BUZZ", "Sound of a busy bee", "Excited hum in the room"],
  // C
  ["CAFE", "Place for a cuppa and a cake"],
  ["CAGE", "Home for a hamster"],
  ["CAKE", "Candles go on top of it", "A piece of ___ (very easy)"],
  ["CALF", "Baby cow", "Back of your lower leg"],
  ["CALM", "Peaceful, like a still lake", "Keep ___ and carry on"],
  ["CAMP", "Pitch your tents here", "Summer ___"],
  ["CANE", "Sugar ___", "Candy ___ on the tree"],
  ["CAPE", "Superhero's flowing cloak"],
  ["CARD", "Birthday greeting in an envelope", "Ace or king"],
  ["CARE", "Look after", "Take ___!"],
  ["CART", "Horse-drawn wagon"],
  ["CASE", "Luggage for a holiday", "Puzzle for a detective"],
  ["CAVE", "Rocky hollow for bats", "Where bats hang out"],
  ["CHAT", "Friendly natter"],
  ["CHEF", "Head cook in a kitchen", "Hat-wearing kitchen boss"],
  ["CHIN", "It's under your mouth", "Keep your ___ up!"],
  ["CHIP", "Hot potato stick", "Tiny brain of a computer"],
  ["CITY", "Big place with tall buildings", "Busy metropolis"],
  ["CLAP", "What an audience does at the end", "Thunder's loud bang"],
  ["CLAW", "A crab's pincher"],
  ["CLAY", "Squishy stuff for a potter's wheel", "Stuff for making pots"],
  ["CLUE", "Hint, like this one!", "What a detective hunts for"],
  ["COAT", "Winter warmer with buttons", "Layer of paint"],
  ["CODE", "Secret message", "What programmers write"],
  ["COIN", "Pound or penny", "Heads or tails?"],
  ["COLD", "Chilly", "Like an ice lolly"],
  ["COMB", "Tidier with teeth", "Honey___"],
  ["CONE", "Crunchy holder for ice cream"],
  ["COOK", "Make the dinner"],
  ["COOL", "Nicely chilly", "Awesome!"],
  ["COPY", "Do exactly the same", "Duplicate"],
  ["CORD", "Thin rope", "Dressing gown tie"],
  ["CORN", "Maize", "Pop___ at the pictures"],
  ["COSY", "Snug by the fire", "Knitted cover for a teapot"],
  ["CRAB", "Beach walker that goes sideways", "Pincers on the rock pool"],
  ["CREW", "Team that sails a ship", "Rowing team"],
  ["CROW", "Big black bird", "What a cockerel does at dawn"],
  ["CUBE", "Shape of a sugar lump", "Ice ___"],
  ["CURL", "Spiral of hair", "Snuggle up in a ball"],
  ["CUTE", "Adorable, like a kitten"],
  // D
  ["DAMP", "Slightly soggy"],
  ["DARE", "Truth or ___?"],
  ["DARK", "When the stars come out", "Pitch black"],
  ["DART", "Dash like a minnow", "Arrow thrown at a board"],
  ["DASH", "Quick run", "Little line in Morse code"],
  ["DATE", "Day on the calendar", "Sticky brown fruit"],
  ["DAWN", "Sunrise", "Crack of ___"],
  ["DEAR", "Letter opener?", "Much loved"],
  ["DECK", "Floor of a ship", "Pack of cards"],
  ["DEEP", "Like the bottom of the ocean", "Like a thoughtful question"],
  ["DEER", "Bambi, for one"],
  ["DESK", "Where homework gets done", "Office table"],
  ["DIAL", "Face of a clock", "Turn this to tune the radio"],
  ["DISH", "Plate for dinner", "The ___ ran away with the spoon"],
  ["DIVE", "Plunge into the pool"],
  ["DOCK", "Where boats tie up"],
  ["DOLL", "Toy with a wardrobe of tiny clothes", "Rag ___"],
  ["DOME", "Round roof like half a ball"],
  ["DOOR", "Knock on it", "Front ___"],
  ["DOVE", "White bird of peace"],
  ["DOWN", "Opposite of up", "Soft fluffy feathers"],
  ["DOZE", "Nod off for a bit"],
  ["DRAW", "Sketch with a pencil", "Match that ends level"],
  ["DRUM", "Bang it to keep the beat", "Beat it with sticks"],
  ["DUCK", "Quacker on the pond", "Nought, in cricket"],
  ["DUET", "Song for two voices"],
  ["DUNE", "Hill of sand"],
  ["DUSK", "When the day turns to evening"],
  ["DUST", "Fluff on the shelves", "Wipe the shelves"],
  // E
  ["EACH", "Every single one"],
  ["EARN", "Get paid for work"],
  ["EASE", "Comfort", "Do it with ___"],
  ["EAST", "Where the sun comes up", "Opposite of west"],
  ["EASY", "Simple as ABC", "Take it ___"],
  ["ECHO", "Your voice coming back from a cave", "Repeat after me, repeat after me"],
  ["EDGE", "Rim of a cliff", "Crust's spot on a pizza"],
  ["EPIC", "Grand, heroic story"],
  ["EVEN", "Like 2, 4 or 6", "Flat and level"],
  ["EXIT", "Way out"],
  // F
  ["FACE", "Front of a clock", "Make a funny one"],
  ["FACT", "Something that's true"],
  ["FAIR", "Just and square", "Fun___ with rides"],
  ["FALL", "Take a tumble", "Autumn, across the Atlantic"],
  ["FARM", "Home of cows and tractors", "Place with a tractor and a barn"],
  ["FAST", "Speedy", "Quick as a flash"],
  ["FAWN", "Baby deer"],
  ["FEAT", "Great achievement"],
  ["FEED", "Give dinner to", "Fill the bird table"],
  ["FERN", "Feathery green plant"],
  ["FILM", "Movie at the cinema", "Picture show"],
  ["FIND", "Discover", "Lucky thing to stumble upon"],
  ["FISH", "Salmon or trout", "Try to catch with a rod"],
  ["FIVE", "Fingers on one hand", "High ___!"],
  ["FIZZ", "Bubbles in lemonade"],
  ["FLAG", "Banner that flies on a pole", "Wave it at the finish line"],
  ["FLAT", "Level, like a pancake", "Home on one floor"],
  ["FLIP", "Toss a pancake", "Somersault"],
  ["FLOW", "What a river does"],
  ["FOAL", "Baby horse"],
  ["FOAM", "Bubbles on a hot chocolate"],
  ["FOLD", "Crease in a paper plane"],
  ["FOOD", "Grub", "Picnic contents"],
  ["FOOT", "Sock filler", "Twelve inches"],
  ["FORK", "Knife's partner at dinner", "Split in the road"],
  ["FOUR", "Legs on a table"],
  ["FROG", "Green hopper in the pond", "Tadpole, grown up"],
  ["FUZZ", "Soft fluff on a peach"],
  // G
  ["GALE", "Very strong wind"],
  ["GAME", "Snakes and ladders, say", "Up for anything"],
  ["GATE", "Garden entrance", "Where you board at the airport"],
  ["GIFT", "Present with a bow", "Natural talent"],
  ["GIRL", "Young lass"],
  ["GLAD", "Happy", "So ___ you came!"],
  ["GLEE", "Delight"],
  ["GLOW", "Gentle shine", "What a firefly does"],
  ["GLUE", "Sticky stuff for crafts", "Stick it together"],
  ["GOAL", "Back of the net!", "Something to aim for"],
  ["GOAT", "Billy or nanny on the farm", "Nimble climber with a beard"],
  ["GOLD", "Winner's medal", "Treasure at the rainbow's end"],
  ["GOLF", "Game with tees and holes", "Crazy ___ at the seaside"],
  ["GOOD", "Well done!", "As ___ as gold"],
  ["GOWN", "Long, fancy dress"],
  ["GRIN", "Big happy smile", "Cheshire cat's speciality"],
  ["GROW", "Get bigger", "What seeds do in spring"],
  ["GULL", "Seaside bird after your chips"],
  ["GUST", "Sudden blast of wind"],
  // H
  ["HAIL", "Icy little balls from the sky"],
  ["HAIR", "What a barber cuts", "Something to brush every morning"],
  ["HALF", "Fifty per cent", "Second ___ of the match"],
  ["HALL", "Big room for assembly"],
  ["HAND", "It has four fingers and a thumb", "Give me a ___!"],
  ["HARE", "Tortoise's speedy rival"],
  ["HARP", "Big stringed instrument you pluck"],
  ["HAWK", "Sharp-eyed bird of prey"],
  ["HEAD", "Where your hat goes", "Captain of the school"],
  ["HEAP", "Big messy pile"],
  ["HEAT", "Warmth", "Early round of a race"],
  ["HELP", "Lend a hand", "Assist"],
  ["HERB", "Basil or parsley"],
  ["HERD", "Group of cows"],
  ["HERO", "Champion who saves the day", "Brave one in the story"],
  ["HIDE", "Tuck out of sight"],
  ["HIKE", "Long walk in the hills", "Trek"],
  ["HILL", "Small mountain", "Jack and Jill went up it"],
  ["HINT", "Little clue"],
  ["HIVE", "Home sweet home for bees", "Buzzing box in the orchard"],
  ["HOME", "Where the heart is", "Sweet ___"],
  ["HONK", "Goose's greeting"],
  ["HOOD", "Part of a coat to pull up in rain"],
  ["HOOP", "Basketball ring", "Hula ___"],
  ["HOOT", "Owl's call", "A real laugh"],
  ["HOPE", "Wish for the best", "Look forward"],
  ["HORN", "Car's beeper", "Brass instrument that blows"],
  ["HOUR", "Sixty minutes", "Clock's short hand counts these"],
  ["HOWL", "Wolf's moon song", "Laugh very loudly"],
  ["HUGE", "Enormous", "Whale-sized"],
  ["HUSH", "Shh!", "Quiet down"],
  // I
  ["ICON", "Little picture on a screen"],
  ["IDEA", "Light bulb moment", "Brainwave"],
  ["INCH", "Little bit of a ruler", "Move very slowly"],
  ["IRON", "Smooth out creases", "Metal in magnets"],
  ["ISLE", "Island, poetically"],
  ["ITEM", "Thing on a list"],
  // J
  ["JADE", "Green gemstone"],
  ["JAZZ", "Swinging music with saxophones"],
  ["JOIN", "Sign up for a club", "Link together"],
  ["JOKE", "Knock-knock, for one", "Something to crack"],
  ["JUMP", "Leap for joy", "Skipping rope move"],
  // K
  ["KALE", "Curly green veg"],
  ["KEEN", "Eager"],
  ["KEEP", "Hold on to", "Castle's strong tower"],
  ["KELP", "Seaweed forest"],
  ["KERB", "Edge of the pavement"],
  ["KICK", "Boot the ball", "Karate move"],
  ["KIND", "Nice and caring", "Type or sort"],
  ["KING", "Chess piece to checkmate", "Crown wearer"],
  ["KITE", "It has a tail and loves a windy day", "Soaring toy on a string"],
  ["KIWI", "Furry brown fruit, green inside", "Bird from New Zealand"],
  ["KNEE", "Joint halfway down your leg"],
  ["KNIT", "Make a scarf with needles", "Purl's partner"],
  ["KNOT", "Tie in a rope", "Unit of speed at sea"],
  // L
  ["LACE", "Shoe string", "Pretty, holey fabric"],
  ["LADY", "Polite word for a woman", "My fair ___"],
  ["LAKE", "Big pond for rowing", "Swan's big pond"],
  ["LAMB", "Young sheep in spring", "Mary had a little one"],
  ["LAMP", "Bedside light", "Aladdin's magic one"],
  ["LAND", "Ground ahoy!", "What a plane does at the end"],
  ["LANE", "Narrow country road", "Swimming pool strip"],
  ["LARK", "Songbird up at dawn", "Bit of fun"],
  ["LATE", "Not on time", "Up past bedtime"],
  ["LAVA", "Hot rock from a volcano"],
  ["LAWN", "Grass for the mower"],
  ["LEAF", "It turns orange in autumn", "Page of a book"],
  ["LEAP", "Big jump", "___ year"],
  ["LEEK", "Welsh national veg"],
  ["LEFT", "Opposite of right", "Went away"],
  ["LENS", "Glass bit in a camera"],
  ["LIFT", "Elevator", "Give someone a ride"],
  ["LILY", "Pond flower with a pad"],
  ["LIME", "Green citrus fruit"],
  ["LINE", "Queue", "Actor's words to learn"],
  ["LINK", "Chain piece", "Click it to go to a page"],
  ["LION", "King of the jungle", "Big cat with a mane"],
  ["LIST", "Shopping ___", "Santa checks it twice"],
  ["LOAF", "Bread before it's sliced"],
  ["LOCK", "It needs a key", "Curl of hair"],
  ["LOFT", "Room right up in the roof"],
  ["LOGO", "Symbol on a team shirt"],
  ["LONG", "Like a giraffe's neck", "Yearn"],
  ["LOOK", "Have a peep", "Glance"],
  ["LOOP", "Rollercoaster circle"],
  ["LOUD", "Turned up to max", "Like a drum solo"],
  ["LOVE", "Adore", "Zero, in tennis"],
  ["LUCK", "Good fortune", "Fingers crossed for it"],
  ["LUSH", "Green and leafy"],
  ["LYNX", "Wild cat with tufted ears"],
  // M
  ["MAIL", "Letters and parcels", "Postie's delivery"],
  ["MANE", "Lion's shaggy collar"],
  ["MANY", "Lots and lots"],
  ["MASK", "Face cover for a party", "Superhero's disguise"],
  ["MAST", "Pole on a sailing ship"],
  ["MATE", "Friend", "Check___!"],
  ["MAZE", "Puzzle of twisting paths"],
  ["MEAL", "Breakfast, lunch or dinner", "Sit-down feast"],
  ["MELT", "What a snowman does in the sun", "Turn to goo"],
  ["MENU", "List of things to eat"],
  ["MICE", "More than one mouse"],
  ["MILD", "Gentle, not spicy"],
  ["MILE", "Distance a bit over 1.6 km"],
  ["MILK", "What a cow gives", "Cereal's splash"],
  ["MIND", "Brain's thinking", "___ the gap!"],
  ["MINT", "Fresh-tasting herb", "Where coins are made"],
  ["MIST", "Light fog", "Morning haze over a field"],
  ["MITT", "Oven glove"],
  ["MOAT", "Water around a castle"],
  ["MOLE", "Digger that leaves hills in lawns"],
  ["MOON", "It changes shape every night", "Cow jumped over it"],
  ["MOSS", "Soft green carpet on rocks"],
  ["MOTH", "Night flier drawn to lamps"],
  ["MOVE", "Get going", "Turn in chess"],
  ["MULE", "Half donkey, half horse"],
  ["MUSE", "Inspiration", "Think deeply"],
  ["MYTH", "Old legend"],
  // N
  ["NAIL", "Hammer's target", "It grows on your fingertip"],
  ["NAME", "What you're called", "Title"],
  ["NEAR", "Close by"],
  ["NEAT", "Tidy", "Really cool!"],
  ["NECK", "Giraffe's long bit"],
  ["NEST", "Cup of twigs for eggs", "Home of the chicks"],
  ["NEWS", "What this paper brings you", "Latest happenings"],
  ["NEWT", "Small spotty pond creature"],
  ["NICE", "Pleasant", "Sugar and spice and all things ___"],
  ["NINE", "Three times three"],
  ["NOON", "Midday"],
  ["NOSE", "Sniffer in the middle of your face", "It knows when cookies are baking"],
  ["NOTE", "Quick message", "Do, re or mi"],
  ["NOUN", "Naming word"],
  // O
  ["OATH", "Solemn promise"],
  ["OBOE", "Reedy woodwind instrument"],
  ["OKAY", "All right"],
  ["ONCE", "___ upon a time"],
  ["ONLY", "Just the one"],
  ["OPAL", "Shimmery gemstone"],
  ["OPEN", "Not shut", "We're ___!"],
  ["ORCA", "Black-and-white whale"],
  ["OVAL", "Egg shape"],
  ["OVEN", "Where the cake bakes", "Kitchen hot box"],
  ["OVER", "Above", "Six balls in cricket"],
  ["OXEN", "More than one ox"],
  // P
  ["PACE", "Speed of walking"],
  ["PACK", "Fill your suitcase", "Group of wolves"],
  ["PAGE", "One side of a leaf in a book", "Turn it to read on"],
  ["PAIL", "Bucket for sandcastles"],
  ["PAIR", "Two of a kind", "Socks come in one"],
  ["PALM", "Inside of your hand", "Tropical tree"],
  ["PARK", "Green space with swings", "Leave the car"],
  ["PART", "Piece of the whole", "Role in the play"],
  ["PATH", "Trail through the woods", "Garden walkway"],
  ["PEAK", "Mountain top"],
  ["PEAR", "Fruit that's round at the bottom", "Fruit on a partridge's tree"],
  ["PEEK", "Sneaky little look"],
  ["PEEL", "Banana skin", "Take the skin off"],
  ["PICK", "Choose", "Guitar plucker"],
  ["PIER", "Seaside walkway on legs"],
  ["PINE", "Tree with cones and needles"],
  ["PINK", "Colour of candyfloss", "Flamingo's colour"],
  ["PIPE", "Tube for water"],
  ["PLAN", "Scheme", "Blueprint"],
  ["PLAY", "Have fun", "Show on a stage"],
  ["PLUM", "Juicy purple fruit"],
  ["POEM", "Verse that may rhyme", "Limerick, for one"],
  ["POET", "Writer of rhymes"],
  ["POLE", "North or South ___", "Flag holder"],
  ["POND", "Home for ducks and frogs", "Where tadpoles grow up"],
  ["PONY", "Small horse", "Shetland, for one"],
  ["POOL", "Swimming ___", "Game with cues and balls"],
  ["POUR", "Tip out of a jug", "Rain very hard"],
  ["PUFF", "Little breath of air", "Cream ___"],
  ["PUMA", "Big cat of the Americas"],
  ["PURR", "Cat's happy hum"],
  ["PUSH", "Shove", "Give the swing a ___"],
  // Q
  ["QUIZ", "Test your knowledge", "Family ___ night"],
  // R
  ["RACE", "Contest of speed", "Egg-and-spoon ___"],
  ["RAFT", "Floating platform"],
  ["RAIN", "Showers from the clouds", "Umbrella weather"],
  ["RAKE", "Tool for gathering leaves"],
  ["RARE", "Uncommon", "Hard to find"],
  ["READ", "Enjoy a book", "What you're doing now"],
  ["REEF", "Coral ___"],
  ["REST", "Relax", "Time out"],
  ["RICE", "Grain in a risotto", "Pudding grain"],
  ["RIDE", "Trip on a bike", "Fairground attraction"],
  ["RING", "Wedding ___", "Sound of a doorbell"],
  ["RIPE", "Ready to eat"],
  ["RISE", "Go up, like bread dough", "What the sun does"],
  ["ROAD", "Street", "Cross the ___ safely"],
  ["ROAR", "Lion's loud call", "Crowd's cheer"],
  ["ROBE", "Dressing gown"],
  ["ROCK", "Stone", "Music with loud guitars"],
  ["ROLL", "Bread bun", "Dice move"],
  ["ROOF", "House top", "Where Santa lands"],
  ["ROOM", "Space", "Space to spread out"],
  ["ROOT", "Plant's underground anchor"],
  ["ROPE", "Skipping ___"],
  ["ROSE", "Red flower with thorns", "Got up"],
  ["ROSY", "Pink-cheeked"],
  ["RUBY", "Red gemstone"],
  ["RULE", "Game regulation", "Draw a straight line"],
  // S
  ["SAFE", "Secure", "Box for treasure"],
  ["SAIL", "Boat's canvas", "Cruise on the breeze"],
  ["SALT", "Seasoning for chips", "Sea water's secret ingredient"],
  ["SAND", "Beach stuff for castles", "Stuff for an hourglass"],
  ["SEAL", "Flippered swimmer", "Close up an envelope"],
  ["SEED", "Tiny plant starter", "Sunflower snack"],
  ["SHIP", "Big boat", "Post a parcel"],
  ["SHOE", "Footwear with a sole", "Cinderella lost a glass one"],
  ["SHOP", "Store", "Go buying"],
  ["SIGN", "Write your autograph", "Stop or Give Way, on a post"],
  ["SILK", "Fabric from worms"],
  ["SING", "Carol, say", "Belt out a tune"],
  ["SKIP", "Hop along", "Miss out"],
  ["SNOW", "Winter flakes", "It makes the whole world white"],
  ["SNUG", "Cosy"],
  ["SOAP", "Bubbles maker", "Telly drama that runs and runs"],
  ["SOCK", "Foot cover", "Christmas stocking's little cousin"],
  ["SOFA", "Couch", "Comfy seat for three"],
  ["SOFT", "Squishy", "Like a pillow"],
  ["SOIL", "Earth for planting"],
  ["SOLO", "Performed alone"],
  ["SONG", "Tune with words", "Singalong number"],
  ["SOUP", "Warm broth", "Tomato ___"],
  ["SPIN", "Twirl"],
  ["SPOT", "Dot", "See"],
  ["STAR", "Twinkler in the sky", "Lead actor"],
  ["STEP", "Stair", "Dance move"],
  ["STEW", "Hearty casserole"],
  ["SWAN", "Graceful bird on the river", "Ugly duckling, grown up"],
  ["SWIM", "Do lengths in the pool", "Float and splash"],
  // T
  ["TAIL", "Wagger at the back", "Heads or ___?"],
  ["TALE", "Story", "Fairy ___"],
  ["TALL", "Like a giraffe"],
  ["TAME", "Gentle and friendly"],
  ["TAPE", "Sticky strip"],
  ["TEAM", "Side in a match", "Group working together"],
  ["TENT", "Camping shelter", "Pitch it in a field"],
  ["TIDE", "Sea's rise and fall", "High or low water"],
  ["TIDY", "Neat"],
  ["TILE", "Square on a bathroom wall"],
  ["TIME", "What a clock tells", "Once upon a ___"],
  ["TINY", "Very small"],
  ["TOAD", "Bumpy-skinned hopper"],
  ["TOFU", "Bean curd"],
  ["TOOL", "Hammer or spanner", "Spanner or screwdriver"],
  ["TOWN", "Place bigger than a village"],
  ["TRAM", "Street train on rails"],
  ["TRAY", "Flat board for carrying drinks", "Ice-cube ___"],
  ["TREE", "Oak or elm", "It grows from a seed"],
  ["TRIO", "Group of three"],
  ["TRIP", "Journey", "Day out"],
  ["TUBA", "Big brass instrument"],
  ["TUNA", "Fish in a sandwich"],
  ["TUNE", "Melody", "Song you can hum"],
  ["TWIG", "Small stick"],
  ["TWIN", "One of a matching pair", "Double of a sibling"],
  // U
  ["UNDO", "Reverse a mistake"],
  ["UNIT", "Metre or gram, say"],
  // V
  ["VASE", "Pot for flowers"],
  ["VERB", "Doing word"],
  ["VEST", "Undershirt"],
  ["VIEW", "Scenery"],
  ["VINE", "Climbing plant"],
  // W
  ["WADE", "Paddle in the shallows"],
  ["WAIT", "Hold on", "Stay put"],
  ["WAKE", "Stop sleeping"],
  ["WALK", "Stroll", "Take the dog out"],
  ["WAND", "Magic stick"],
  ["WARM", "Toasty", "Snug as a hot-water bottle"],
  ["WASH", "Clean with soap", "Scrub up before tea"],
  ["WAVE", "Hello from afar", "Surfer's ride"],
  ["WEEK", "Seven days", "Monday to Sunday"],
  ["WELL", "Wishing ___", "Healthy and happy"],
  ["WEST", "Where the sun sets"],
  ["WHIM", "Sudden fancy"],
  ["WIDE", "Broad"],
  ["WILD", "Untamed", "Like a jungle"],
  ["WIND", "Breeze", "Turn a clock key"],
  ["WING", "Flapper on a bird", "Part of a plane"],
  ["WINK", "Cheeky eye signal"],
  ["WISE", "Clever, like an owl"],
  ["WISH", "Hope on a star", "Blow out the candles and make one"],
  ["WOLF", "Howler at the moon"],
  ["WOOD", "Timber", "Forest"],
  ["WOOL", "Sheep's coat", "Knitter's supply"],
  ["WORD", "What you're filling in"],
  ["WORM", "Wriggler in the soil", "Early bird's catch"],
  ["WRAP", "Gift ___"],
  ["WREN", "Tiny brown bird"],
  // Y
  ["YARD", "Three feet"],
  ["YARN", "Knitting wool", "Long story"],
  ["YAWN", "Sleepy stretch", "Sign it's bedtime"],
  ["YEAR", "365 days", "Twelve months"],
  ["YELL", "Shout"],
  ["YOGA", "Stretching exercise"],
  ["YOLK", "Yellow of an egg"],
  // Z
  ["ZANY", "Wacky"],
  ["ZERO", "Nothing at all", "Freezing point in Celsius"],
  ["ZEST", "Lemon peel", "Energy and enthusiasm"],
  ["ZINC", "Bluish-grey metal"],
  ["ZONE", "Area"],
  ["ZOOM", "Whizz along", "Close-up on a camera"],
];
